.TH "AbsoluteBurnPeriod" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbsoluteBurnPeriod
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBMonth\fP"
.br
.ti -1c
.RI "long \fBDay\fP"
.br
.ti -1c
.RI "long \fBStart\fP"
.br
.ti -1c
.RI "long \fBEnd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB899\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long AbsoluteBurnPeriod::Day"

.PP
Definition at line \fB902\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long AbsoluteBurnPeriod::End"

.PP
Definition at line \fB904\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long AbsoluteBurnPeriod::Month"

.PP
Definition at line \fB901\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long AbsoluteBurnPeriod::Start"

.PP
Definition at line \fB903\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
