.TH "AccelConstants" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AccelConstants
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBPoint\fP"
.br
.ti -1c
.RI "double \fBLine\fP"
.br
.ti -1c
.RI "double \fBLimit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB45\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double AccelConstants::Limit"

.PP
Definition at line \fB49\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double AccelConstants::Line"

.PP
Definition at line \fB48\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double AccelConstants::Point"

.PP
Definition at line \fB47\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
