.TH "AccelData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AccelData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxwaccl\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBAccelLoad\fP [256]"
.br
.ti -1c
.RI "char \fBAccelSave\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB37\fP of file \fBfsxwaccl\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char AccelData::AccelLoad[256]"

.PP
Definition at line \fB39\fP of file \fBfsxwaccl\&.h\fP\&.
.SS "char AccelData::AccelSave[256]"

.PP
Definition at line \fB40\fP of file \fBfsxwaccl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
