.TH "Acceleration" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Acceleration
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAcceleration\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAccelConstants\fP \fBac\fP [261]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB53\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Acceleration::Acceleration ()"

.PP
Definition at line \fB47\fP of file \fBfsxwmech\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAccelConstants\fP Acceleration::ac[261]"

.PP
Definition at line \fB55\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
