.TH "AirAttack" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AirAttack
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsairatk\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAirAttack\fP ()"
.br
.ti -1c
.RI "\fB~AirAttack\fP ()"
.br
.ti -1c
.RI "bool \fBCheckEffectiveness\fP (\fBAirAttackData\fP *atk, double TimeStep)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBAirAttackNumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB82\fP of file \fBfsairatk\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AirAttack::AirAttack ()"

.PP
Definition at line \fB60\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "AirAttack::~AirAttack ()"

.PP
Definition at line \fB65\fP of file \fBfsairatk\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool AirAttack::CheckEffectiveness (\fBAirAttackData\fP * atk, double TimeStep)"

.PP
Definition at line \fB70\fP of file \fBfsairatk\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long AirAttack::AirAttackNumber"

.PP
Definition at line \fB87\fP of file \fBfsairatk\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
