.TH "AirAttackData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AirAttackData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsairatk\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBAirAttackNumber\fP"
.br
.ti -1c
.RI "long \fBAirCraftNumber\fP"
.br
.ti -1c
.RI "long \fBCoverageLevel\fP"
.br
.ti -1c
.RI "long \fBPatternNumber\fP"
.br
.ti -1c
.RI "double \fBElapsedTime\fP"
.br
.ti -1c
.RI "double \fBEffectiveDuration\fP"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB69\fP of file \fBfsairatk\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long AirAttackData::AirAttackNumber"

.PP
Definition at line \fB71\fP of file \fBfsairatk\&.h\fP\&.
.SS "long AirAttackData::AirCraftNumber"

.PP
Definition at line \fB72\fP of file \fBfsairatk\&.h\fP\&.
.SS "long AirAttackData::CoverageLevel"

.PP
Definition at line \fB73\fP of file \fBfsairatk\&.h\fP\&.
.SS "double AirAttackData::EffectiveDuration"

.PP
Definition at line \fB76\fP of file \fBfsairatk\&.h\fP\&.
.SS "double AirAttackData::ElapsedTime"

.PP
Definition at line \fB75\fP of file \fBfsairatk\&.h\fP\&.
.SS "void* AirAttackData::next"

.PP
Definition at line \fB77\fP of file \fBfsairatk\&.h\fP\&.
.SS "long AirAttackData::PatternNumber"

.PP
Definition at line \fB74\fP of file \fBfsairatk\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
