.TH "AirCraft" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AirCraft
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsairatk\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAirCraft\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBAirCraftName\fP [256]"
.br
.ti -1c
.RI "long \fBUnits\fP"
.br
.ti -1c
.RI "double \fBPatternLength\fP [6]"
.br
.ti -1c
.RI "double \fBReturnTime\fP"
.br
.ti -1c
.RI "double \fBCost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB52\fP of file \fBfsairatk\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AirCraft::AirCraft ()"

.PP
Definition at line \fB45\fP of file \fBfsairatk\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char AirCraft::AirCraftName[256]"

.PP
Definition at line \fB54\fP of file \fBfsairatk\&.h\fP\&.
.SS "double AirCraft::Cost"

.PP
Definition at line \fB58\fP of file \fBfsairatk\&.h\fP\&.
.SS "double AirCraft::PatternLength[6]"

.PP
Definition at line \fB56\fP of file \fBfsairatk\&.h\fP\&.
.SS "double AirCraft::ReturnTime"

.PP
Definition at line \fB57\fP of file \fBfsairatk\&.h\fP\&.
.SS "long AirCraft::Units"

.PP
Definition at line \fB55\fP of file \fBfsairatk\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
