.TH "AirData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AirData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsairdlg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBAirFileName\fP [256]"
.br
.ti -1c
.RI "int \fBm\fP"
.br
.ti -1c
.RI "int \fBft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBfsairdlg\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char AirData::AirFileName[256]"

.PP
Definition at line \fB51\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int AirData::ft"

.PP
Definition at line \fB53\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int AirData::m"

.PP
Definition at line \fB52\fP of file \fBfsairdlg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
