.TH "AreaPerimeter" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AreaPerimeter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.PP
Inherits \fBAPolygon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAreaPerimeter\fP ()"
.br
.ti -1c
.RI "\fB~AreaPerimeter\fP ()"
.br
.ti -1c
.RI "void \fBarp\fP (long count)"
.br
.in -1c

Public Member Functions inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "\fBAPolygon\fP ()"
.br
.ti -1c
.RI "\fB~APolygon\fP ()"
.br
.ti -1c
.RI "long \fBOverlap\fP (long count)"
.br
.ti -1c
.RI "double \fBdirection\fP (double xpt1, double ypt1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBarea\fP"
.br
.ti -1c
.RI "double \fBperimeter\fP"
.br
.ti -1c
.RI "double \fBsperimeter\fP"
.br
.ti -1c
.RI "double \fBcuumslope\fP [2]"
.br
.in -1c

Public Attributes inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "double \fBstartx\fP"
.br
.ti -1c
.RI "double \fBstarty\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB451\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AreaPerimeter::AreaPerimeter ()"

.PP
Definition at line \fB45\fP of file \fBfsxwutil\&.cpp\fP\&.
.SS "AreaPerimeter::~AreaPerimeter ()"

.PP
Definition at line \fB55\fP of file \fBfsxwutil\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AreaPerimeter::arp (long count)"

.PP
Definition at line \fB60\fP of file \fBfsxwutil\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double AreaPerimeter::area"

.PP
Definition at line \fB454\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double AreaPerimeter::cuumslope[2]"

.PP
Definition at line \fB455\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double AreaPerimeter::perimeter"

.PP
Definition at line \fB454\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double AreaPerimeter::sperimeter"

.PP
Definition at line \fB454\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
