.TH "Attack" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Attack
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxwattk\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttack\fP ()"
.br
.ti -1c
.RI "\fB~Attack\fP ()"
.br
.ti -1c
.RI "bool \fBDirectAttack\fP (\fBAttackData\fP *attack, double TimeStep)"
.br
.ti -1c
.RI "bool \fBIndirectAttack\fP (\fBAttackData\fP *attack, double TimeStep)"
.br
.ti -1c
.RI "bool \fBParallelAttack\fP (\fBAttackData\fP *atk, double TimeStep)"
.br
.ti -1c
.RI "void \fBConductBurnout\fP (\fBAttackData\fP *atk)"
.br
.ti -1c
.RI "long \fBCheckOverlapAttacks\fP (long *attacks, double TimeStep)"
.br
.ti -1c
.RI "void \fBBoundingBox\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB106\fP of file \fBfsxwattk\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Attack::Attack ()"

.PP
Definition at line \fB83\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "Attack::~Attack ()"

.PP
Definition at line \fB97\fP of file \fBfsxwattk\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Attack::BoundingBox ()"

.PP
Definition at line \fB1627\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long Attack::CheckOverlapAttacks (long * attacks, double TimeStep)"

.PP
Definition at line \fB353\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void Attack::ConductBurnout (\fBAttackData\fP * atk)"

.PP
Definition at line \fB1884\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "bool Attack::DirectAttack (\fBAttackData\fP * attack, double TimeStep)"

.PP
Definition at line \fB371\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "bool Attack::IndirectAttack (\fBAttackData\fP * attack, double TimeStep)"

.PP
Definition at line \fB859\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "bool Attack::ParallelAttack (\fBAttackData\fP * atk, double TimeStep)"

.PP
Definition at line \fB1061\fP of file \fBfsxwattk\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
