.TH "AttackData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AttackData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxwattk\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBAttackNumber\fP"
.br
.ti -1c
.RI "long \fBFireNumber\fP"
.br
.ti -1c
.RI "long \fBLineNumber\fP"
.br
.ti -1c
.RI "long \fBCrewNum\fP"
.br
.ti -1c
.RI "long \fBBurnDelay\fP"
.br
.ti -1c
.RI "long \fBFireDist\fP"
.br
.ti -1c
.RI "long \fBCurrentPoint\fP"
.br
.ti -1c
.RI "long \fBNextPoint\fP"
.br
.ti -1c
.RI "long \fBBurnout\fP"
.br
.ti -1c
.RI "long \fBSuspended\fP"
.br
.ti -1c
.RI "long \fBIndirect\fP"
.br
.ti -1c
.RI "long \fBReverse\fP"
.br
.ti -1c
.RI "long \fBNumPoints\fP"
.br
.ti -1c
.RI "long \fBBurnLine\fP [2]"
.br
.ti -1c
.RI "long \fBBurnDirection\fP"
.br
.ti -1c
.RI "double \fBAttackTime\fP"
.br
.ti -1c
.RI "double \fBLineBuilt\fP"
.br
.ti -1c
.RI "double * \fBIndirectLine1\fP"
.br
.ti -1c
.RI "double * \fBIndirectLine2\fP"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB81\fP of file \fBfsxwattk\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long AttackData::AttackNumber"

.PP
Definition at line \fB83\fP of file \fBfsxwattk\&.h\fP\&.
.SS "double AttackData::AttackTime"

.PP
Definition at line \fB98\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::BurnDelay"

.PP
Definition at line \fB87\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::BurnDirection"

.PP
Definition at line \fB97\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::BurnLine[2]"

.PP
Definition at line \fB96\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::Burnout"

.PP
Definition at line \fB91\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::CrewNum"

.PP
Definition at line \fB86\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::CurrentPoint"

.PP
Definition at line \fB89\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::FireDist"

.PP
Definition at line \fB88\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::FireNumber"

.PP
Definition at line \fB84\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::Indirect"

.PP
Definition at line \fB93\fP of file \fBfsxwattk\&.h\fP\&.
.SS "double* AttackData::IndirectLine1"

.PP
Definition at line \fB100\fP of file \fBfsxwattk\&.h\fP\&.
.SS "double* AttackData::IndirectLine2"

.PP
Definition at line \fB101\fP of file \fBfsxwattk\&.h\fP\&.
.SS "double AttackData::LineBuilt"

.PP
Definition at line \fB99\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::LineNumber"

.PP
Definition at line \fB85\fP of file \fBfsxwattk\&.h\fP\&.
.SS "void* AttackData::next"

.PP
Definition at line \fB102\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::NextPoint"

.PP
Definition at line \fB90\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::NumPoints"

.PP
Definition at line \fB95\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::Reverse"

.PP
Definition at line \fB94\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long AttackData::Suspended"

.PP
Definition at line \fB92\fP of file \fBfsxwattk\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
