.TH "BurnHistory" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BurnHistory
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxpfront\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBDuffLoad\fP"
.br
.ti -1c
.RI "unsigned char \fBWoodyFuelType\fP"
.br
.ti -1c
.RI "unsigned char \fBSurfaceFuelModel\fP"
.br
.ti -1c
.RI "unsigned char \fBMoistures\fP [20]"
.br
.ti -1c
.RI "unsigned char \fBFlamePolyNum\fP"
.br
.ti -1c
.RI "unsigned char \fBWeightPolyNum\fP"
.br
.ti -1c
.RI "float \fBCrownLoadingBurned\fP"
.br
.ti -1c
.RI "float \fBFlameCoefX\fP [18]"
.br
.ti -1c
.RI "float \fBFlameCoefY\fP [18]"
.br
.ti -1c
.RI "float \fBWeightCoefX\fP [18]"
.br
.ti -1c
.RI "float \fBWeightCoefY\fP [18]"
.br
.ti -1c
.RI "float \fBFlameTime\fP"
.br
.ti -1c
.RI "float \fBTotalTime\fP"
.br
.ti -1c
.RI "double \fBLastIntegTime\fP"
.br
.ti -1c
.RI "float \fBTotalWeight\fP"
.br
.ti -1c
.RI "float \fBReactionIntensity\fP [2]"
.br
.ti -1c
.RI "float \fBFlameResidenceTime\fP [2]"
.br
.ti -1c
.RI "float \fBLastWtRemoved\fP"
.br
.ti -1c
.RI "float \fBCurWtRemoved\fP"
.br
.ti -1c
.RI "float \fBFlameWtRemoved\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB110\fP of file \fBfsxpfront\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float BurnHistory::CrownLoadingBurned"

.PP
Definition at line \fB118\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::CurWtRemoved"

.PP
Definition at line \fB130\fP of file \fBfsxpfront\&.h\fP\&.
.SS "short BurnHistory::DuffLoad"

.PP
Definition at line \fB112\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::FlameCoefX[18]"

.PP
Definition at line \fB119\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::FlameCoefY[18]"

.PP
Definition at line \fB120\fP of file \fBfsxpfront\&.h\fP\&.
.SS "unsigned char BurnHistory::FlamePolyNum"

.PP
Definition at line \fB116\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::FlameResidenceTime[2]"

.PP
Definition at line \fB128\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::FlameTime"

.PP
Definition at line \fB123\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::FlameWtRemoved"

.PP
Definition at line \fB131\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double BurnHistory::LastIntegTime"

.PP
Definition at line \fB125\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::LastWtRemoved"

.PP
Definition at line \fB129\fP of file \fBfsxpfront\&.h\fP\&.
.SS "unsigned char BurnHistory::Moistures[20]"

.PP
Definition at line \fB115\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::ReactionIntensity[2]"

.PP
Definition at line \fB127\fP of file \fBfsxpfront\&.h\fP\&.
.SS "unsigned char BurnHistory::SurfaceFuelModel"

.PP
Definition at line \fB114\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::TotalTime"

.PP
Definition at line \fB124\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::TotalWeight"

.PP
Definition at line \fB126\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::WeightCoefX[18]"

.PP
Definition at line \fB121\fP of file \fBfsxpfront\&.h\fP\&.
.SS "float BurnHistory::WeightCoefY[18]"

.PP
Definition at line \fB122\fP of file \fBfsxpfront\&.h\fP\&.
.SS "unsigned char BurnHistory::WeightPolyNum"

.PP
Definition at line \fB117\fP of file \fBfsxpfront\&.h\fP\&.
.SS "unsigned char BurnHistory::WoodyFuelType"

.PP
Definition at line \fB113\fP of file \fBfsxpfront\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
