.TH "Burn" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Burn
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.PP
Inherits \fBIntersections\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBurn\fP ()"
.br
.ti -1c
.RI "\fB~Burn\fP ()"
.br
.ti -1c
.RI "void \fBBurnIt\fP (long CurrentFire)"
.br
.ti -1c
.RI "void \fBEliminateFire\fP (long FireNum)"
.br
.ti -1c
.RI "void \fBDetermineSimLevelTimeStep\fP ()"
.br
.ti -1c
.RI "void \fBResetAllPerimThreads\fP ()"
.br
.ti -1c
.RI "void \fBBurnSpotThreads\fP ()"
.br
.ti -1c
.RI "void \fBSetSpotLocation\fP (long Loc)"
.br
.ti -1c
.RI "\fBEmbers::spotdata\fP * \fBGetSpotData\fP (double CurrentTimeStep)"
.br
.in -1c

Public Member Functions inherited from \fBIntersections\fP
.in +1c
.ti -1c
.RI "\fBIntersections\fP ()"
.br
.ti -1c
.RI "\fB~Intersections\fP ()"
.br
.ti -1c
.RI "double \fBarp\fP (int PerimNum, long count)"
.br
.ti -1c
.RI "void \fBCrossFires\fP (int check, long *firenum)"
.br
.ti -1c
.RI "void \fBCrossesWithBarriers\fP (long FireNum)"
.br
.ti -1c
.RI "void \fBCleanPerimeter\fP (long CurrentFire)"
.br
.ti -1c
.RI "void \fBResetIntersectionArrays\fP ()"
.br
.ti -1c
.RI "void \fBCloseCrossThreads\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBXUtilities\fP
.in +1c
.ti -1c
.RI "\fBXUtilities\fP ()"
.br
.ti -1c
.RI "\fB~XUtilities\fP ()"
.br
.ti -1c
.RI "void \fBAllocSwap\fP (long NumPoint)"
.br
.ti -1c
.RI "void \fBFreeSwap\fP ()"
.br
.ti -1c
.RI "void \fBGetSwap\fP (long NumPoint, double *xpt, double *ypt, double *ros, double *fli, double *rct)"
.br
.ti -1c
.RI "void \fBSetSwap\fP (long NumPoint, double xpt, double ypt, double ros, double fli, double rct)"
.br
.ti -1c
.RI "void \fBSwapTranz\fP (long writefire, long nump)"
.br
.ti -1c
.RI "void \fBtranz\fP (long count, long nump)"
.br
.ti -1c
.RI "void \fBrediscretize\fP (long *count, bool Reorder)"
.br
.ti -1c
.RI "void \fBRePositionFire\fP (long *firenum)"
.br
.ti -1c
.RI "void \fBRestoreDeadPoints\fP (long firenum)"
.br
.in -1c

Public Member Functions inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "\fBAPolygon\fP ()"
.br
.ti -1c
.RI "\fB~APolygon\fP ()"
.br
.ti -1c
.RI "long \fBOverlap\fP (long count)"
.br
.ti -1c
.RI "double \fBdirection\fP (double xpt1, double ypt1)"
.br
.in -1c

Public Member Functions inherited from \fBCompareRect\fP
.in +1c
.ti -1c
.RI "\fBCompareRect\fP ()"
.br
.ti -1c
.RI "\fB~CompareRect\fP ()"
.br
.ti -1c
.RI "void \fBInitRect\fP (long FireNum)"
.br
.ti -1c
.RI "void \fBWriteHiLo\fP (long FireNum)"
.br
.ti -1c
.RI "void \fBExchangeRect\fP (long FireNum)"
.br
.ti -1c
.RI "bool \fBXOverlap\fP ()"
.br
.ti -1c
.RI "bool \fBYOverlap\fP ()"
.br
.ti -1c
.RI "bool \fBBoundCross\fP (long Fire1, long Fire2)"
.br
.ti -1c
.RI "void \fBDetermineHiLo\fP (double xpt, double ypt)"
.br
.ti -1c
.RI "bool \fBMergeInAndOutOK1\fP (long Fire1, long Fire2)"
.br
.in -1c

Public Member Functions inherited from \fBStandardizePolygon\fP
.in +1c
.ti -1c
.RI "\fBStandardizePolygon\fP ()"
.br
.ti -1c
.RI "\fB~StandardizePolygon\fP ()"
.br
.ti -1c
.RI "long \fBFindExternalPoint\fP (long CurrentFire, long type)"
.br
.ti -1c
.RI "void \fBReorderPerimeter\fP (long CurrentFire, long NewBeginning)"
.br
.ti -1c
.RI "void \fBFindOuterFirePerimeter\fP (long CurrentFire)"
.br
.ti -1c
.RI "bool \fBCross\fP (double xpt1, double ypt1, double xpt2, double ypt2, double xpt1n, double ypt1n, double xpt2n, double ypt2n, double *newx, double *newy, long *dup1, long *dup2)"
.br
.ti -1c
.RI "void \fBDensityControl\fP (long CurrentFire)"
.br
.ti -1c
.RI "void \fBRemoveDuplicatePoints\fP (long CurrentFire)"
.br
.ti -1c
.RI "void \fBRemoveIdenticalPoints\fP (long FireNum)"
.br
.ti -1c
.RI "void \fBBoundingBox\fP (long CurrentFire)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBCanStillBurn\fP"
.br
.ti -1c
.RI "bool \fBStillBurning\fP"
.br
.ti -1c
.RI "long \fBDistMethod\fP"
.br
.ti -1c
.RI "long \fBrastmake\fP"
.br
.ti -1c
.RI "double \fBSIMTIME\fP"
.br
.ti -1c
.RI "double \fBCuumTimeIncrement\fP"
.br
.ti -1c
.RI "long * \fBNumSpots\fP"
.br
.ti -1c
.RI "long \fBTotalSpots\fP"
.br
.ti -1c
.RI "long \fBSpotFires\fP"
.br
.ti -1c
.RI "\fBRasterize\fP \fBrast\fP"
.br
.ti -1c
.RI "\fBAreaPerimeter\fP \fBprod\fP"
.br
.ti -1c
.RI "\fBFireEnvironment2\fP * \fBenv\fP"
.br
.ti -1c
.RI "\fBFELocalSite\fP * \fBfe\fP"
.br
.in -1c

Public Attributes inherited from \fBIntersections\fP
.in +1c
.ti -1c
.RI "\fBPostFrontal\fP \fBpost\fP"
.br
.in -1c

Public Attributes inherited from \fBXUtilities\fP
.in +1c
.ti -1c
.RI "long \fBExNumPts\fP"
.br
.ti -1c
.RI "long \fBOldNumPoints\fP"
.br
.ti -1c
.RI "double * \fBswapperim\fP"
.br
.in -1c

Public Attributes inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "double \fBstartx\fP"
.br
.ti -1c
.RI "double \fBstarty\fP"
.br
.in -1c

Public Attributes inherited from \fBCompareRect\fP
.in +1c
.ti -1c
.RI "double \fBXLO\fP"
.br
.ti -1c
.RI "double \fBXHI\fP"
.br
.ti -1c
.RI "double \fBYLO\fP"
.br
.ti -1c
.RI "double \fBYHI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1061\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Burn::Burn ()"

.PP
Definition at line \fB664\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "Burn::~Burn ()"

.PP
Definition at line \fB681\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Burn::BurnIt (long CurrentFire)"

.PP
Definition at line \fB692\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "void Burn::BurnSpotThreads ()"

.PP
Definition at line \fB1708\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "void Burn::DetermineSimLevelTimeStep ()"

.PP
Definition at line \fB1230\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "void Burn::EliminateFire (long FireNum)"

.PP
Definition at line \fB1575\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "\fBEmbers::spotdata\fP * Burn::GetSpotData (double CurrentTimeStep)"

.PP
Definition at line \fB1648\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "void Burn::ResetAllPerimThreads ()"

.PP
Definition at line \fB705\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "void Burn::SetSpotLocation (long Loc)"

.PP
Definition at line \fB1585\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Burn::CanStillBurn"

.PP
Definition at line \fB1101\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Burn::CuumTimeIncrement"

.PP
Definition at line \fB1104\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long Burn::DistMethod"

.PP
Definition at line \fB1103\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBFireEnvironment2\fP* Burn::env"

.PP
Definition at line \fB1110\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBFELocalSite\fP* Burn::fe"

.PP
Definition at line \fB1111\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long* Burn::NumSpots"

.PP
Definition at line \fB1105\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBAreaPerimeter\fP Burn::prod"

.PP
Definition at line \fB1109\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBRasterize\fP Burn::rast"

.PP
Definition at line \fB1108\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long Burn::rastmake"

.PP
Definition at line \fB1103\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Burn::SIMTIME"

.PP
Definition at line \fB1104\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long Burn::SpotFires"

.PP
Definition at line \fB1106\fP of file \fBfsx4\&.hpp\fP\&.
.SS "bool Burn::StillBurning"

.PP
Definition at line \fB1102\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long Burn::TotalSpots"

.PP
Definition at line \fB1106\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
