.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/burnupw.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/burnupw.h
.SH SYNOPSIS
.br
.PP
\fR#include 'splinex\&.h'\fP
.br
\fR#include 'fsxsync\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFuelStruct\fP"
.br
.ti -1c
.RI "struct \fBBurnStruct\fP"
.br
.ti -1c
.RI "class \fBBurnUp\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXNO\fP   20"
.br
.ti -1c
.RI "#define \fBMAXTYPES\fP   3"
.br
.ti -1c
.RI "#define \fBMAXKL\fP   (\fBMAXNO\fP * ( \fBMAXNO\fP + 1 ) / 2 + \fBMAXNO\fP )"
.br
.ti -1c
.RI "#define \fBMXSTEP\fP   20"
.br
.ti -1c
.RI "#define \fBSWITCHOUTSIDE\fP   0"
.br
.ti -1c
.RI "#define \fBSWITCHINSIDE\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpolynom\fP (double x, double a[], long)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAXKL   (\fBMAXNO\fP * ( \fBMAXNO\fP + 1 ) / 2 + \fBMAXNO\fP )"

.PP
Definition at line \fB33\fP of file \fBburnupw\&.h\fP\&.
.SS "#define MAXNO   20"

.PP
Definition at line \fB31\fP of file \fBburnupw\&.h\fP\&.
.SS "#define MAXTYPES   3"

.PP
Definition at line \fB32\fP of file \fBburnupw\&.h\fP\&.
.SS "#define MXSTEP   20"

.PP
Definition at line \fB34\fP of file \fBburnupw\&.h\fP\&.
.SS "#define SWITCHINSIDE   1"

.PP
Definition at line \fB36\fP of file \fBburnupw\&.h\fP\&.
.SS "#define SWITCHOUTSIDE   0"

.PP
Definition at line \fB35\fP of file \fBburnupw\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void polynom (double x, double a[], long)"

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
