.TH "BurnupFireRings" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BurnupFireRings
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxpfront\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBurnupFireRings\fP ()"
.br
.ti -1c
.RI "\fB~BurnupFireRings\fP ()"
.br
.ti -1c
.RI "void \fBBurnFireRings\fP (long StartRingNum, long EndRingNum)"
.br
.ti -1c
.RI "void \fBResetAllThreads\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB204\fP of file \fBfsxpfront\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BurnupFireRings::BurnupFireRings ()"

.PP
Definition at line \fB861\fP of file \fBfsxpfront\&.cpp\fP\&.
.SS "BurnupFireRings::~BurnupFireRings ()"

.PP
Definition at line \fB869\fP of file \fBfsxpfront\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void BurnupFireRings::BurnFireRings (long StartRingNum, long EndRingNum)"

.PP
Definition at line \fB875\fP of file \fBfsxpfront\&.cpp\fP\&.
.SS "void BurnupFireRings::ResetAllThreads ()"

.PP
Definition at line \fB969\fP of file \fBfsxpfront\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
