.TH "CanopyCharacteristics" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanopyCharacteristics
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxlandt\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCanopyCharacteristics\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBDefaultHeight\fP"
.br
.ti -1c
.RI "double \fBDefaultBase\fP"
.br
.ti -1c
.RI "double \fBDefaultDensity\fP"
.br
.ti -1c
.RI "double \fBHeight\fP"
.br
.ti -1c
.RI "double \fBCrownBase\fP"
.br
.ti -1c
.RI "double \fBBulkDensity\fP"
.br
.ti -1c
.RI "double \fBDiameter\fP"
.br
.ti -1c
.RI "double \fBFoliarMC\fP"
.br
.ti -1c
.RI "long \fBTolerance\fP"
.br
.ti -1c
.RI "long \fBSpecies\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB54\fP of file \fBfsxlandt\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CanopyCharacteristics::CanopyCharacteristics ()"

.PP
Definition at line \fB880\fP of file \fBfsglbvar\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double CanopyCharacteristics::BulkDensity"

.PP
Definition at line \fB62\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double CanopyCharacteristics::CrownBase"

.PP
Definition at line \fB61\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double CanopyCharacteristics::DefaultBase"

.PP
Definition at line \fB58\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double CanopyCharacteristics::DefaultDensity"

.PP
Definition at line \fB59\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double CanopyCharacteristics::DefaultHeight"

.PP
Definition at line \fB57\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double CanopyCharacteristics::Diameter"

.PP
Definition at line \fB63\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double CanopyCharacteristics::FoliarMC"

.PP
Definition at line \fB64\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double CanopyCharacteristics::Height"

.PP
Definition at line \fB60\fP of file \fBfsxlandt\&.h\fP\&.
.SS "long CanopyCharacteristics::Species"

.PP
Definition at line \fB66\fP of file \fBfsxlandt\&.h\fP\&.
.SS "long CanopyCharacteristics::Tolerance"

.PP
Definition at line \fB65\fP of file \fBfsxlandt\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
