.TH "celldata" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
celldata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxlandt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBe\fP"
.br
.ti -1c
.RI "short \fBs\fP"
.br
.ti -1c
.RI "short \fBa\fP"
.br
.ti -1c
.RI "short \fBf\fP"
.br
.ti -1c
.RI "short \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBfsxlandt\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "short celldata::a"

.PP
Definition at line \fB31\fP of file \fBfsxlandt\&.h\fP\&.
.SS "short celldata::c"

.PP
Definition at line \fB33\fP of file \fBfsxlandt\&.h\fP\&.
.SS "short celldata::e"

.PP
Definition at line \fB29\fP of file \fBfsxlandt\&.h\fP\&.
.SS "short celldata::f"

.PP
Definition at line \fB32\fP of file \fBfsxlandt\&.h\fP\&.
.SS "short celldata::s"

.PP
Definition at line \fB30\fP of file \fBfsxlandt\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
