.TH "ChangeValue" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChangeValue
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wwedits\&.h>\fP
.PP
Inherits TDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChangeValue\fP (TWindow *Parent, const char *resID, char *kind, double *val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB40\fP of file \fBwwedits\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ChangeValue::ChangeValue (TWindow * Parent, const char * resID, char * kind, double * val)"


.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
