.TH "CoarseWoody" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoarseWoody
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoarseWoody\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBUnits\fP"
.br
.ti -1c
.RI "double \fBDepth\fP"
.br
.ti -1c
.RI "double \fBTotalWeight\fP"
.br
.ti -1c
.RI "long \fBNumClasses\fP"
.br
.ti -1c
.RI "char \fBDescription\fP [64]"
.br
.ti -1c
.RI "\fBWoodyData\fP * \fBwd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB971\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CoarseWoody::CoarseWoody ()"

.PP
Definition at line \fB6868\fP of file \fBfsglbvar\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double CoarseWoody::Depth"

.PP
Definition at line \fB974\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char CoarseWoody::Description[64]"

.PP
Definition at line \fB977\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long CoarseWoody::NumClasses"

.PP
Definition at line \fB976\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double CoarseWoody::TotalWeight"

.PP
Definition at line \fB975\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long CoarseWoody::Units"

.PP
Definition at line \fB973\fP of file \fBfsglbvar\&.h\fP\&.
.SS "\fBWoodyData\fP* CoarseWoody::wd"

.PP
Definition at line \fB978\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
