.TH "CompoundCrew" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompoundCrew
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxwattk\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBNumCurrentCrews\fP"
.br
.ti -1c
.RI "long \fBNumTotalCrews\fP"
.br
.ti -1c
.RI "long \fBCompCrew\fP"
.br
.ti -1c
.RI "long * \fBCrewIndex\fP"
.br
.ti -1c
.RI "double * \fBMultiplier\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB65\fP of file \fBfsxwattk\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long CompoundCrew::CompCrew"

.PP
Definition at line \fB69\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long* CompoundCrew::CrewIndex"

.PP
Definition at line \fB70\fP of file \fBfsxwattk\&.h\fP\&.
.SS "double* CompoundCrew::Multiplier"

.PP
Definition at line \fB71\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long CompoundCrew::NumCurrentCrews"

.PP
Definition at line \fB67\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long CompoundCrew::NumTotalCrews"

.PP
Definition at line \fB68\fP of file \fBfsxwattk\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
