.TH "Crew" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crew
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxwattk\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrew\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBCrewName\fP [256]"
.br
.ti -1c
.RI "long \fBCompound\fP"
.br
.ti -1c
.RI "long \fBUnits\fP"
.br
.ti -1c
.RI "double \fBFlameLimit\fP"
.br
.ti -1c
.RI "double \fBLineProduction\fP [51]"
.br
.ti -1c
.RI "double \fBCost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB50\fP of file \fBfsxwattk\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Crew::Crew ()"

.PP
Definition at line \fB56\fP of file \fBfsxwattk\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long Crew::Compound"

.PP
Definition at line \fB53\fP of file \fBfsxwattk\&.h\fP\&.
.SS "double Crew::Cost"

.PP
Definition at line \fB57\fP of file \fBfsxwattk\&.h\fP\&.
.SS "char Crew::CrewName[256]"

.PP
Definition at line \fB52\fP of file \fBfsxwattk\&.h\fP\&.
.SS "double Crew::FlameLimit"

.PP
Definition at line \fB55\fP of file \fBfsxwattk\&.h\fP\&.
.SS "double Crew::LineProduction[51]"

.PP
Definition at line \fB56\fP of file \fBfsxwattk\&.h\fP\&.
.SS "long Crew::Units"

.PP
Definition at line \fB54\fP of file \fBfsxwattk\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
