.TH "crowndata32bits" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
crowndata32bits
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBh\fP"
.br
.ti -1c
.RI "int16_t \fBb\fP"
.br
.ti -1c
.RI "int16_t \fBp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB677\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t crowndata32bits::b"

.PP
Definition at line \fB680\fP of file \fBfsglbvar\&.h\fP\&.
.SS "int16_t crowndata32bits::h"

.PP
Definition at line \fB679\fP of file \fBfsglbvar\&.h\fP\&.
.SS "int16_t crowndata32bits::p"

.PP
Definition at line \fB681\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
