.TH "Crown" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crown
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrown\fP ()"
.br
.ti -1c
.RI "\fB~Crown\fP ()"
.br
.ti -1c
.RI "void \fBCrownIgnite\fP (double height, double base, double density)"
.br
.ti -1c
.RI "double \fBCrownSpread\fP (double avgros, double R10)"
.br
.ti -1c
.RI "void \fBCrownIntensity\fP (double cros, double *fli)"
.br
.ti -1c
.RI "void \fBCrownBurn\fP (double avgros, double fli, double AccelConstant)"
.br
.ti -1c
.RI "double \fBCrownBurn2\fP (double avgros, double fli, double AccelConstant, void *bt)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBA\fP"
.br
.ti -1c
.RI "double \fBIo\fP"
.br
.ti -1c
.RI "double \fBSFC\fP"
.br
.ti -1c
.RI "double \fBCrownFractionBurned\fP"
.br
.ti -1c
.RI "double \fBCrownLoadingBurned\fP"
.br
.ti -1c
.RI "double \fBHLCB\fP"
.br
.ti -1c
.RI "double \fBFoliarMC\fP"
.br
.ti -1c
.RI "double \fBCrownBulkDensity\fP"
.br
.ti -1c
.RI "double \fBTreeHeight\fP"
.br
.ti -1c
.RI "double \fBFlameLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB61\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Crown::Crown ()\fR [inline]\fP"

.PP
Definition at line \fB70\fP of file \fBfsx4\&.hpp\fP\&.
.SS "Crown::~Crown ()\fR [inline]\fP"

.PP
Definition at line \fB73\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Crown::CrownBurn (double avgros, double fli, double AccelConstant)"

.PP
Definition at line \fB87\fP of file \fBfsxwcrwn\&.cpp\fP\&.
.SS "double Crown::CrownBurn2 (double avgros, double fli, double AccelConstant, void * bt)"

.PP
Definition at line \fB114\fP of file \fBfsxwcrwn\&.cpp\fP\&.
.SS "void Crown::CrownIgnite (double height, double base, double density)"

.PP
Definition at line \fB25\fP of file \fBfsxwcrwn\&.cpp\fP\&.
.SS "void Crown::CrownIntensity (double cros, double * fli)"

.PP
Definition at line \fB66\fP of file \fBfsxwcrwn\&.cpp\fP\&.
.SS "double Crown::CrownSpread (double avgros, double R10)"

.PP
Definition at line \fB48\fP of file \fBfsxwcrwn\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double Crown::A"

.PP
Definition at line \fB66\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Crown::CrownBulkDensity"

.PP
Definition at line \fB67\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Crown::CrownFractionBurned"

.PP
Definition at line \fB66\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Crown::CrownLoadingBurned"

.PP
Definition at line \fB66\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Crown::FlameLength"

.PP
Definition at line \fB68\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Crown::FoliarMC"

.PP
Definition at line \fB67\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Crown::HLCB"

.PP
Definition at line \fB67\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Crown::Io"

.PP
Definition at line \fB66\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Crown::SFC"

.PP
Definition at line \fB66\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Crown::TreeHeight"

.PP
Definition at line \fB67\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
