.TH "DeadMoistureDescription" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeadMoistureDescription
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeadMoistureDescription\fP ()"
.br
.ti -1c
.RI "void \fBResetDescription\fP (long Station, long FuelSize)"
.br
.ti -1c
.RI "\fB~DeadMoistureDescription\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBNumAlloc\fP [\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"
.br
.ti -1c
.RI "long \fBNumStations\fP"
.br
.ti -1c
.RI "long \fBNumElevs\fP [\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"
.br
.ti -1c
.RI "long \fBNumSlopes\fP [\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"
.br
.ti -1c
.RI "long \fBNumAspects\fP [\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"
.br
.ti -1c
.RI "long \fBNumCovers\fP [\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"
.br
.ti -1c
.RI "long \fBNumFuels\fP [\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"
.br
.ti -1c
.RI "long \fBFuelKey\fP [\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP][256]"
.br
.ti -1c
.RI "long \fBNumHist\fP [\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"
.br
.ti -1c
.RI "double \fBEndTime\fP [\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"
.br
.ti -1c
.RI "\fBFms\fP ** \fBfms\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB657\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DeadMoistureDescription::DeadMoistureDescription ()"

.PP
Definition at line \fB109\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "DeadMoistureDescription::~DeadMoistureDescription ()"

.PP
Definition at line \fB140\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DeadMoistureDescription::ResetDescription (long Station, long FuelSize)"

.PP
Definition at line \fB122\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double DeadMoistureDescription::EndTime[\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"

.PP
Definition at line \fB675\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBFms\fP** DeadMoistureDescription::fms"

.PP
Definition at line \fB676\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureDescription::FuelKey[\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP][256]"

.PP
Definition at line \fB673\fP of file \fBfsx4\&.hpp\fP\&.
.SS "unsigned long DeadMoistureDescription::NumAlloc[\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"

.PP
Definition at line \fB659\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureDescription::NumAspects[\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"

.PP
Definition at line \fB667\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureDescription::NumCovers[\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"

.PP
Definition at line \fB669\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureDescription::NumElevs[\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"

.PP
Definition at line \fB663\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureDescription::NumFuels[\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"

.PP
Definition at line \fB671\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureDescription::NumHist[\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"

.PP
Definition at line \fB674\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureDescription::NumSlopes[\fBMAX_NUM_STATIONS\fP][\fBNUM_FUEL_SIZES\fP]"

.PP
Definition at line \fB665\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureDescription::NumStations"

.PP
Definition at line \fB661\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
