.TH "DeadMoistureHistory" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeadMoistureHistory
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBLastTime\fP"
.br
.ti -1c
.RI "double \fBSimTime\fP"
.br
.ti -1c
.RI "long \fBElevation\fP"
.br
.ti -1c
.RI "double \fBAirTemperature\fP"
.br
.ti -1c
.RI "double \fBRelHumidity\fP"
.br
.ti -1c
.RI "long \fBCloudCover\fP"
.br
.ti -1c
.RI "double \fBRainfall\fP"
.br
.ti -1c
.RI "double * \fBMoisture\fP"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB632\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double DeadMoistureHistory::AirTemperature"

.PP
Definition at line \fB640\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureHistory::CloudCover"

.PP
Definition at line \fB644\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long DeadMoistureHistory::Elevation"

.PP
Definition at line \fB638\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double DeadMoistureHistory::LastTime"

.PP
Definition at line \fB634\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double* DeadMoistureHistory::Moisture"

.PP
Definition at line \fB648\fP of file \fBfsx4\&.hpp\fP\&.
.SS "void* DeadMoistureHistory::next"

.PP
Definition at line \fB650\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double DeadMoistureHistory::Rainfall"

.PP
Definition at line \fB646\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double DeadMoistureHistory::RelHumidity"

.PP
Definition at line \fB642\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double DeadMoistureHistory::SimTime"

.PP
Definition at line \fB636\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
