.TH "DisplayData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisplayData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBCheckMetric\fP"
.br
.ti -1c
.RI "int \fBCheckEnglish\fP"
.br
.ti -1c
.RI "int \fBVCheckWhite\fP"
.br
.ti -1c
.RI "int \fBVCheckFLI\fP"
.br
.ti -1c
.RI "int \fBVCheckFL\fP"
.br
.ti -1c
.RI "int \fBVCheckROS\fP"
.br
.ti -1c
.RI "int \fBVCheckHA\fP"
.br
.ti -1c
.RI "int \fBSVGA\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBMAX\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBINT\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBFM\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBFR\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBFG\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBFB\fP"
.br
.ti -1c
.RI "char \fBCMAX\fP [10]"
.br
.ti -1c
.RI "char \fBCCINT\fP [10]"
.br
.ti -1c
.RI "char \fBCFM\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB137\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char DisplayData::CCINT[10]"

.PP
Definition at line \fB144\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char DisplayData::CFM[5]"

.PP
Definition at line \fB144\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DisplayData::CheckEnglish"

.PP
Definition at line \fB139\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DisplayData::CheckMetric"

.PP
Definition at line \fB139\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char DisplayData::CMAX[10]"

.PP
Definition at line \fB144\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DisplayData::FB"

.PP
Definition at line \fB142\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DisplayData::FG"

.PP
Definition at line \fB142\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DisplayData::FM"

.PP
Definition at line \fB142\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DisplayData::FR"

.PP
Definition at line \fB142\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DisplayData::INT"

.PP
Definition at line \fB142\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DisplayData::MAX"

.PP
Definition at line \fB142\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DisplayData::SVGA"

.PP
Definition at line \fB141\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DisplayData::VCheckFL"

.PP
Definition at line \fB140\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DisplayData::VCheckFLI"

.PP
Definition at line \fB140\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DisplayData::VCheckHA"

.PP
Definition at line \fB140\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DisplayData::VCheckROS"

.PP
Definition at line \fB140\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DisplayData::VCheckWhite"

.PP
Definition at line \fB140\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
