.TH "DurationData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DurationData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBStart\fP"
.br
.ti -1c
.RI "int \fBEnding\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBMo\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBDay\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBHr\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBMin\fP"
.br
.ti -1c
.RI "int \fBReset\fP"
.br
.ti -1c
.RI "char \fBSTMo\fP [10]"
.br
.ti -1c
.RI "char \fBSTDay\fP [10]"
.br
.ti -1c
.RI "char \fBSTHr\fP [10]"
.br
.ti -1c
.RI "char \fBCMo\fP [10]"
.br
.ti -1c
.RI "char \fBCDay\fP [10]"
.br
.ti -1c
.RI "char \fBCHr\fP [10]"
.br
.ti -1c
.RI "char \fBCMin\fP [10]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB243\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char DurationData::CDay[10]"

.PP
Definition at line \fB249\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char DurationData::CHr[10]"

.PP
Definition at line \fB249\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char DurationData::CMin[10]"

.PP
Definition at line \fB249\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char DurationData::CMo[10]"

.PP
Definition at line \fB249\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DurationData::Day"

.PP
Definition at line \fB246\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DurationData::Ending"

.PP
Definition at line \fB245\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DurationData::Hr"

.PP
Definition at line \fB246\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DurationData::Min"

.PP
Definition at line \fB246\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP DurationData::Mo"

.PP
Definition at line \fB246\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DurationData::Reset"

.PP
Definition at line \fB247\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int DurationData::Start"

.PP
Definition at line \fB245\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char DurationData::STDay[10]"

.PP
Definition at line \fB248\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char DurationData::STHr[10]"

.PP
Definition at line \fB248\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char DurationData::STMo[10]"

.PP
Definition at line \fB248\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
