.TH "emberdata" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emberdata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBPartDiam\fP"
.br
.ti -1c
.RI "double \fBZHeight\fP"
.br
.ti -1c
.RI "double \fBStartElev\fP"
.br
.ti -1c
.RI "double \fBCurrentTime\fP"
.br
.ti -1c
.RI "double \fBElapsedTime\fP"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB944\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double emberdata::CurrentTime"

.PP
Definition at line \fB951\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double emberdata::ElapsedTime"

.PP
Definition at line \fB952\fP of file \fBfsx4\&.hpp\fP\&.
.SS "void* emberdata::next"

.PP
Definition at line \fB953\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double emberdata::PartDiam"

.PP
Definition at line \fB948\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double emberdata::StartElev"

.PP
Definition at line \fB950\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double emberdata::x"

.PP
Definition at line \fB946\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double emberdata::y"

.PP
Definition at line \fB947\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double emberdata::ZHeight"

.PP
Definition at line \fB949\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
