.TH "Embers" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Embers
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.PP
Inherits \fBAPolygon\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBspotdata\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmbers\fP ()"
.br
.ti -1c
.RI "\fB~Embers\fP ()"
.br
.ti -1c
.RI "void \fBLoft\fP (double CFlameLength, double CFBurned, double CrownHeight, double LoadingBurned, double ROS, double SubTimeStep, double curtime)"
.br
.ti -1c
.RI "void \fBPlume\fP (double CFlameLength, double CFBurned)"
.br
.ti -1c
.RI "void \fBFlight\fP (double \fBCurTime\fP, double EndofTimeStep)"
.br
.ti -1c
.RI "void \fBOverlap\fP ()"
.br
.ti -1c
.RI "void \fBEmberReset\fP ()"
.br
.ti -1c
.RI "void \fBSpotReset\fP (long numspots, \fBspotdata\fP *ThisSpot)"
.br
.ti -1c
.RI "void \fBSetFireEnvironmentCalls\fP (\fBFireEnvironment2\fP *Env, \fBFELocalSite\fP *Fe)"
.br
.ti -1c
.RI "\fBemberdata\fP \fBExtractEmber\fP (long type)"
.br
.ti -1c
.RI "void \fBAddEmber\fP (\fBemberdata\fP *ember)"
.br
.in -1c

Public Member Functions inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "\fBAPolygon\fP ()"
.br
.ti -1c
.RI "\fB~APolygon\fP ()"
.br
.ti -1c
.RI "long \fBOverlap\fP (long count)"
.br
.ti -1c
.RI "double \fBdirection\fP (double xpt1, double ypt1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBspotdata\fP * \fBFirstSpot\fP"
.br
.ti -1c
.RI "\fBspotdata\fP * \fBCurSpot\fP"
.br
.ti -1c
.RI "\fBspotdata\fP * \fBNextSpot\fP"
.br
.ti -1c
.RI "\fBspotdata\fP * \fBCarrySpot\fP"
.br
.ti -1c
.RI "int \fBSpotSource\fP"
.br
.ti -1c
.RI "double \fBSteadyHeight\fP"
.br
.ti -1c
.RI "double \fBDuration\fP"
.br
.ti -1c
.RI "double \fBSourceRadius\fP"
.br
.ti -1c
.RI "double \fBSourcePower\fP"
.br
.ti -1c
.RI "long \fBNumEmbers\fP"
.br
.ti -1c
.RI "long \fBCarryOverEmbers\fP"
.br
.ti -1c
.RI "long \fBNumSpots\fP"
.br
.ti -1c
.RI "long \fBSpotFires\fP"
.br
.ti -1c
.RI "long \fBCarrySpots\fP"
.br
.ti -1c
.RI "fcoord \fBFcoord\fP"
.br
.in -1c

Public Attributes inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "double \fBstartx\fP"
.br
.ti -1c
.RI "double \fBstarty\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB957\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Embers::Embers ()"

.PP
Definition at line \fB59\fP of file \fBfsxwspot\&.cpp\fP\&.
.SS "Embers::~Embers (void)"

.PP
Definition at line \fB73\fP of file \fBfsxwspot\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Embers::AddEmber (\fBemberdata\fP * ember)"

.PP
Definition at line \fB645\fP of file \fBfsxwspot\&.cpp\fP\&.
.SS "void Embers::EmberReset ()"

.PP
Definition at line \fB592\fP of file \fBfsxwspot\&.cpp\fP\&.
.SS "\fBemberdata\fP Embers::ExtractEmber (long type)"

.PP
Definition at line \fB633\fP of file \fBfsxwspot\&.cpp\fP\&.
.SS "void Embers::Flight (double CurTime, double EndofTimeStep)"

.PP
Definition at line \fB254\fP of file \fBfsxwspot\&.cpp\fP\&.
.SS "void Embers::Loft (double CFlameLength, double CFBurned, double CrownHeight, double LoadingBurned, double ROS, double SubTimeStep, double curtime)"

.PP
Definition at line \fB126\fP of file \fBfsxwspot\&.cpp\fP\&.
.SS "void Embers::Overlap (void)"

.PP
Definition at line \fB671\fP of file \fBfsxwspot\&.cpp\fP\&.
.SS "void Embers::Plume (double CFlameLength, double CFBurned)"

.PP
Definition at line \fB195\fP of file \fBfsxwspot\&.cpp\fP\&.
.SS "void Embers::SetFireEnvironmentCalls (\fBFireEnvironment2\fP * Env, \fBFELocalSite\fP * Fe)"

.PP
Definition at line \fB83\fP of file \fBfsxwspot\&.cpp\fP\&.
.SS "void Embers::SpotReset (long numspots, \fBspotdata\fP * ThisSpot)"

.PP
Definition at line \fB611\fP of file \fBfsxwspot\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long Embers::CarryOverEmbers"

.PP
Definition at line \fB998\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBspotdata\fP* Embers::CarrySpot"

.PP
Definition at line \fB994\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long Embers::CarrySpots"

.PP
Definition at line \fB998\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBspotdata\fP* Embers::CurSpot"

.PP
Definition at line \fB992\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Embers::Duration"

.PP
Definition at line \fB997\fP of file \fBfsx4\&.hpp\fP\&.
.SS "fcoord Embers::Fcoord"

.PP
Definition at line \fB999\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBspotdata\fP* Embers::FirstSpot"

.PP
Definition at line \fB991\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBspotdata\fP* Embers::NextSpot"

.PP
Definition at line \fB993\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long Embers::NumEmbers"

.PP
Definition at line \fB998\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long Embers::NumSpots"

.PP
Definition at line \fB998\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Embers::SourcePower"

.PP
Definition at line \fB997\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Embers::SourceRadius"

.PP
Definition at line \fB997\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long Embers::SpotFires"

.PP
Definition at line \fB998\fP of file \fBfsx4\&.hpp\fP\&.
.SS "int Embers::SpotSource"

.PP
Definition at line \fB996\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Embers::SteadyHeight"

.PP
Definition at line \fB997\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
