.TH "EnvironmentData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnvironmentData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBones\fP"
.br
.ti -1c
.RI "double \fBtens\fP"
.br
.ti -1c
.RI "double \fBhundreds\fP"
.br
.ti -1c
.RI "double \fBthousands\fP"
.br
.ti -1c
.RI "double \fBtenthous\fP"
.br
.ti -1c
.RI "double \fBlivew\fP"
.br
.ti -1c
.RI "double \fBliveh\fP"
.br
.ti -1c
.RI "double \fBwindspd\fP"
.br
.ti -1c
.RI "double \fBwinddir\fP"
.br
.ti -1c
.RI "double \fBtws\fP"
.br
.ti -1c
.RI "double \fBtemp\fP"
.br
.ti -1c
.RI "double \fBhumid\fP"
.br
.ti -1c
.RI "double \fBsolrad\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB561\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double EnvironmentData::humid"

.PP
Definition at line \fB574\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::hundreds"

.PP
Definition at line \fB565\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::liveh"

.PP
Definition at line \fB569\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::livew"

.PP
Definition at line \fB568\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::ones"

.PP
Definition at line \fB563\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::solrad"

.PP
Definition at line \fB575\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::temp"

.PP
Definition at line \fB573\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::tens"

.PP
Definition at line \fB564\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::tenthous"

.PP
Definition at line \fB567\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::thousands"

.PP
Definition at line \fB566\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::tws"

.PP
Definition at line \fB572\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::winddir"

.PP
Definition at line \fB571\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double EnvironmentData::windspd"

.PP
Definition at line \fB570\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
