.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/farsite.hpp" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/farsite.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include 'fsdattyp\&.h'\fP
.br
\fR#include 'ftestrc\&.h'\fP
.br
\fR#include 'fsoutput\&.h'\fP
.br
\fR#include 'fsxwinpt\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTScrollBarData\fP"
.br
.ti -1c
.RI "struct \fBTTransWSData\fP"
.br
.ti -1c
.RI "struct \fBDisplayData\fP"
.br
.ti -1c
.RI "struct \fBTTransDisplayData\fP"
.br
.ti -1c
.RI "struct \fBLandDisplayData\fP"
.br
.ti -1c
.RI "struct \fBTTransLandDisplayData\fP"
.br
.ti -1c
.RI "struct \fBOutputData\fP"
.br
.ti -1c
.RI "struct \fBTTransOutputData\fP"
.br
.ti -1c
.RI "struct \fBModelData\fP"
.br
.ti -1c
.RI "struct \fBTTransModelData\fP"
.br
.ti -1c
.RI "struct \fBOptionsData\fP"
.br
.ti -1c
.RI "struct \fBTTransOptionsData\fP"
.br
.ti -1c
.RI "struct \fBDurationData\fP"
.br
.ti -1c
.RI "struct \fBTTransDurationData\fP"
.br
.ti -1c
.RI "struct \fBTransEnvtMap\fP"
.br
.ti -1c
.RI "struct \fBTransCombMap\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTRICT\fP"
.br
.ti -1c
.RI "#define \fBBULLSHIT\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BULLSHIT"

.PP
Definition at line \fB35\fP of file \fBfarsite\&.hpp\fP\&.
.SS "#define STRICT"

.PP
Definition at line \fB23\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
