.TH "FireData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FireData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsdattyp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFireData\fP ()"
.br
.ti -1c
.RI "\fB~FireData\fP ()"
.br
.ti -1c
.RI "long \fBGetFires\fP (long num)"
.br
.ti -1c
.RI "long \fBGetSpots\fP (long num)"
.br
.ti -1c
.RI "long \fBGetEnclaves\fP (long num)"
.br
.ti -1c
.RI "void \fBSetData\fP (long fires, long spots, long enclaves)"
.br
.ti -1c
.RI "void \fBReAllocData\fP ()"
.br
.ti -1c
.RI "void \fBReSet\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBnumber\fP"
.br
.ti -1c
.RI "long \fBcount\fP"
.br
.ti -1c
.RI "long \fBnumarrays\fP"
.br
.ti -1c
.RI "\fBFireStruct\fP * \fBFire1\fP"
.br
.ti -1c
.RI "\fBFireStruct\fP * \fBFire2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB92\fP of file \fBfsdattyp\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FireData::FireData ()"

.SS "FireData::~FireData ()"

.SH "Member Function Documentation"
.PP 
.SS "long FireData::GetEnclaves (long num)"

.SS "long FireData::GetFires (long num)"

.SS "long FireData::GetSpots (long num)"

.SS "void FireData::ReAllocData ()"

.SS "void FireData::ReSet ()"

.SS "void FireData::SetData (long fires, long spots, long enclaves)"

.SH "Member Data Documentation"
.PP 
.SS "long FireData::count"

.PP
Definition at line \fB94\fP of file \fBfsdattyp\&.h\fP\&.
.SS "\fBFireStruct\fP* FireData::Fire1"

.PP
Definition at line \fB98\fP of file \fBfsdattyp\&.h\fP\&.
.SS "\fBFireStruct\fP * FireData::Fire2"

.PP
Definition at line \fB98\fP of file \fBfsdattyp\&.h\fP\&.
.SS "long FireData::numarrays"

.PP
Definition at line \fB94\fP of file \fBfsdattyp\&.h\fP\&.
.SS "long FireData::number"

.PP
Definition at line \fB94\fP of file \fBfsdattyp\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
