.TH "FireRing" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FireRing
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxpfront\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBOriginalFireNumber\fP"
.br
.ti -1c
.RI "long \fBNumFires\fP"
.br
.ti -1c
.RI "long * \fBNumPoints\fP"
.br
.ti -1c
.RI "double \fBStartTime\fP"
.br
.ti -1c
.RI "double \fBElapsedTime\fP"
.br
.ti -1c
.RI "long \fBNumMergePoints\fP [2]"
.br
.ti -1c
.RI "\fBMergePoints\fP * \fBmergepoints\fP"
.br
.ti -1c
.RI "\fBPerimPoints\fP * \fBperimpoints\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB146\fP of file \fBfsxpfront\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double FireRing::ElapsedTime"

.PP
Definition at line \fB152\fP of file \fBfsxpfront\&.h\fP\&.
.SS "\fBMergePoints\fP* FireRing::mergepoints"

.PP
Definition at line \fB154\fP of file \fBfsxpfront\&.h\fP\&.
.SS "long FireRing::NumFires"

.PP
Definition at line \fB149\fP of file \fBfsxpfront\&.h\fP\&.
.SS "long FireRing::NumMergePoints[2]"

.PP
Definition at line \fB153\fP of file \fBfsxpfront\&.h\fP\&.
.SS "long* FireRing::NumPoints"

.PP
Definition at line \fB150\fP of file \fBfsxpfront\&.h\fP\&.
.SS "long FireRing::OriginalFireNumber"

.PP
Definition at line \fB148\fP of file \fBfsxpfront\&.h\fP\&.
.SS "\fBPerimPoints\fP* FireRing::perimpoints"

.PP
Definition at line \fB155\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double FireRing::StartTime"

.PP
Definition at line \fB151\fP of file \fBfsxpfront\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
