.TH "FireEnvironment" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FireEnvironment
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.PP
Inherits \fBLandscapeData\fP\&.
.PP
Inherited by \fBFECalls\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFireEnvironment\fP ()"
.br
.ti -1c
.RI "\fB~FireEnvironment\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBLandscapeData\fP
.in +1c
.ti -1c
.RI "void \fBElevConvert\fP (short)"
.br
.ti -1c
.RI "void \fBSlopeConvert\fP (short)"
.br
.ti -1c
.RI "void \fBAspectConvert\fP (short)"
.br
.ti -1c
.RI "void \fBFuelConvert\fP (short)"
.br
.ti -1c
.RI "void \fBCoverConvert\fP (short)"
.br
.ti -1c
.RI "void \fBHeightConvert\fP (short)"
.br
.ti -1c
.RI "void \fBBaseConvert\fP (short)"
.br
.ti -1c
.RI "void \fBDensityConvert\fP (short)"
.br
.ti -1c
.RI "void \fBDuffConvert\fP (short)"
.br
.ti -1c
.RI "void \fBWoodyConvert\fP (short)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBFoliarMC\fP"
.br
.ti -1c
.RI "double \fBAirTemp\fP"
.br
.ti -1c
.RI "double \fBAirHumid\fP"
.br
.ti -1c
.RI "double \fBPtTemperature\fP"
.br
.ti -1c
.RI "double \fBPtHumidity\fP"
.br
.ti -1c
.RI "double \fBXLocation\fP"
.br
.ti -1c
.RI "double \fBYLocation\fP"
.br
.ti -1c
.RI "long \fBStationNumber\fP"
.br
.ti -1c
.RI "long \fBposit\fP"
.br
.in -1c

Public Attributes inherited from \fBLandscapeData\fP
.in +1c
.ti -1c
.RI "\fBLandscapeStruct\fP \fBld\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBenvt\fP (double SIMTIME)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "long \fBLW\fP"
.br
.ti -1c
.RI "long \fBLH\fP"
.br
.ti -1c
.RI "double \fBohmc\fP"
.br
.ti -1c
.RI "double \fBthmc\fP"
.br
.ti -1c
.RI "double \fBhhmc\fP"
.br
.ti -1c
.RI "double \fBmwindspd\fP"
.br
.ti -1c
.RI "double \fBtwindspd\fP"
.br
.ti -1c
.RI "double \fBwwinddir\fP"
.br
.ti -1c
.RI "double \fBFuelTemp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB520\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FireEnvironment::FireEnvironment ()"

.PP
Definition at line \fB426\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "FireEnvironment::~FireEnvironment ()"

.PP
Definition at line \fB432\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void FireEnvironment::envt (double SIMTIME)\fR [protected]\fP"

.PP
Definition at line \fB437\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double FireEnvironment::AirHumid"

.PP
Definition at line \fB551\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::AirTemp"

.PP
Definition at line \fB551\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::FoliarMC"

.PP
Definition at line \fB551\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::FuelTemp\fR [protected]\fP"

.PP
Definition at line \fB544\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::hhmc\fR [protected]\fP"

.PP
Definition at line \fB544\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FireEnvironment::LH\fR [protected]\fP"

.PP
Definition at line \fB543\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FireEnvironment::LW\fR [protected]\fP"

.PP
Definition at line \fB543\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::mwindspd\fR [protected]\fP"

.PP
Definition at line \fB544\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::ohmc\fR [protected]\fP"

.PP
Definition at line \fB544\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FireEnvironment::posit"

.PP
Definition at line \fB554\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::PtHumidity"

.PP
Definition at line \fB551\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::PtTemperature"

.PP
Definition at line \fB551\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FireEnvironment::StationNumber"

.PP
Definition at line \fB554\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::thmc\fR [protected]\fP"

.PP
Definition at line \fB544\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::twindspd\fR [protected]\fP"

.PP
Definition at line \fB544\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::wwinddir\fR [protected]\fP"

.PP
Definition at line \fB544\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::XLocation"

.PP
Definition at line \fB553\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment::YLocation"

.PP
Definition at line \fB553\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
