.TH "FireEnvironment2" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FireEnvironment2
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFireEnvironment2\fP ()"
.br
.ti -1c
.RI "\fB~FireEnvironment2\fP ()"
.br
.ti -1c
.RI "void \fBResetData\fP (long FuelSize)"
.br
.ti -1c
.RI "void \fBResetAllThreads\fP ()"
.br
.ti -1c
.RI "void \fBTerminateHistory\fP ()"
.br
.ti -1c
.RI "bool \fBAllocStations\fP (long Num)"
.br
.ti -1c
.RI "void \fBFreeStations\fP ()"
.br
.ti -1c
.RI "double \fBGetMx\fP (double Time, long fuel, long elev, long slope, double aspectf, long cover, double *equil, double *solrad, long FuelSize)"
.br
.ti -1c
.RI "bool \fBCalcMapFuelMoistures\fP (double SimTime)"
.br
.ti -1c
.RI "bool \fBExportMoistureData\fP (char *FileName, char *Desc)"
.br
.ti -1c
.RI "bool \fBImportMoistureData\fP (char *FileName, char *Desc)"
.br
.ti -1c
.RI "bool \fBCheckMoistureTimes\fP (double SimTime)"
.br
.ti -1c
.RI "void \fBNormalizeMoistureStartTime\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBStationNumber\fP"
.br
.ti -1c
.RI "long \fBelevref\fP"
.br
.ti -1c
.RI "double \fBtempref\fP"
.br
.ti -1c
.RI "double \fBhumref\fP"
.br
.ti -1c
.RI "double \fBrain\fP"
.br
.ti -1c
.RI "double \fBhumidmx\fP"
.br
.ti -1c
.RI "double \fBhumidmn\fP"
.br
.ti -1c
.RI "double \fBtempmx\fP"
.br
.ti -1c
.RI "double \fBtempmn\fP"
.br
.ti -1c
.RI "\fBFmsThread\fP * \fBfmsthread\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB826\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FireEnvironment2::FireEnvironment2 ()"

.PP
Definition at line \fB493\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "FireEnvironment2::~FireEnvironment2 ()"

.PP
Definition at line \fB517\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool FireEnvironment2::AllocStations (long Num)"

.PP
Definition at line \fB616\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "bool FireEnvironment2::CalcMapFuelMoistures (double SimTime)"

.PP
Definition at line \fB524\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "bool FireEnvironment2::CheckMoistureTimes (double SimTime)"

.PP
Definition at line \fB1416\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "bool FireEnvironment2::ExportMoistureData (char * FileName, char * Desc)"

.PP
Definition at line \fB1654\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FireEnvironment2::FreeStations ()"

.PP
Definition at line \fB650\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "double FireEnvironment2::GetMx (double Time, long fuel, long elev, long slope, double aspectf, long cover, double * equil, double * solrad, long FuelSize)"

.PP
Definition at line \fB939\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "bool FireEnvironment2::ImportMoistureData (char * FileName, char * Desc)"

.PP
Definition at line \fB1758\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FireEnvironment2::NormalizeMoistureStartTime ()"

.PP
Definition at line \fB1372\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FireEnvironment2::ResetAllThreads ()"

.PP
Definition at line \fB697\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FireEnvironment2::ResetData (long FuelSize)"

.PP
Definition at line \fB606\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FireEnvironment2::TerminateHistory ()"

.PP
Definition at line \fB1331\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long FireEnvironment2::elevref"

.PP
Definition at line \fB860\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBFmsThread\fP* FireEnvironment2::fmsthread"

.PP
Definition at line \fB863\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment2::humidmn"

.PP
Definition at line \fB862\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment2::humidmx"

.PP
Definition at line \fB862\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment2::humref"

.PP
Definition at line \fB861\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment2::rain"

.PP
Definition at line \fB861\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FireEnvironment2::StationNumber"

.PP
Definition at line \fB859\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment2::tempmn"

.PP
Definition at line \fB862\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment2::tempmx"

.PP
Definition at line \fB862\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FireEnvironment2::tempref"

.PP
Definition at line \fB861\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
