.TH "FMS_Slopes" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FMS_Slopes
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFMS_Slopes\fP (long \fBFuelSize\fP)"
.br
.ti -1c
.RI "bool \fBAllocSlopes\fP ()"
.br
.ti -1c
.RI "void \fBFreeSlopes\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBElev\fP"
.br
.ti -1c
.RI "long \fBFuel\fP"
.br
.ti -1c
.RI "long \fBNumSlopes\fP"
.br
.ti -1c
.RI "long \fBFuelSize\fP"
.br
.ti -1c
.RI "long \fBLoVal\fP"
.br
.ti -1c
.RI "long \fBHiVal\fP"
.br
.ti -1c
.RI "\fBFMS_Aspects\fP ** \fBFms_Slope\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB734\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FMS_Slopes::FMS_Slopes (long FuelSize)"

.PP
Definition at line \fB2777\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool FMS_Slopes::AllocSlopes ()"

.PP
Definition at line \fB2785\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FMS_Slopes::FreeSlopes ()"

.PP
Definition at line \fB2842\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long FMS_Slopes::Elev"

.PP
Definition at line \fB736\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBFMS_Aspects\fP** FMS_Slopes::Fms_Slope"

.PP
Definition at line \fB742\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Slopes::Fuel"

.PP
Definition at line \fB736\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Slopes::FuelSize"

.PP
Definition at line \fB738\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Slopes::HiVal"

.PP
Definition at line \fB740\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Slopes::LoVal"

.PP
Definition at line \fB740\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Slopes::NumSlopes"

.PP
Definition at line \fB738\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
