.TH "FMS_Aspects" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FMS_Aspects
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFMS_Aspects\fP (long \fBFuelSize\fP)"
.br
.ti -1c
.RI "bool \fBAllocAspects\fP ()"
.br
.ti -1c
.RI "void \fBFreeAspects\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBSlope\fP"
.br
.ti -1c
.RI "long \fBElev\fP"
.br
.ti -1c
.RI "long \fBFuel\fP"
.br
.ti -1c
.RI "long \fBNumAspects\fP"
.br
.ti -1c
.RI "long \fBFuelSize\fP"
.br
.ti -1c
.RI "long \fBLoVal\fP"
.br
.ti -1c
.RI "long \fBHiVal\fP"
.br
.ti -1c
.RI "\fBFMS_Cover\fP ** \fBFms_Aspect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB714\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FMS_Aspects::FMS_Aspects (long FuelSize)"

.PP
Definition at line \fB2867\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool FMS_Aspects::AllocAspects ()"

.PP
Definition at line \fB2875\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FMS_Aspects::FreeAspects ()"

.PP
Definition at line \fB2912\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long FMS_Aspects::Elev"

.PP
Definition at line \fB716\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBFMS_Cover\fP** FMS_Aspects::Fms_Aspect"

.PP
Definition at line \fB722\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Aspects::Fuel"

.PP
Definition at line \fB716\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Aspects::FuelSize"

.PP
Definition at line \fB718\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Aspects::HiVal"

.PP
Definition at line \fB720\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Aspects::LoVal"

.PP
Definition at line \fB720\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Aspects::NumAspects"

.PP
Definition at line \fB718\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Aspects::Slope"

.PP
Definition at line \fB716\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
