.TH "FMS_Elevations" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FMS_Elevations
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFMS_Elevations\fP (long \fBFuelSize\fP)"
.br
.ti -1c
.RI "void \fBSetFuel\fP (long \fBFuel\fP)"
.br
.ti -1c
.RI "bool \fBAllocElevations\fP ()"
.br
.ti -1c
.RI "void \fBFreeElevations\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBNumElevs\fP"
.br
.ti -1c
.RI "long \fBFuel\fP"
.br
.ti -1c
.RI "long \fBFuelSize\fP"
.br
.ti -1c
.RI "double \fBFirstTime\fP"
.br
.ti -1c
.RI "double \fBLastTime\fP"
.br
.ti -1c
.RI "\fBFMS_Slopes\fP ** \fBFms_Elev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB753\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FMS_Elevations::FMS_Elevations (long FuelSize)"

.PP
Definition at line \fB2692\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool FMS_Elevations::AllocElevations ()"

.PP
Definition at line \fB2703\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FMS_Elevations::FreeElevations ()"

.PP
Definition at line \fB2747\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FMS_Elevations::SetFuel (long Fuel)"

.PP
Definition at line \fB2737\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double FMS_Elevations::FirstTime"

.PP
Definition at line \fB757\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBFMS_Slopes\fP** FMS_Elevations::Fms_Elev"

.PP
Definition at line \fB759\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Elevations::Fuel"

.PP
Definition at line \fB756\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Elevations::FuelSize"

.PP
Definition at line \fB756\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FMS_Elevations::LastTime"

.PP
Definition at line \fB758\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Elevations::NumElevs"

.PP
Definition at line \fB755\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
