.TH "FMS_Cover" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FMS_Cover
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFMS_Cover\fP (long \fBFuelSize\fP)"
.br
.ti -1c
.RI "bool \fBAllocCover\fP ()"
.br
.ti -1c
.RI "void \fBFreeCover\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFms\fP ** \fBfms\fP"
.br
.ti -1c
.RI "long \fBFuelSize\fP"
.br
.ti -1c
.RI "long \fBLoVal\fP"
.br
.ti -1c
.RI "long \fBHiVal\fP"
.br
.ti -1c
.RI "double \fBSolRad\fP"
.br
.ti -1c
.RI "double \fBAspectf\fP"
.br
.ti -1c
.RI "long \fBNumFms\fP"
.br
.ti -1c
.RI "long \fBAspect\fP"
.br
.ti -1c
.RI "long \fBElev\fP"
.br
.ti -1c
.RI "long \fBFuel\fP"
.br
.ti -1c
.RI "long \fBSlope\fP"
.br
.ti -1c
.RI "double * \fBLastMx\fP"
.br
.ti -1c
.RI "double * \fBNextMx\fP"
.br
.ti -1c
.RI "double * \fBLastEq\fP"
.br
.ti -1c
.RI "double * \fBNextEq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB692\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FMS_Cover::FMS_Cover (long FuelSize)"

.PP
Definition at line \fB2937\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool FMS_Cover::AllocCover ()"

.PP
Definition at line \fB2949\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FMS_Cover::FreeCover ()"

.PP
Definition at line \fB3007\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long FMS_Cover::Aspect"

.PP
Definition at line \fB701\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FMS_Cover::Aspectf"

.PP
Definition at line \fB699\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Cover::Elev"

.PP
Definition at line \fB701\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBFms\fP** FMS_Cover::fms"

.PP
Definition at line \fB694\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Cover::Fuel"

.PP
Definition at line \fB701\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Cover::FuelSize"

.PP
Definition at line \fB695\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Cover::HiVal"

.PP
Definition at line \fB697\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double* FMS_Cover::LastEq"

.PP
Definition at line \fB704\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double* FMS_Cover::LastMx"

.PP
Definition at line \fB702\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Cover::LoVal"

.PP
Definition at line \fB696\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double* FMS_Cover::NextEq"

.PP
Definition at line \fB705\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double* FMS_Cover::NextMx"

.PP
Definition at line \fB703\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Cover::NumFms"

.PP
Definition at line \fB700\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FMS_Cover::Slope"

.PP
Definition at line \fB701\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FMS_Cover::SolRad"

.PP
Definition at line \fB698\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
