.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsatkdlg.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsatkdlg.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include 'fsxwattk\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTScrollBarData\fP"
.br
.ti -1c
.RI "struct \fBTransAttack\fP"
.br
.ti -1c
.RI "struct \fBTTransAttackData\fP"
.br
.ti -1c
.RI "struct \fBTransMult\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
