.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsglbvar.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsglbvar.h
.SH SYNOPSIS
.br
.PP
\fR#include 'themes\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include 'fsxwatm\&.h'\fP
.br
\fR#include 'fsxw\&.hpp'\fP
.br
\fR#include 'fsx4\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBThemes\fP"
.br
.ti -1c
.RI "struct \fBVectorStorage\fP"
.br
.ti -1c
.RI "struct \fBstreamdata\fP"
.br
.ti -1c
.RI "struct \fBWindData\fP"
.br
.ti -1c
.RI "struct \fBWeatherData\fP"
.br
.ti -1c
.RI "struct \fBStationGrid\fP"
.br
.ti -1c
.RI "struct \fBFuelConversions\fP"
.br
.ti -1c
.RI "struct \fBoldcelldata\fP"
.br
.ti -1c
.RI "struct \fBoldheaddata\fP"
.br
.ti -1c
.RI "struct \fBheaddata2\fP"
.br
.ti -1c
.RI "struct \fB__attribute__\fP"
.br
.ti -1c
.RI "struct \fBcelldata32bits\fP"
.br
.ti -1c
.RI "struct \fBcrowndata32bits\fP"
.br
.ti -1c
.RI "struct \fBgrounddata32bits\fP"
.br
.ti -1c
.RI "struct \fBheaddata\fP"
.br
.ti -1c
.RI "struct \fBAbsoluteBurnPeriod\fP"
.br
.ti -1c
.RI "struct \fBRelativeBurnPeriod\fP"
.br
.ti -1c
.RI "struct \fBInitialFuelMoisture\fP"
.br
.ti -1c
.RI "struct \fBWoodyData\fP"
.br
.ti -1c
.RI "struct \fBCoarseWoody\fP"
.br
.ti -1c
.RI "struct \fBNewFuel\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNULLLOCATION\fP   0"
.br
.ti -1c
.RI "#define \fBIGNITIONLOCATION\fP   1"
.br
.ti -1c
.RI "#define \fBBARRIERLOCATION\fP   2"
.br
.ti -1c
.RI "#define \fBFUELLOCATION\fP   3"
.br
.ti -1c
.RI "#define \fBWEATHERLOCATION\fP   4"
.br
.ti -1c
.RI "#define \fBZOOMLOCATION\fP   5"
.br
.ti -1c
.RI "#define \fBEDITLOCATION\fP   6"
.br
.ti -1c
.RI "#define \fBDIRECTLOCATION\fP   7"
.br
.ti -1c
.RI "#define \fBINDIRECTLOCATION\fP   8"
.br
.ti -1c
.RI "#define \fBPARALLELLOCATION\fP   9"
.br
.ti -1c
.RI "#define \fBAERIALLOCATION\fP   10"
.br
.ti -1c
.RI "#define \fBRELOCATEDIRECT\fP   11"
.br
.ti -1c
.RI "#define \fBRELOCATEINDIRECT\fP   12"
.br
.ti -1c
.RI "#define \fBRELOCATEPARALLEL\fP   13"
.br
.ti -1c
.RI "#define \fBRELOCATEAIRATTACK\fP   14"
.br
.ti -1c
.RI "#define \fBADDGROUNDATTACK\fP   15"
.br
.ti -1c
.RI "#define \fBFIREINFORMATION\fP   16"
.br
.ti -1c
.RI "#define \fBMOVEPERIMPOINTS\fP   17"
.br
.ti -1c
.RI "#define \fBPANLANDSCAPE\fP   18"
.br
.ti -1c
.RI "#define \fBSTOPLOCATION\fP   19"
.br
.ti -1c
.RI "#define \fBMEASURELANDSCAPE\fP   20"
.br
.ti -1c
.RI "#define \fBWW_UNITS_METRIC\fP   1"
.br
.ti -1c
.RI "#define \fBWW_UNITS_ENGLISH\fP   0"
.br
.ti -1c
.RI "#define \fBWW_UNITS_UNDEFINED\fP   \-1"
.br
.ti -1c
.RI "#define \fBRAST_ARRIVALTIME\fP   20"
.br
.ti -1c
.RI "#define \fBRAST_FIREINTENSITY\fP   21"
.br
.ti -1c
.RI "#define \fBRAST_SPREADRATE\fP   22"
.br
.ti -1c
.RI "#define \fBRAST_FLAMELENGTH\fP   23"
.br
.ti -1c
.RI "#define \fBRAST_HEATPERAREA\fP   24"
.br
.ti -1c
.RI "#define \fBRAST_CROWNFIRE\fP   25"
.br
.ti -1c
.RI "#define \fBRAST_FIREDIRECTION\fP   26"
.br
.ti -1c
.RI "#define \fBRAST_REACTIONINTENSITY\fP   27"
.br
.ti -1c
.RI "#define \fBE_DATA\fP   0"
.br
.ti -1c
.RI "#define \fBS_DATA\fP   1"
.br
.ti -1c
.RI "#define \fBA_DATA\fP   2"
.br
.ti -1c
.RI "#define \fBF_DATA\fP   3"
.br
.ti -1c
.RI "#define \fBC_DATA\fP   4"
.br
.ti -1c
.RI "#define \fBH_DATA\fP   5"
.br
.ti -1c
.RI "#define \fBB_DATA\fP   6"
.br
.ti -1c
.RI "#define \fBP_DATA\fP   7"
.br
.ti -1c
.RI "#define \fBD_DATA\fP   8"
.br
.ti -1c
.RI "#define \fBW_DATA\fP   9"
.br
.ti -1c
.RI "#define \fBFM_INTERVAL_TIME\fP   0"
.br
.ti -1c
.RI "#define \fBFM_INTERVAL_ELEV\fP   1"
.br
.ti -1c
.RI "#define \fBFM_INTERVAL_SLOPE\fP   2"
.br
.ti -1c
.RI "#define \fBFM_INTERVAL_ASP\fP   3"
.br
.ti -1c
.RI "#define \fBFM_INTERVAL_COV\fP   4"
.br
.ti -1c
.RI "#define \fBRGB\fP(r,  g,  b)   ((unsigned long) (((char)(r) |((unsigned int)(g) << 8 | (((unsigned long)(char) (b)))<<16))))"
.br
.ti -1c
.RI "#define \fBMAXNUM_COARSEWOODY_MODELS\fP   256"
.br
.ti -1c
.RI "#define \fBCWD_COMBINE_NEVER\fP   1"
.br
.ti -1c
.RI "#define \fBCWD_COMBINE_ALWAYS\fP   2"
.br
.ti -1c
.RI "#define \fBCWD_COMBINE_ABSENT\fP   3"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned long \fBCOLORREF\fP"
.br
.ti -1c
.RI "typedef struct \fB__attribute__\fP \fBheaddata32bit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCheckMessageLoop\fP ()"
.br
.ti -1c
.RI "double \fBpow2\fP (double base)"
.br
.ti -1c
.RI "void \fBGetRatios\fP (double *xratio, double *yratio)"
.br
.ti -1c
.RI "void \fBSetRatios\fP (double xratio, double yratio)"
.br
.ti -1c
.RI "void \fBGetMaxDims\fP (double *maxx, double *maxy)"
.br
.ti -1c
.RI "void \fBSetMaxDims\fP (double maxx, double maxy)"
.br
.ti -1c
.RI "void \fBSetXORArrows\fP (bool TorF)"
.br
.ti -1c
.RI "bool \fBGetXORArrows\fP ()"
.br
.ti -1c
.RI "int \fBGetFuelsAltered\fP ()"
.br
.ti -1c
.RI "void \fBSetFuelsAltered\fP (int YesNo)"
.br
.ti -1c
.RI "void \fBGetDefaultCrownChx\fP (double *Height, double *Base, double *Density)"
.br
.ti -1c
.RI "long \fBGetTheme_DistanceUnits\fP ()"
.br
.ti -1c
.RI "short \fBGetTheme_Units\fP (short DataTheme)"
.br
.ti -1c
.RI "short \fBGetTheme_NumCategories\fP (short DataTheme)"
.br
.ti -1c
.RI "long \fBGetTheme_HiValue\fP (short DataTheme)"
.br
.ti -1c
.RI "long \fBGetTheme_LoValue\fP (short DataTheme)"
.br
.ti -1c
.RI "char * \fBGetTheme_FileName\fP (short DataTheme)"
.br
.ti -1c
.RI "bool \fBLinkDensityWithCrownCover\fP (long TrueFalse)"
.br
.ti -1c
.RI "int \fBCheckCellResUnits\fP ()"
.br
.ti -1c
.RI "double \fBGetCellResolutionX\fP ()"
.br
.ti -1c
.RI "double \fBGetCellResolutionY\fP ()"
.br
.ti -1c
.RI "double \fBMetricResolutionConvert\fP ()"
.br
.ti -1c
.RI "long \fBCanSetRasterResolution\fP (long YesNo)"
.br
.ti -1c
.RI "long \fBSetRasterExtentToViewport\fP (long YesNo)"
.br
.ti -1c
.RI "void \fBSetRastRes\fP (double XResol, double YResol)"
.br
.ti -1c
.RI "void \fBGetRastRes\fP (double *XResol, double *YResol)"
.br
.ti -1c
.RI "long \fBGridInterval\fP (long Interval)"
.br
.ti -1c
.RI "long \fBTopoShadeDirection\fP (long Direction)"
.br
.ti -1c
.RI "void \fBSetTopoShading\fP (bool YesNo)"
.br
.ti -1c
.RI "bool \fBTopoShading\fP ()"
.br
.ti -1c
.RI "long \fBGetInputMode\fP ()"
.br
.ti -1c
.RI "void \fBSetInputMode\fP (long ModeCode, bool Pending)"
.br
.ti -1c
.RI "bool \fBChangeInputMode\fP (long YesNo)"
.br
.ti -1c
.RI "void \fBSetZoomReplayDelay\fP (long MilliSeconds)"
.br
.ti -1c
.RI "long \fBGetZoomReplayDelay\fP ()"
.br
.ti -1c
.RI "void \fBSetRastFormat\fP (long Type)"
.br
.ti -1c
.RI "long \fBGetRastFormat\fP ()"
.br
.ti -1c
.RI "void \fBSetVectFormat\fP (long Type)"
.br
.ti -1c
.RI "long \fBGetVectFormat\fP ()"
.br
.ti -1c
.RI "void \fBSetRastMake\fP (bool YesNo)"
.br
.ti -1c
.RI "bool \fBGetRastMake\fP ()"
.br
.ti -1c
.RI "void \fBSetVectMake\fP (bool YesNo)"
.br
.ti -1c
.RI "bool \fBGetVectMake\fP ()"
.br
.ti -1c
.RI "long \fBExcludeBarriersFromVectorFiles\fP (long YesNo)"
.br
.ti -1c
.RI "void \fBSetVectVisOnly\fP (bool YesNo)"
.br
.ti -1c
.RI "bool \fBGetVectVisOnly\fP ()"
.br
.ti -1c
.RI "void \fBSetShapeMake\fP (bool YesNo)"
.br
.ti -1c
.RI "bool \fBGetShapeMake\fP ()"
.br
.ti -1c
.RI "long \fBAccessDisplayUnits\fP (long val)"
.br
.ti -1c
.RI "long \fBAccessOutputUnits\fP (long val)"
.br
.ti -1c
.RI "double \fBMinFireChx\fP (double)"
.br
.ti -1c
.RI "double \fBMaxFireChx\fP (double)"
.br
.ti -1c
.RI "long \fBNumFireInterval\fP (long Num)"
.br
.ti -1c
.RI "long \fBOutputFireParam\fP (long Param)"
.br
.ti -1c
.RI "void \fBSetCanopyChx\fP (double Height, double CrownBase, double BulkDensity, double Diameter, long FoliarMoisture, long Tolerance, long Species)"
.br
.ti -1c
.RI "double \fBGetDefaultCrownHeight\fP ()"
.br
.ti -1c
.RI "double \fBGetDefaultCrownBase\fP ()"
.br
.ti -1c
.RI "double \fBGetDefaultCrownBD\fP (short cover)"
.br
.ti -1c
.RI "double \fBGetAverageDBH\fP ()"
.br
.ti -1c
.RI "double \fBGetFoliarMC\fP ()"
.br
.ti -1c
.RI "long \fBGetTolerance\fP ()"
.br
.ti -1c
.RI "long \fBGetCanopySpecies\fP ()"
.br
.ti -1c
.RI "void \fBResetFuelConversions\fP ()"
.br
.ti -1c
.RI "void \fBResetCustomFuelModels\fP ()"
.br
.ti -1c
.RI "int \fBGetFuelConversion\fP (int fuel)"
.br
.ti -1c
.RI "int \fBSetFuelConversion\fP (int fueltype, int fuelmodel)"
.br
.ti -1c
.RI "double \fBGetFuelDepth\fP (int Number)"
.br
.ti -1c
.RI "long \fBAccessFuelModelUnits\fP (long Val)"
.br
.ti -1c
.RI "void \fBSetFullTint\fP (double tint)"
.br
.ti -1c
.RI "double \fBGetFullTint\fP ()"
.br
.ti -1c
.RI "void \fBSetTint\fP (double tint)"
.br
.ti -1c
.RI "double \fBGetTint\fP ()"
.br
.ti -1c
.RI "void \fBSetMaxWindowDim\fP (long Dim)"
.br
.ti -1c
.RI "long \fBGetMaxWindowDim\fP ()"
.br
.ti -1c
.RI "bool \fBViewPortStatus\fP (long TrueFalse)"
.br
.ti -1c
.RI "bool \fBViewPortChanged\fP (long TrueFalse)"
.br
.ti -1c
.RI "void \fBSetLandscapeViewPort\fP (double north, double south, double east, double west)"
.br
.ti -1c
.RI "void \fBGetLandscapeViewPort\fP (double *north, double *south, double *east, double *west)"
.br
.ti -1c
.RI "double \fBGetViewNorth\fP ()"
.br
.ti -1c
.RI "double \fBGetViewSouth\fP ()"
.br
.ti -1c
.RI "double \fBGetViewEast\fP ()"
.br
.ti -1c
.RI "double \fBGetViewWest\fP ()"
.br
.ti -1c
.RI "long \fBGetNumViewEast\fP ()"
.br
.ti -1c
.RI "long \fBGetNumViewNorth\fP ()"
.br
.ti -1c
.RI "char * \fBGetCurrentPath\fP ()"
.br
.ti -1c
.RI "bool \fBReadIgnitions\fP (char *igfi)"
.br
.ti -1c
.RI "double \fBarp\fP ()"
.br
.ti -1c
.RI "void \fBBoundingBox\fP ()"
.br
.ti -1c
.RI "void \fBReversePoints\fP (int TYPE)"
.br
.ti -1c
.RI "bool \fBCanUseCurrentPath\fP (long YesNo)"
.br
.ti -1c
.RI "long \fBAdjustIgnitionSpreadRates\fP (long YesNoValue)"
.br
.ti -1c
.RI "bool \fBPreserveInactiveEnclaves\fP (long YesNo)"
.br
.ti -1c
.RI "void \fBSetRasterFileName\fP (const char *FileName)"
.br
.ti -1c
.RI "char * \fBGetRasterFileName\fP (long Type)"
.br
.ti -1c
.RI "void \fBSetVectorFileName\fP (const char *FileName)"
.br
.ti -1c
.RI "char * \fBGetVectorFileName\fP ()"
.br
.ti -1c
.RI "void \fBSetVisPerimPoint\fP (long xpt, long ypt, long firenum)"
.br
.ti -1c
.RI "void \fBResetVisPerimFile\fP ()"
.br
.ti -1c
.RI "void \fBCopyOutVisPerimFile\fP (char *NewVisName)"
.br
.ti -1c
.RI "void \fBCopyInVisPerimFile\fP (char *NewVisName)"
.br
.ti -1c
.RI "long \fBGetVisPerimFile\fP (long *xpt, long *ypt)"
.br
.ti -1c
.RI "void \fBSetVisPerimFile\fP (long xpt, long ypt)"
.br
.ti -1c
.RI "long \fBOpenVisPerimFile\fP (int rewindit)"
.br
.ti -1c
.RI "void \fBOpenVisPerimFileAtPosition\fP (long FilePosition)"
.br
.ti -1c
.RI "void \fBOpenCopyVisPerimFile\fP (char *FileName)"
.br
.ti -1c
.RI "long \fBCloseVisPerimFile\fP (int writeend, long firenum)"
.br
.ti -1c
.RI "void \fBSetFileOutputOptions\fP (long FileType, bool YesNo)"
.br
.ti -1c
.RI "bool \fBGetFileOutputOptions\fP (long FileType)"
.br
.ti -1c
.RI "void \fBSetViewRasterThemeInfo\fP (char *filename, long hi, long lo)"
.br
.ti -1c
.RI "char * \fBGetViewRasterThemeInfo\fP (long *hi, long *lo)"
.br
.ti -1c
.RI "bool \fBDraw3DVectorFile\fP (long YesNo)"
.br
.ti -1c
.RI "void \fBSetViewVectorThemeInfo\fP (char *filename, \fBCOLORREF\fP colr, long FileType)"
.br
.ti -1c
.RI "char * \fBGetViewVectorThemeInfo\fP (\fBCOLORREF\fP *colr)"
.br
.ti -1c
.RI "long \fBGetViewVectorFileType\fP ()"
.br
.ti -1c
.RI "void \fBSetShapeFileChx\fP (const char *ShapeFileName, long VisOnly, long Polygons, long BarriersSep)"
.br
.ti -1c
.RI "char * \fBGetShapeFileChx\fP (long *VisOnly, long *Polygons, long *BarriersSep)"
.br
.ti -1c
.RI "void \fBtrim\fP (char *totrim)"
.br
.ti -1c
.RI "\fBLandscapeTheme\fP * \fBGetLandscapeTheme\fP ()"
.br
.ti -1c
.RI "double \fBQueryRasterMap\fP (\fBThemes\fP *theme, double x, double y)"
.br
.ti -1c
.RI "\fBThemes\fP * \fBGetRasterTheme\fP (long Num)"
.br
.ti -1c
.RI "\fBThemes\fP * \fBAllocRasterTheme\fP ()"
.br
.ti -1c
.RI "void \fBFreeRasterTheme\fP (long Num)"
.br
.ti -1c
.RI "void \fBFreeAllRasterThemes\fP ()"
.br
.ti -1c
.RI "long \fBGetNumRasterThemes\fP ()"
.br
.ti -1c
.RI "long \fBSetNumRasterThemes\fP (long Num)"
.br
.ti -1c
.RI "void \fBSetNumVectorThemes\fP (long number)"
.br
.ti -1c
.RI "long \fBGetNumVectorThemes\fP ()"
.br
.ti -1c
.RI "long \fBAllocVectorTheme\fP ()"
.br
.ti -1c
.RI "\fBVectorTheme\fP * \fBGetVectorTheme\fP (long Num)"
.br
.ti -1c
.RI "void \fBSetVectorTheme\fP (long Num, \fBVectorTheme\fP *Theme)"
.br
.ti -1c
.RI "\fBVectorTheme\fP * \fBSetNewVectorTheme\fP (\fBVectorTheme\fP *Theme)"
.br
.ti -1c
.RI "bool \fBSetVectorOnOff\fP (long Num, long OnOff)"
.br
.ti -1c
.RI "void \fBFreeVectorTheme\fP (long Num)"
.br
.ti -1c
.RI "void \fBFreeAllVectorThemes\fP ()"
.br
.ti -1c
.RI "bool \fBCalcFirstLastStreamData\fP ()"
.br
.ti -1c
.RI "void \fBSetCorrectStreamNumbers\fP ()"
.br
.ti -1c
.RI "long \fBGetOpenWindStation\fP ()"
.br
.ti -1c
.RI "long \fBAllocWindData\fP (long StatNum, long NumObs)"
.br
.ti -1c
.RI "void \fBFreeWindData\fP (long StationNumber)"
.br
.ti -1c
.RI "long \fBSetWindData\fP (long StationNumber, long NumObs, long month, long day, long hour, double windspd, long winddir, long cloudy)"
.br
.ti -1c
.RI "long \fBGetWindMonth\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetWindDay\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetWindHour\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "double \fBGetWindSpeed\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetWindDir\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetWindCloud\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetMaxWindObs\fP (long StationNumber)"
.br
.ti -1c
.RI "void \fBSetWindUnits\fP (long StationNumber, long Units)"
.br
.ti -1c
.RI "void \fBSetWeatherUnits\fP (long StationNumber, long Units)"
.br
.ti -1c
.RI "long \fBGetWindUnits\fP (long StationNumber)"
.br
.ti -1c
.RI "long \fBGetWeatherUnits\fP (long StationNumber)"
.br
.ti -1c
.RI "long \fBGetOpenWeatherStation\fP ()"
.br
.ti -1c
.RI "long \fBAllocWeatherData\fP (long StatNum, long NumObs)"
.br
.ti -1c
.RI "void \fBFreeWeatherData\fP (long StationNumber)"
.br
.ti -1c
.RI "long \fBSetWeatherData\fP (long StationNumber, long NumObs, long month, long day, double rain, long time1, long time2, double temp1, double temp2, long humid1, long humid2, double elevation, long tr1, long tr2)"
.br
.ti -1c
.RI "long \fBGetWeatherMonth\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetWeatherDay\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "double \fBGetWeatherRain\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetWeatherTime1\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetWeatherTime2\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "double \fBGetWeatherTemp1\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "double \fBGetWeatherTemp2\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetWeatherHumid1\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "long \fBGetWeatherHumid2\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "double \fBGetWeatherElev\fP (long StationNumber, long NumObs)"
.br
.ti -1c
.RI "void \fBGetWeatherRainTimes\fP (long StationNumber, long NumObs, long *tr1, long *tr2)"
.br
.ti -1c
.RI "long \fBGetMaxWeatherObs\fP (long StationNumber)"
.br
.ti -1c
.RI "void \fBAllocStationGrid\fP (long XDim, long YDim)"
.br
.ti -1c
.RI "long \fBFreeStationGrid\fP ()"
.br
.ti -1c
.RI "long \fBGetStationNumber\fP (double xpt, double ypt)"
.br
.ti -1c
.RI "long \fBSetStationNumber\fP (long XPos, long YPos, long StationNumber)"
.br
.ti -1c
.RI "void \fBSetGridEastDimension\fP (long XDim)"
.br
.ti -1c
.RI "void \fBSetGridNorthDimension\fP (long YDim)"
.br
.ti -1c
.RI "long \fBGetGridEastDimension\fP ()"
.br
.ti -1c
.RI "long \fBGetGridNorthDimension\fP ()"
.br
.ti -1c
.RI "long \fBGridInitialized\fP ()"
.br
.ti -1c
.RI "long \fBGetNumStations\fP ()"
.br
.ti -1c
.RI "void \fBSetGridNorthOffset\fP (double offset)"
.br
.ti -1c
.RI "void \fBSetGridEastOffset\fP (double offset)"
.br
.ti -1c
.RI "double \fBGetGridNorthOffset\fP ()"
.br
.ti -1c
.RI "double \fBGetGridEastOffset\fP ()"
.br
.ti -1c
.RI "bool \fBTestForLCPVersion1\fP ()"
.br
.ti -1c
.RI "bool \fBTestForLCPVersion2\fP ()"
.br
.ti -1c
.RI "bool \fBConvertLCPFileToVersion2\fP ()"
.br
.ti -1c
.RI "bool \fBConvertLCPFile2ToVersion4\fP ()"
.br
.ti -1c
.RI "\fBheaddata\fP \fBGetHeaderInformation\fP ()"
.br
.ti -1c
.RI "void \fBSetHeader\fP (\fBheaddata\fP *data)"
.br
.ti -1c
.RI "void \fBReadHeader2\fP ()"
.br
.ti -1c
.RI "void \fBReadHeader\fP ()"
.br
.ti -1c
.RI "long \fBHaveCrownFuels\fP ()"
.br
.ti -1c
.RI "long \fBHaveGroundFuels\fP ()"
.br
.ti -1c
.RI "size_t \fBGetHeadSize\fP ()"
.br
.ti -1c
.RI "\fBcelldata\fP \fBCellData\fP (double east, double north, \fBcelldata\fP &cell, \fBcrowndata\fP &cfuel, \fBgrounddata\fP &gfuel, long *posit)"
.br
.ti -1c
.RI "void \fBGetCellDataFromMemory\fP (long posit, \fBcelldata\fP &cell, \fBcrowndata\fP &cfuel, \fBgrounddata\fP &gfuel)"
.br
.ti -1c
.RI "bool \fBSetCellData\fP (double xpt, double ypt, \fBcelldata\fP *cell, \fBcrowndata\fP *crown, \fBgrounddata\fP *ground)"
.br
.ti -1c
.RI "bool \fBGetBinaryCellData\fP (unsigned long row, unsigned long col, unsigned long num, short *data)"
.br
.ti -1c
.RI "long \fBGetCellPosition\fP (double east, double north)"
.br
.ti -1c
.RI "void \fBSetFilePosition\fP (long position)"
.br
.ti -1c
.RI "bool \fBHaveCustomFuelModels\fP ()"
.br
.ti -1c
.RI "bool \fBHaveFuelConversions\fP ()"
.br
.ti -1c
.RI "bool \fBNeedCustFuelModels\fP ()"
.br
.ti -1c
.RI "bool \fBNeedConvFuelModels\fP ()"
.br
.ti -1c
.RI "void \fBSetCustFuelModelID\fP (bool True_False)"
.br
.ti -1c
.RI "void \fBSetConvFuelModelID\fP (bool True_False)"
.br
.ti -1c
.RI "long \fBDurationResetAtRestart\fP (long YesNo)"
.br
.ti -1c
.RI "long \fBIgnitionResetAtRestart\fP (long YesNo)"
.br
.ti -1c
.RI "long \fBRotateSensitiveIgnitions\fP (long YesNo)"
.br
.ti -1c
.RI "long \fBShowFiresAsGrown\fP (long YesNo)"
.br
.ti -1c
.RI "void \fBSetVisibleTheme\fP (long ThemeNumber)"
.br
.ti -1c
.RI "long \fBGetVisibleTheme\fP ()"
.br
.ti -1c
.RI "FILE * \fBGetLandFile\fP ()"
.br
.ti -1c
.RI "bool \fBOpenLandFile\fP ()"
.br
.ti -1c
.RI "bool \fBReOpenLandFile\fP ()"
.br
.ti -1c
.RI "bool \fBOpenEditLandFile\fP ()"
.br
.ti -1c
.RI "void \fBCloseLandFile\fP ()"
.br
.ti -1c
.RI "void \fBCloseEditLandFile\fP ()"
.br
.ti -1c
.RI "void \fBSetLandFileName\fP (const char *FileName)"
.br
.ti -1c
.RI "char * \fBGetLandFileName\fP ()"
.br
.ti -1c
.RI "bool \fBSaveLCPMemoryToFile\fP (char *NewName)"
.br
.ti -1c
.RI "bool \fBWriteAsciiLCPTheme\fP (long ThemeNum, long Type, char *Name)"
.br
.ti -1c
.RI "double \fBGetWestUtm\fP ()"
.br
.ti -1c
.RI "double \fBGetEastUtm\fP ()"
.br
.ti -1c
.RI "double \fBGetSouthUtm\fP ()"
.br
.ti -1c
.RI "double \fBGetNorthUtm\fP ()"
.br
.ti -1c
.RI "double \fBGetLoEast\fP ()"
.br
.ti -1c
.RI "double \fBGetHiEast\fP ()"
.br
.ti -1c
.RI "double \fBGetLoNorth\fP ()"
.br
.ti -1c
.RI "double \fBGetHiNorth\fP ()"
.br
.ti -1c
.RI "long \fBGetLoElev\fP ()"
.br
.ti -1c
.RI "long \fBGetHiElev\fP ()"
.br
.ti -1c
.RI "long \fBGetNumEast\fP ()"
.br
.ti -1c
.RI "long \fBGetNumNorth\fP ()"
.br
.ti -1c
.RI "double \fBConvertEastingOffsetToUtm\fP (double input)"
.br
.ti -1c
.RI "double \fBConvertNorthingOffsetToUtm\fP (double input)"
.br
.ti -1c
.RI "double \fBConvertUtmToEastingOffset\fP (double input)"
.br
.ti -1c
.RI "double \fBConvertUtmToNorthingOffset\fP (double input)"
.br
.ti -1c
.RI "char * \fBGetHeaderDescription\fP ()"
.br
.ti -1c
.RI "long \fBGetConditMonth\fP ()"
.br
.ti -1c
.RI "long \fBGetConditDay\fP ()"
.br
.ti -1c
.RI "void \fBSetConditMonth\fP (long input)"
.br
.ti -1c
.RI "void \fBSetConditDay\fP (long input)"
.br
.ti -1c
.RI "long \fBGetConditMinDeficit\fP ()"
.br
.ti -1c
.RI "long \fBGetLatitude\fP ()"
.br
.ti -1c
.RI "long \fBGetStartMonth\fP ()"
.br
.ti -1c
.RI "long \fBGetStartDay\fP ()"
.br
.ti -1c
.RI "long \fBGetStartHour\fP ()"
.br
.ti -1c
.RI "long \fBGetStartMin\fP ()"
.br
.ti -1c
.RI "long \fBGetStartDate\fP ()"
.br
.ti -1c
.RI "void \fBSetStartMonth\fP (long input)"
.br
.ti -1c
.RI "void \fBSetStartDay\fP (long input)"
.br
.ti -1c
.RI "void \fBSetStartHour\fP (long input)"
.br
.ti -1c
.RI "void \fBSetStartMin\fP (long input)"
.br
.ti -1c
.RI "void \fBSetStartDate\fP (long input)"
.br
.ti -1c
.RI "long \fBGetEndMonth\fP ()"
.br
.ti -1c
.RI "long \fBGetEndDay\fP ()"
.br
.ti -1c
.RI "long \fBGetEndHour\fP ()"
.br
.ti -1c
.RI "long \fBGetEndDate\fP ()"
.br
.ti -1c
.RI "long \fBGetEndMin\fP ()"
.br
.ti -1c
.RI "void \fBSetEndMonth\fP (long input)"
.br
.ti -1c
.RI "void \fBSetEndDay\fP (long input)"
.br
.ti -1c
.RI "void \fBSetEndHour\fP (long input)"
.br
.ti -1c
.RI "void \fBSetEndMin\fP (long input)"
.br
.ti -1c
.RI "void \fBSetEndDate\fP (long input)"
.br
.ti -1c
.RI "long \fBGetMaxMonth\fP ()"
.br
.ti -1c
.RI "long \fBGetMaxDay\fP ()"
.br
.ti -1c
.RI "long \fBGetMaxHour\fP ()"
.br
.ti -1c
.RI "long \fBGetMinMonth\fP ()"
.br
.ti -1c
.RI "long \fBGetMinDay\fP ()"
.br
.ti -1c
.RI "long \fBGetMinHour\fP ()"
.br
.ti -1c
.RI "long \fBGetJulianDays\fP (long Month)"
.br
.ti -1c
.RI "double \fBConvertActualTimeToSimtime\fP (long mo, long dy, long hr, long mn, bool FromCondit)"
.br
.RI "Converts a time expressed in 'component form' (ie: month, day, hour, minutes) to the same time expressed in minutes from the beginning of the simulation\&. 
.br
 "
.ti -1c
.RI "void \fBConvertSimtimeToActualTime\fP (double SimTime, long *mo, long *dy, long *hr, long *mn, bool FromCondit)"
.br
.ti -1c
.RI "void \fBSetSimulationDuration\fP (double minutes)"
.br
.ti -1c
.RI "double \fBGetSimulationDuration\fP ()"
.br
.ti -1c
.RI "bool \fBUseConditioningPeriod\fP (long YesNo)"
.br
.ti -1c
.RI "bool \fBEnvironmentChanged\fP (long Changed, long StationNumber, long FuelSize)"
.br
.ti -1c
.RI "long \fBGetMoistCalcInterval\fP (long FM_SIZECLASS, long CATEGORY)"
.br
.ti -1c
.RI "void \fBSetMoistCalcInterval\fP (long FM_SIZECLASS, long CATEGORY, long Val)"
.br
.ti -1c
.RI "bool \fBPreCalcMoistures\fP (long YesNo)"
.br
.ti -1c
.RI "char * \fBGetStoredColorFile\fP ()"
.br
.ti -1c
.RI "void \fBGetStoredColorFile\fP (char *Filename)"
.br
.ti -1c
.RI "bool \fBSetAtmosphereGrid\fP (long NumGrids)"
.br
.ti -1c
.RI "\fBAtmosphereGrid\fP * \fBGetAtmosphereGrid\fP ()"
.br
.ti -1c
.RI "long \fBAtmosphereGridExists\fP ()"
.br
.ti -1c
.RI "void \fBAddDownTime\fP (double time)"
.br
.ti -1c
.RI "double \fBGetDownTime\fP ()"
.br
.ti -1c
.RI "bool \fBAllocBurnPeriod\fP (long num)"
.br
.ti -1c
.RI "long \fBGetNumBurnPeriods\fP ()"
.br
.ti -1c
.RI "void \fBFreeBurnPeriod\fP ()"
.br
.ti -1c
.RI "void \fBSetBurnPeriod\fP (long num, long mo, long dy, long start, long end)"
.br
.ti -1c
.RI "bool \fBGetBurnPeriod\fP (long num, long *mo, long *dy, long *start, long *end)"
.br
.ti -1c
.RI "bool \fBInquireInBurnPeriod\fP (double SimTime)"
.br
.ti -1c
.RI "void \fBConvertAbsoluteToRelativeBurnPeriod\fP ()"
.br
.ti -1c
.RI "bool \fBCheckBurnPeriod\fP (long mo1, long dy1, long mo2, long dy2)"
.br
.ti -1c
.RI "bool \fBSetInitialFuelMoistures\fP (long model, long t1, long t10, long t100, long tlh, long tlw)"
.br
.ti -1c
.RI "bool \fBGetInitialFuelMoistures\fP (long model, long *t1, long *t10, long *t100, long *tlh, long *tlw)"
.br
.ti -1c
.RI "long \fBGetInitialFuelMoisture\fP (long Model, long FuelClass)"
.br
.ti -1c
.RI "bool \fBInitialFuelMoistureIsHere\fP (long Model)"
.br
.ti -1c
.RI "bool \fBAllocCoarseWoody\fP (long ModelNumber, long NumClasses)"
.br
.ti -1c
.RI "void \fBFreeCoarseWoody\fP (long ModelNumber)"
.br
.ti -1c
.RI "void \fBFreeAllCoarseWoody\fP ()"
.br
.ti -1c
.RI "bool \fBSetWoodyData\fP (long ModelNumber, long ClassNumber, \fBWoodyData\fP *wd, long Units)"
.br
.ti -1c
.RI "bool \fBSetWoodyDataDepth\fP (long ModelNumber, double depth, const char *Description)"
.br
.ti -1c
.RI "bool \fBSetNFFLWoody\fP ()"
.br
.ti -1c
.RI "void \fBGetWoodyData\fP (long WoodyModelNumber, long SurfModelNumber, long *NumClasses, \fBWoodyData\fP *woody, double *Depth, double *TotalLoad)"
.br
.ti -1c
.RI "long \fBGetWoodyDataUnits\fP (long ModelNumber, char *Description)"
.br
.ti -1c
.RI "double \fBGetWoodyFuelMoisture\fP (long ModelNumber, long SizeClass)"
.br
.ti -1c
.RI "void \fBGetCurrentFuelMoistures\fP (long fuelmod, long woodymod, double *MxIn, double *MxOut, long NumMx)"
.br
.ti -1c
.RI "double \fBWeightLossErrorTolerance\fP (double value)"
.br
.ti -1c
.RI "long \fBWoodyCombineOptions\fP (long Options)"
.br
.ti -1c
.RI "double \fBGet1000HrMoisture\fP (long ModelNumber, bool Average)"
.br
.ti -1c
.RI "long \fBGetMaxThreads\fP ()"
.br
.ti -1c
.RI "void \fBSetMaxThreads\fP (long numthreads)"
.br
.ti -1c
.RI "bool \fBCanModifyInputs\fP (long YesNo)"
.br
.ti -1c
.RI "bool \fBCanAssignProcessor\fP ()"
.br
.ti -1c
.RI "void \fBResetNewFuels\fP ()"
.br
.ti -1c
.RI "bool \fBSetNewFuel\fP (\fBNewFuel\fP *newfuel)"
.br
.ti -1c
.RI "bool \fBGetNewFuel\fP (long number, \fBNewFuel\fP *newfuel)"
.br
.ti -1c
.RI "void \fBInitializeNewFuel\fP ()"
.br
.ti -1c
.RI "bool \fBIsNewFuelReserved\fP (long number)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define A_DATA   2"

.PP
Definition at line \fB75\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define ADDGROUNDATTACK   15"

.PP
Definition at line \fB53\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define AERIALLOCATION   10"

.PP
Definition at line \fB48\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define B_DATA   6"

.PP
Definition at line \fB79\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define BARRIERLOCATION   2"

.PP
Definition at line \fB40\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define C_DATA   4"

.PP
Definition at line \fB77\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define CWD_COMBINE_ABSENT   3"

.PP
Definition at line \fB958\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define CWD_COMBINE_ALWAYS   2"

.PP
Definition at line \fB957\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define CWD_COMBINE_NEVER   1"

.PP
Definition at line \fB956\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define D_DATA   8"

.PP
Definition at line \fB81\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define DIRECTLOCATION   7"

.PP
Definition at line \fB45\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define E_DATA   0"

.PP
Definition at line \fB73\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define EDITLOCATION   6"

.PP
Definition at line \fB44\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define F_DATA   3"

.PP
Definition at line \fB76\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define FIREINFORMATION   16"

.PP
Definition at line \fB54\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define FM_INTERVAL_ASP   3"

.PP
Definition at line \fB87\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define FM_INTERVAL_COV   4"

.PP
Definition at line \fB88\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define FM_INTERVAL_ELEV   1"

.PP
Definition at line \fB85\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define FM_INTERVAL_SLOPE   2"

.PP
Definition at line \fB86\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define FM_INTERVAL_TIME   0"

.PP
Definition at line \fB84\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define FUELLOCATION   3"

.PP
Definition at line \fB41\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define H_DATA   5"

.PP
Definition at line \fB78\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define IGNITIONLOCATION   1"

.PP
Definition at line \fB39\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define INDIRECTLOCATION   8"

.PP
Definition at line \fB46\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define MAXNUM_COARSEWOODY_MODELS   256"

.PP
Definition at line \fB955\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define MEASURELANDSCAPE   20"

.PP
Definition at line \fB58\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define MOVEPERIMPOINTS   17"

.PP
Definition at line \fB55\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define NULLLOCATION   0"

.PP
Definition at line \fB38\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define P_DATA   7"

.PP
Definition at line \fB80\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define PANLANDSCAPE   18"

.PP
Definition at line \fB56\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define PARALLELLOCATION   9"

.PP
Definition at line \fB47\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RAST_ARRIVALTIME   20"

.PP
Definition at line \fB64\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RAST_CROWNFIRE   25"

.PP
Definition at line \fB69\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RAST_FIREDIRECTION   26"

.PP
Definition at line \fB70\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RAST_FIREINTENSITY   21"

.PP
Definition at line \fB65\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RAST_FLAMELENGTH   23"

.PP
Definition at line \fB67\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RAST_HEATPERAREA   24"

.PP
Definition at line \fB68\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RAST_REACTIONINTENSITY   27"

.PP
Definition at line \fB71\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RAST_SPREADRATE   22"

.PP
Definition at line \fB66\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RELOCATEAIRATTACK   14"

.PP
Definition at line \fB52\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RELOCATEDIRECT   11"

.PP
Definition at line \fB49\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RELOCATEINDIRECT   12"

.PP
Definition at line \fB50\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RELOCATEPARALLEL   13"

.PP
Definition at line \fB51\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define RGB(r, g, b)   ((unsigned long) (((char)(r) |((unsigned int)(g) << 8 | (((unsigned long)(char) (b)))<<16))))"

.PP
Definition at line \fB89\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define S_DATA   1"

.PP
Definition at line \fB74\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define STOPLOCATION   19"

.PP
Definition at line \fB57\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define W_DATA   9"

.PP
Definition at line \fB82\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define WEATHERLOCATION   4"

.PP
Definition at line \fB42\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define WW_UNITS_ENGLISH   0"

.PP
Definition at line \fB61\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define WW_UNITS_METRIC   1"

.PP
Definition at line \fB60\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define WW_UNITS_UNDEFINED   \-1"

.PP
Definition at line \fB62\fP of file \fBfsglbvar\&.h\fP\&.
.SS "#define ZOOMLOCATION   5"

.PP
Definition at line \fB43\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned long \fBCOLORREF\fP"

.PP
Definition at line \fB102\fP of file \fBfsglbvar\&.h\fP\&.
.SS "typedef  struct \fB__attribute__\fP \fBheaddata32bit\fP"

.SH "Function Documentation"
.PP 
.SS "long AccessDisplayUnits (long val)"

.PP
Definition at line \fB1765\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long AccessFuelModelUnits (long Val)"

.PP
Definition at line \fB984\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long AccessOutputUnits (long val)"

.PP
Definition at line \fB1774\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void AddDownTime (double time)"

.PP
Definition at line \fB6757\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long AdjustIgnitionSpreadRates (long YesNoValue)"

.PP
Definition at line \fB864\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool AllocBurnPeriod (long num)"

.PP
Definition at line \fB6192\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool AllocCoarseWoody (long ModelNumber, long NumClasses)"

.PP
Definition at line \fB6878\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "\fBThemes\fP * AllocRasterTheme ()"

.PP
Definition at line \fB3785\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void AllocStationGrid (long XDim, long YDim)"

.PP
Definition at line \fB3150\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long AllocVectorTheme ()"

.PP
Definition at line \fB2305\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long AllocWeatherData (long StatNum, long NumObs)"

.PP
Definition at line \fB2844\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long AllocWindData (long StatNum, long NumObs)"

.PP
Definition at line \fB2684\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double arp ()"

.PP
Definition at line \fB538\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long AtmosphereGridExists ()"

.PP
Definition at line \fB6166\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void BoundingBox ()"

.PP
Definition at line \fB629\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool CalcFirstLastStreamData ()"

.PP
Definition at line \fB2476\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool CanAssignProcessor ()"

.PP
Definition at line \fB7595\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool CanModifyInputs (long YesNo)"

.PP
Definition at line \fB7586\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long CanSetRasterResolution (long YesNo)"

.PP
Definition at line \fB1578\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool CanUseCurrentPath (long YesNo)"

.PP
Definition at line \fB848\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "\fBcelldata\fP CellData (double east, double north, \fBcelldata\fP & cell, \fBcrowndata\fP & cfuel, \fBgrounddata\fP & gfuel, long * posit)"

.PP
Definition at line \fB4624\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool ChangeInputMode (long YesNo)"

.PP
Definition at line \fB1277\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool CheckBurnPeriod (long mo1, long dy1, long mo2, long dy2)"

.PP
Definition at line \fB6558\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "int CheckCellResUnits ()"

.PP
Definition at line \fB1512\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void CheckMessageLoop ()"

.PP
Definition at line \fB658\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void CloseEditLandFile ()"

.PP
Definition at line \fB5351\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void CloseLandFile ()"

.PP
Definition at line \fB5329\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long CloseVisPerimFile (int writeend, long firenum)"

.PP
Definition at line \fB2180\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void ConvertAbsoluteToRelativeBurnPeriod ()"

.PP
Definition at line \fB6595\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double ConvertActualTimeToSimtime (long mo, long dy, long hr, long mn, bool FromCondit)"

.PP
Converts a time expressed in 'component form' (ie: month, day, hour, minutes) to the same time expressed in minutes from the beginning of the simulation\&. 
.br
 This algorithm assumes that the arguments have the following units:
.PP
.PD 0
.IP "\(bu" 1
mo 'month of year' number (1-12) 
.IP "\(bu" 1
dy 'day of month' number (1-31) 
.IP "\(bu" 1
hr 'hour of day times 100' number (0000 - 2400) 
.IP "\(bu" 1
min 'minute of hour' number (0-59)
.PP
This algorithm works by converting the simulation start time to 'minutes
since the start of the year' for a reference\&. Then the provided time is also converted to 'minutes since the start of the year\&.' The 'simulation
time' is then computed by a simple subtraction of the start time from the provided time\&. 
.br
.PP
Because there is no provision for specifying the year of any of the times, certain assumptions must be made\&. For instance, if the 'month' of the provided time is less than the month of the simulation start, the algorithm assumes that the provided time refers to a time in the next year\&. 
.PP
Definition at line \fB6393\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double ConvertEastingOffsetToUtm (double input)"

.PP
Definition at line \fB4851\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool ConvertLCPFile2ToVersion4 ()"

.PP
Definition at line \fB5477\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool ConvertLCPFileToVersion2 ()"

.PP
Definition at line \fB5387\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double ConvertNorthingOffsetToUtm (double input)"

.PP
Definition at line \fB4864\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void ConvertSimtimeToActualTime (double SimTime, long * mo, long * dy, long * hr, long * mn, bool FromCondit)"

.PP
Definition at line \fB6452\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double ConvertUtmToEastingOffset (double input)"

.PP
Definition at line \fB4877\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double ConvertUtmToNorthingOffset (double input)"

.PP
Definition at line \fB4890\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void CopyInVisPerimFile (char * NewVisName)"

.PP
Definition at line \fB1997\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void CopyOutVisPerimFile (char * NewVisName)"

.PP
Definition at line \fB1990\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool Draw3DVectorFile (long YesNo)"

.PP
Definition at line \fB2250\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long DurationResetAtRestart (long YesNo)"

.PP
Definition at line \fB5133\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool EnvironmentChanged (long Changed, long StationNumber, long FuelSize)"

.PP
Definition at line \fB5246\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long ExcludeBarriersFromVectorFiles (long YesNo)"

.PP
Definition at line \fB1807\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void FreeAllCoarseWoody ()"

.PP
Definition at line \fB6906\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void FreeAllRasterThemes ()"

.PP
Definition at line \fB3823\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void FreeAllVectorThemes ()"

.PP
Definition at line \fB2452\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void FreeBurnPeriod ()"

.PP
Definition at line \fB6250\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void FreeCoarseWoody (long ModelNumber)"

.PP
Definition at line \fB6895\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void FreeRasterTheme (long Num)"

.PP
Definition at line \fB3840\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long FreeStationGrid ()"

.PP
Definition at line \fB3172\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void FreeVectorTheme (long Num)"

.PP
Definition at line \fB2425\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void FreeWeatherData (long StationNumber)"

.PP
Definition at line \fB2873\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void FreeWindData (long StationNumber)"

.PP
Definition at line \fB2713\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double Get1000HrMoisture (long ModelNumber, bool Average)"

.PP
Definition at line \fB7287\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "\fBAtmosphereGrid\fP * GetAtmosphereGrid ()"

.PP
Definition at line \fB6161\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetAverageDBH ()"

.PP
Definition at line \fB934\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool GetBinaryCellData (unsigned long row, unsigned long col, unsigned long num, short * data)"

.SS "bool GetBurnPeriod (long num, long * mo, long * dy, long * start, long * end)"

.PP
Definition at line \fB6283\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetCanopySpecies ()"

.PP
Definition at line \fB952\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetCellDataFromMemory (long posit, \fBcelldata\fP & cell, \fBcrowndata\fP & cfuel, \fBgrounddata\fP & gfuel)"

.PP
Definition at line \fB4383\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetCellPosition (double east, double north)"

.PP
Definition at line \fB4757\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetCellResolutionX ()"

.PP
Definition at line \fB1485\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetCellResolutionY ()"

.PP
Definition at line \fB1494\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetConditDay ()"

.PP
Definition at line \fB4928\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetConditMinDeficit ()"

.PP
Definition at line \fB4934\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetConditMonth ()"

.PP
Definition at line \fB4922\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetCurrentFuelMoistures (long fuelmod, long woodymod, double * MxIn, double * MxOut, long NumMx)"

.PP
Definition at line \fB7434\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetCurrentPath ()"

.PP
Definition at line \fB837\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetDefaultCrownBase ()"

.PP
Definition at line \fB919\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetDefaultCrownBD (short cover)"

.PP
Definition at line \fB925\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetDefaultCrownChx (double * Height, double * Base, double * Density)"

.PP
Definition at line \fB905\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetDefaultCrownHeight ()"

.PP
Definition at line \fB913\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetDownTime ()"

.PP
Definition at line \fB6765\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetEastUtm ()"

.PP
Definition at line \fB4817\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetEndDate ()"

.PP
Definition at line \fB5191\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetEndDay ()"

.PP
Definition at line \fB5181\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetEndHour ()"

.PP
Definition at line \fB5186\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetEndMin ()"

.PP
Definition at line \fB5196\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetEndMonth ()"

.PP
Definition at line \fB5176\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool GetFileOutputOptions (long FileType)"

.PP
Definition at line \fB1715\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetFoliarMC ()"

.PP
Definition at line \fB940\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "int GetFuelConversion (int fuel)"

.PP
Definition at line \fB1231\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetFuelDepth (int Number)"

.PP
Definition at line \fB7695\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "int GetFuelsAltered ()"

.PP
Definition at line \fB1200\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetFullTint ()"

.PP
Definition at line \fB719\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetGridEastDimension ()"

.PP
Definition at line \fB3236\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetGridEastOffset ()"

.PP
Definition at line \fB3263\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetGridNorthDimension ()"

.PP
Definition at line \fB3242\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetGridNorthOffset ()"

.PP
Definition at line \fB3258\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetHeaderDescription ()"

.PP
Definition at line \fB4904\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "\fBheaddata\fP GetHeaderInformation ()"

.PP
Definition at line \fB4788\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "size_t GetHeadSize ()"

.PP
Definition at line \fB4232\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetHiEast ()"

.PP
Definition at line \fB4836\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetHiElev ()"

.PP
Definition at line \fB4916\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetHiNorth ()"

.PP
Definition at line \fB4846\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetInitialFuelMoisture (long Model, long FuelClass)"

.PP
Definition at line \fB6824\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool GetInitialFuelMoistures (long model, long * t1, long * t10, long * t100, long * tlh, long * tlw)"

.PP
Definition at line \fB6804\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetInputMode ()"

.PP
Definition at line \fB1005\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetJulianDays (long Month)"

.PP
Definition at line \fB6332\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "FILE * GetLandFile ()"

.PP
Definition at line \fB5257\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetLandFileName ()"

.PP
Definition at line \fB5631\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "\fBLandscapeTheme\fP * GetLandscapeTheme ()"

.PP
Definition at line \fB3274\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetLandscapeViewPort (double * north, double * south, double * east, double * west)"

.PP
Definition at line \fB796\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetLatitude ()"

.PP
Definition at line \fB4965\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetLoEast ()"

.PP
Definition at line \fB4832\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetLoElev ()"

.PP
Definition at line \fB4911\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetLoNorth ()"

.PP
Definition at line \fB4841\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMaxDay ()"

.PP
Definition at line \fB5011\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetMaxDims (double * maxx, double * maxy)"

.PP
Definition at line \fB1090\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMaxHour ()"

.PP
Definition at line \fB5027\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMaxMonth ()"

.PP
Definition at line \fB4997\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMaxThreads ()"

.PP
Definition at line \fB7573\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMaxWeatherObs (long StationNumber)"

.PP
Definition at line \fB3021\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMaxWindObs (long StationNumber)"

.PP
Definition at line \fB2807\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMaxWindowDim ()"

.PP
Definition at line \fB745\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMinDay ()"

.PP
Definition at line \fB5064\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMinHour ()"

.PP
Definition at line \fB5084\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMinMonth ()"

.PP
Definition at line \fB5048\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetMoistCalcInterval (long FM_SIZECLASS, long CATEGORY)"

.PP
Definition at line \fB3039\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool GetNewFuel (long number, \fBNewFuel\fP * newfuel)"

.PP
Definition at line \fB7665\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetNorthUtm ()"

.PP
Definition at line \fB4827\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetNumBurnPeriods ()"

.PP
Definition at line \fB6303\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetNumEast ()"

.PP
Definition at line \fB4800\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetNumNorth ()"

.PP
Definition at line \fB4806\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetNumRasterThemes ()"

.PP
Definition at line \fB3755\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetNumStations ()"

.PP
Definition at line \fB2835\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetNumVectorThemes ()"

.PP
Definition at line \fB2299\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetNumViewEast ()"

.PP
Definition at line \fB826\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetNumViewNorth ()"

.PP
Definition at line \fB831\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetOpenWeatherStation ()"

.PP
Definition at line \fB2821\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetOpenWindStation ()"

.PP
Definition at line \fB2670\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetRasterFileName (long Type)"

.PP
Definition at line \fB1658\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "\fBThemes\fP * GetRasterTheme (long Num)"

.PP
Definition at line \fB3769\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetRastFormat ()"

.PP
Definition at line \fB1560\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool GetRastMake ()"

.PP
Definition at line \fB1757\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetRastRes (double * XResol, double * YResol)"

.PP
Definition at line \fB1604\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetRatios (double * xratio, double * yratio)"

.PP
Definition at line \fB1104\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetShapeFileChx (long * VisOnly, long * Polygons, long * BarriersSep)"

.PP
Definition at line \fB1839\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool GetShapeMake ()"

.PP
Definition at line \fB1802\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetSimulationDuration ()"

.PP
Definition at line \fB5226\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetSouthUtm ()"

.PP
Definition at line \fB4822\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetStartDate ()"

.PP
Definition at line \fB4991\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetStartDay ()"

.PP
Definition at line \fB4975\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetStartHour ()"

.PP
Definition at line \fB4980\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetStartMin ()"

.PP
Definition at line \fB4986\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetStartMonth ()"

.PP
Definition at line \fB4970\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetStationNumber (double xpt, double ypt)"

.PP
Definition at line \fB3187\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetStoredColorFile ()"

.PP
Definition at line \fB5649\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetStoredColorFile (char * Filename)"

.PP
Definition at line \fB5654\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetTheme_DistanceUnits ()"

.PP
Definition at line \fB1302\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetTheme_FileName (short DataTheme)"

.PP
Definition at line \fB1433\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetTheme_HiValue (short DataTheme)"

.PP
Definition at line \fB1370\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetTheme_LoValue (short DataTheme)"

.PP
Definition at line \fB1401\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "short GetTheme_NumCategories (short DataTheme)"

.PP
Definition at line \fB1339\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "short GetTheme_Units (short DataTheme)"

.PP
Definition at line \fB1308\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetTint ()"

.PP
Definition at line \fB731\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetTolerance ()"

.PP
Definition at line \fB946\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetVectFormat ()"

.PP
Definition at line \fB1572\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool GetVectMake ()"

.PP
Definition at line \fB1791\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetVectorFileName ()"

.PP
Definition at line \fB1629\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "\fBVectorTheme\fP * GetVectorTheme (long Num)"

.PP
Definition at line \fB2362\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool GetVectVisOnly ()"

.PP
Definition at line \fB1822\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetViewEast ()"

.PP
Definition at line \fB816\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetViewNorth ()"

.PP
Definition at line \fB806\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetViewRasterThemeInfo (long * hi, long * lo)"

.PP
Definition at line \fB2242\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetViewSouth ()"

.PP
Definition at line \fB811\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetViewVectorFileType ()"

.PP
Definition at line \fB2275\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "char * GetViewVectorThemeInfo (\fBCOLORREF\fP * colr)"

.PP
Definition at line \fB2267\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetViewWest ()"

.PP
Definition at line \fB821\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetVisibleTheme ()"

.PP
Definition at line \fB4777\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetVisPerimFile (long * xpt, long * ypt)"

.PP
Definition at line \fB2061\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWeatherDay (long StationNumber, long NumObs)"

.PP
Definition at line \fB2938\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetWeatherElev (long StationNumber, long NumObs)"

.PP
Definition at line \fB3002\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWeatherHumid1 (long StationNumber, long NumObs)"

.PP
Definition at line \fB2986\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWeatherHumid2 (long StationNumber, long NumObs)"

.PP
Definition at line \fB2994\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWeatherMonth (long StationNumber, long NumObs)"

.PP
Definition at line \fB2931\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetWeatherRain (long StationNumber, long NumObs)"

.PP
Definition at line \fB2946\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetWeatherRainTimes (long StationNumber, long NumObs, long * tr1, long * tr2)"

.PP
Definition at line \fB3011\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetWeatherTemp1 (long StationNumber, long NumObs)"

.PP
Definition at line \fB2970\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetWeatherTemp2 (long StationNumber, long NumObs)"

.PP
Definition at line \fB2978\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWeatherTime1 (long StationNumber, long NumObs)"

.PP
Definition at line \fB2954\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWeatherTime2 (long StationNumber, long NumObs)"

.PP
Definition at line \fB2962\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWeatherUnits (long StationNumber)"

.PP
Definition at line \fB3123\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetWestUtm ()"

.PP
Definition at line \fB4812\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWindCloud (long StationNumber, long NumObs)"

.PP
Definition at line \fB2799\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWindDay (long StationNumber, long NumObs)"

.PP
Definition at line \fB2767\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWindDir (long StationNumber, long NumObs)"

.PP
Definition at line \fB2791\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWindHour (long StationNumber, long NumObs)"

.PP
Definition at line \fB2775\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWindMonth (long StationNumber, long NumObs)"

.PP
Definition at line \fB2759\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetWindSpeed (long StationNumber, long NumObs)"

.PP
Definition at line \fB2783\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWindUnits (long StationNumber)"

.PP
Definition at line \fB3118\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void GetWoodyData (long WoodyModelNumber, long SurfModelNumber, long * NumClasses, \fBWoodyData\fP * woody, double * Depth, double * TotalLoad)"

.PP
Definition at line \fB7333\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetWoodyDataUnits (long ModelNumber, char * Description)"

.PP
Definition at line \fB7324\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double GetWoodyFuelMoisture (long ModelNumber, long SizeClass)"

.PP
Definition at line \fB7312\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool GetXORArrows ()"

.PP
Definition at line \fB1084\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GetZoomReplayDelay ()"

.PP
Definition at line \fB1297\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GridInitialized ()"

.PP
Definition at line \fB3216\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long GridInterval (long Interval)"

.PP
Definition at line \fB672\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long HaveCrownFuels ()"

.PP
Definition at line \fB1474\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool HaveCustomFuelModels ()"

.PP
Definition at line \fB1542\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool HaveFuelConversions ()"

.PP
Definition at line \fB1548\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long HaveGroundFuels ()"

.PP
Definition at line \fB1479\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long IgnitionResetAtRestart (long YesNo)"

.PP
Definition at line \fB5107\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool InitialFuelMoistureIsHere (long Model)"

.PP
Definition at line \fB6848\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void InitializeNewFuel ()"

.PP
Definition at line \fB7707\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool InquireInBurnPeriod (double SimTime)"

.PP
Definition at line \fB6309\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool IsNewFuelReserved (long number)"

.PP
Definition at line \fB7683\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool LinkDensityWithCrownCover (long TrueFalse)"

.PP
Definition at line \fB1465\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double MaxFireChx (double Type)"

.PP
Definition at line \fB6090\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double MetricResolutionConvert ()"

.PP
Definition at line \fB1503\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double MinFireChx (double Type)"

.PP
Definition at line \fB6080\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool NeedConvFuelModels ()"

.PP
Definition at line \fB1536\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool NeedCustFuelModels ()"

.PP
Definition at line \fB1530\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long NumFireInterval (long Num)"

.PP
Definition at line \fB6100\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void OpenCopyVisPerimFile (char * FileName)"

.PP
Definition at line \fB2170\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool OpenEditLandFile ()"

.PP
Definition at line \fB5307\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool OpenLandFile ()"

.PP
Definition at line \fB5263\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long OpenVisPerimFile (int rewindit)"

.PP
Definition at line \fB2129\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void OpenVisPerimFileAtPosition (long FilePosition)"

.PP
Definition at line \fB2160\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long OutputFireParam (long Param)"

.PP
Definition at line \fB6110\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double pow2 (double base)"

.PP
Definition at line \fB708\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool PreCalcMoistures (long YesNo)"

.PP
Definition at line \fB3030\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool PreserveInactiveEnclaves (long YesNo)"

.PP
Definition at line \fB5142\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double QueryRasterMap (\fBThemes\fP * theme, double x, double y)"

.PP
Definition at line \fB3730\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void ReadHeader ()"

.PP
Definition at line \fB3953\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void ReadHeader2 ()"

.PP
Definition at line \fB3891\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool ReadIgnitions (char * igfi)"
Hopefully will read in an ignition file for us\&. 
.PP
Definition at line \fB313\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool ReOpenLandFile ()"

.PP
Definition at line \fB5285\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void ResetCustomFuelModels ()"

.PP
Definition at line \fB271\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void ResetFuelConversions ()"

.PP
Definition at line \fB256\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void ResetNewFuels ()"

.PP
Definition at line \fB7619\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void ResetVisPerimFile ()"

.PP
Definition at line \fB2029\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void ReversePoints (int TYPE)"

.PP
Definition at line \fB585\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long RotateSensitiveIgnitions (long YesNo)"

.PP
Definition at line \fB5115\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool SaveLCPMemoryToFile (char * NewName)"

.PP
Definition at line \fB4473\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool SetAtmosphereGrid (long NumGrids)"

.PP
Definition at line \fB6129\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetBurnPeriod (long num, long mo, long dy, long start, long end)"

.PP
Definition at line \fB6265\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetCanopyChx (double Height, double CrownBase, double BulkDensity, double Diameter, long FoliarMoisture, long Tolerance, long Species)"

.PP
Definition at line \fB892\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool SetCellData (double xpt, double ypt, \fBcelldata\fP * cell, \fBcrowndata\fP * crown, \fBgrounddata\fP * ground)"

.PP
Definition at line \fB4244\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetConditDay (long input)"

.PP
Definition at line \fB4959\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetConditMonth (long input)"

.PP
Definition at line \fB4953\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetConvFuelModelID (bool True_False)"

.PP
Definition at line \fB1524\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetCorrectStreamNumbers ()"

.PP
Definition at line \fB2610\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetCustFuelModelID (bool True_False)"

.PP
Definition at line \fB1518\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetEndDate (long input)"

.PP
Definition at line \fB5221\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetEndDay (long input)"

.PP
Definition at line \fB5206\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetEndHour (long input)"

.PP
Definition at line \fB5211\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetEndMin (long input)"

.PP
Definition at line \fB5216\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetEndMonth (long input)"

.PP
Definition at line \fB5201\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetFileOutputOptions (long FileType, bool YesNo)"

.PP
Definition at line \fB1683\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetFilePosition (long position)"

.PP
Definition at line \fB4238\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "int SetFuelConversion (int fueltype, int fuelmodel)"

.PP
Definition at line \fB1259\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetFuelsAltered (int YesNo)"

.PP
Definition at line \fB1205\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetFullTint (double tint)"

.PP
Definition at line \fB714\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetGridEastDimension (long XDim)"

.PP
Definition at line \fB3225\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetGridEastOffset (double offset)"

.PP
Definition at line \fB3253\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetGridNorthDimension (long YDim)"

.PP
Definition at line \fB3231\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetGridNorthOffset (double offset)"

.PP
Definition at line \fB3248\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetHeader (\fBheaddata\fP * data)"

.PP
Definition at line \fB4794\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool SetInitialFuelMoistures (long model, long t1, long t10, long t100, long tlh, long tlw)"

.PP
Definition at line \fB6777\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetInputMode (long ModeCode, bool Pending)"

.PP
Definition at line \fB1013\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetLandFileName (const char * FileName)"

.PP
Definition at line \fB5636\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetLandscapeViewPort (double north, double south, double east, double west)"

.PP
Definition at line \fB776\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetMaxDims (double maxx, double maxy)"

.PP
Definition at line \fB1097\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetMaxThreads (long numthreads)"

.PP
Definition at line \fB7579\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetMaxWindowDim (long Dim)"

.PP
Definition at line \fB738\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetMoistCalcInterval (long FM_SIZECLASS, long CATEGORY, long Val)"

.PP
Definition at line \fB3045\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool SetNewFuel (\fBNewFuel\fP * newfuel)"

.PP
Definition at line \fB7636\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "\fBVectorTheme\fP * SetNewVectorTheme (\fBVectorTheme\fP * Theme)"

.PP
Definition at line \fB2396\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool SetNFFLWoody ()"

.PP
Definition at line \fB6965\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long SetNumRasterThemes (long Num)"

.PP
Definition at line \fB3760\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetNumVectorThemes (long number)"

.PP
Definition at line \fB2293\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long SetRasterExtentToViewport (long YesNo)"

.PP
Definition at line \fB1587\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetRasterFileName (const char * FileName)"

.PP
Definition at line \fB1635\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetRastFormat (long Type)"

.PP
Definition at line \fB1554\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetRastMake (bool YesNo)"

.PP
Definition at line \fB1751\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetRastRes (double XResol, double YResol)"

.PP
Definition at line \fB1596\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetRatios (double xratio, double yratio)"

.PP
Definition at line \fB1111\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetShapeFileChx (const char * ShapeFileName, long VisOnly, long Polygons, long BarriersSep)"

.PP
Definition at line \fB1828\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetShapeMake (bool YesNo)"

.PP
Definition at line \fB1796\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetSimulationDuration (double minutes)"

.PP
Definition at line \fB5231\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetStartDate (long input)"

.PP
Definition at line \fB5171\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetStartDay (long input)"

.PP
Definition at line \fB5156\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetStartHour (long input)"

.PP
Definition at line \fB5161\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetStartMin (long input)"

.PP
Definition at line \fB5166\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetStartMonth (long input)"

.PP
Definition at line \fB5151\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long SetStationNumber (long XPos, long YPos, long StationNumber)"

.PP
Definition at line \fB3202\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetTint (double tint)"

.PP
Definition at line \fB724\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetTopoShading (bool YesNo)"

.PP
Definition at line \fB993\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetVectFormat (long Type)"

.PP
Definition at line \fB1566\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetVectMake (bool YesNo)"

.PP
Definition at line \fB1785\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetVectorFileName (const char * FileName)"

.PP
Definition at line \fB1612\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool SetVectorOnOff (long Num, long OnOff)"

.PP
Definition at line \fB2343\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetVectorTheme (long Num, \fBVectorTheme\fP * Theme)"

.PP
Definition at line \fB2379\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetVectVisOnly (bool YesNo)"

.PP
Definition at line \fB1816\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetViewRasterThemeInfo (char * filename, long hi, long lo)"

.PP
Definition at line \fB2235\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetViewVectorThemeInfo (char * filename, \fBCOLORREF\fP colr, long FileType)"

.PP
Definition at line \fB2259\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetVisibleTheme (long ThemeNumber)"

.PP
Definition at line \fB4772\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetVisPerimFile (long xpt, long ypt)"

.PP
Definition at line \fB2080\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetVisPerimPoint (long xpt, long ypt, long firenum)"

.PP
Definition at line \fB2099\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long SetWeatherData (long StationNumber, long NumObs, long month, long day, double rain, long time1, long time2, double temp1, double temp2, long humid1, long humid2, double elevation, long tr1, long tr2)"

.PP
Definition at line \fB2891\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetWeatherUnits (long StationNumber, long Units)"

.PP
Definition at line \fB3113\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long SetWindData (long StationNumber, long NumObs, long month, long day, long hour, double windspd, long winddir, long cloudy)"

.PP
Definition at line \fB2731\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetWindUnits (long StationNumber, long Units)"

.PP
Definition at line \fB3108\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool SetWoodyData (long ModelNumber, long ClassNumber, \fBWoodyData\fP * wd, long Units)"

.PP
Definition at line \fB6923\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool SetWoodyDataDepth (long ModelNumber, double depth, const char * Description)"

.PP
Definition at line \fB6952\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetXORArrows (bool TorF)"

.PP
Definition at line \fB1078\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void SetZoomReplayDelay (long MilliSeconds)"

.PP
Definition at line \fB1287\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long ShowFiresAsGrown (long YesNo)"

.PP
Definition at line \fB5124\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool TestForLCPVersion1 ()"

.PP
Definition at line \fB5361\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool TestForLCPVersion2 ()"

.PP
Definition at line \fB5374\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long TopoShadeDirection (long Direction)"

.PP
Definition at line \fB698\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool TopoShading ()"

.PP
Definition at line \fB999\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void trim (char * totrim)"

.PP
Definition at line \fB8633\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool UseConditioningPeriod (long YesNo)"

.PP
Definition at line \fB5237\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool ViewPortChanged (long TrueFalse)"

.PP
Definition at line \fB751\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool ViewPortStatus (long TrueFalse)"

.PP
Definition at line \fB759\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double WeightLossErrorTolerance (double value)"

.PP
Definition at line \fB7558\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "long WoodyCombineOptions (long Options)"

.PP
Definition at line \fB7549\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "bool WriteAsciiLCPTheme (long ThemeNum, long Type, char * Name)"

.PP
Definition at line \fB4494\fP of file \fBfsglbvar\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
