.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxsync.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxsync.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFarsiteEvent\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEVENT_BURN\fP   1"
.br
.ti -1c
.RI "#define \fBEVENT_MOIST\fP   2"
.br
.ti -1c
.RI "#define \fBEVENT_BURNUP\fP   3"
.br
.ti -1c
.RI "#define \fBEVENT_INTEG\fP   4"
.br
.ti -1c
.RI "#define \fBEVENT_BURN_THREAD\fP   5"
.br
.ti -1c
.RI "#define \fBEVENT_MOIST_THREAD\fP   6"
.br
.ti -1c
.RI "#define \fBEVENT_BURNUP_THREAD\fP   7"
.br
.ti -1c
.RI "#define \fBEVENT_INTEG_THREAD\fP   8"
.br
.ti -1c
.RI "#define \fBEVENT_CROSS\fP   9"
.br
.ti -1c
.RI "#define \fBEVENT_CROSS_THREAD\fP   10"
.br
.ti -1c
.RI "#define \fBFARSITE_HANDLE\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef long \fBX_HANDLE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBAllocFarsiteEvents\fP (long EventNum, long numevents, char *basename, bool ManReset, bool InitState)"
.br
.ti -1c
.RI "bool \fBFreeFarsiteEvents\fP (long EventNum)"
.br
.ti -1c
.RI "bool \fBSetFarsiteEvent\fP (long EventNum, long ThreadNum)"
.br
.ti -1c
.RI "bool \fBResetFarsiteEvent\fP (long EventNum, long ThreadNum)"
.br
.ti -1c
.RI "bool \fBWaitForFarsiteEvents\fP (long EventNum, long NumEvents, bool All, unsigned long Wait)"
.br
.ti -1c
.RI "bool \fBWaitForOneFarsiteEvent\fP (long EventNum, long ThreadNum, unsigned long Wait)"
.br
.ti -1c
.RI "\fBX_HANDLE\fP \fBGetFarsiteEvent\fP (long EventNum, long ThreadNum)"
.br
.ti -1c
.RI "\fBX_HANDLE\fP \fBGetLandscapeSemaphore\fP ()"
.br
.ti -1c
.RI "bool \fBCreateLandscapeSemaphore\fP ()"
.br
.ti -1c
.RI "void \fBCloseLandscapeSemaphore\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EVENT_BURN   1"

.PP
Definition at line \fB35\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define EVENT_BURN_THREAD   5"

.PP
Definition at line \fB39\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define EVENT_BURNUP   3"

.PP
Definition at line \fB37\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define EVENT_BURNUP_THREAD   7"

.PP
Definition at line \fB41\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define EVENT_CROSS   9"

.PP
Definition at line \fB43\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define EVENT_CROSS_THREAD   10"

.PP
Definition at line \fB44\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define EVENT_INTEG   4"

.PP
Definition at line \fB38\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define EVENT_INTEG_THREAD   8"

.PP
Definition at line \fB42\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define EVENT_MOIST   2"

.PP
Definition at line \fB36\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define EVENT_MOIST_THREAD   6"

.PP
Definition at line \fB40\fP of file \fBfsxsync\&.h\fP\&.
.SS "#define FARSITE_HANDLE"

.PP
Definition at line \fB47\fP of file \fBfsxsync\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef long \fBX_HANDLE\fP"

.PP
Definition at line \fB48\fP of file \fBfsxsync\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "bool AllocFarsiteEvents (long EventNum, long numevents, char * basename, bool ManReset, bool InitState)"

.PP
Definition at line \fB46\fP of file \fBfsxsync\&.cpp\fP\&.
.SS "void CloseLandscapeSemaphore ()"

.PP
Definition at line \fB474\fP of file \fBfsxsync\&.cpp\fP\&.
.SS "bool CreateLandscapeSemaphore ()"

.PP
Definition at line \fB454\fP of file \fBfsxsync\&.cpp\fP\&.
.SS "bool FreeFarsiteEvents (long EventNum)"

.PP
Definition at line \fB88\fP of file \fBfsxsync\&.cpp\fP\&.
.SS "\fBX_HANDLE\fP GetFarsiteEvent (long EventNum, long ThreadNum)"

.PP
Definition at line \fB267\fP of file \fBfsxsync\&.cpp\fP\&.
.SS "\fBX_HANDLE\fP GetLandscapeSemaphore ()"

.PP
Definition at line \fB448\fP of file \fBfsxsync\&.cpp\fP\&.
.SS "bool ResetFarsiteEvent (long EventNum, long ThreadNum)"

.PP
Definition at line \fB158\fP of file \fBfsxsync\&.cpp\fP\&.
.SS "bool SetFarsiteEvent (long EventNum, long ThreadNum)"

.PP
Definition at line \fB123\fP of file \fBfsxsync\&.cpp\fP\&.
.SS "bool WaitForFarsiteEvents (long EventNum, long NumEvents, bool All, unsigned long Wait)"

.PP
Definition at line \fB193\fP of file \fBfsxsync\&.cpp\fP\&.
.SS "bool WaitForOneFarsiteEvent (long EventNum, long ThreadNum, unsigned long Wait)"

.PP
Definition at line \fB231\fP of file \fBfsxsync\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
