.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwinpt.cpp" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwinpt.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'fsxwinpt\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include 'portablestrings\&.h'\fP
.br
\fR#include 'fcopy\&.h'\fP
.br
\fR#include <sys/stat\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNODATA\fP   \-9999"
.br
.ti -1c
.RI "#define \fBIDYES\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IDYES   1"

.PP
Definition at line \fB45\fP of file \fBfsxwinpt\&.cpp\fP\&.
.SS "#define NODATA   \-9999"

.PP
Definition at line \fB44\fP of file \fBfsxwinpt\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
