.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwburn4.cpp" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwburn4.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'fsx4\&.hpp'\fP
.br
\fR#include 'fsxwattk\&.h'\fP
.br
\fR#include 'fsairatk\&.h'\fP
.br
\fR#include 'fsxpfront\&.h'\fP
.br
\fR#include 'fsglbvar\&.h'\fP
.br
\fR#include 'fsxsync\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <ncurses\&.h>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBURN_THREAD\fP   0"
.br
.ti -1c
.RI "#define \fBSPOT_THREAD\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBendCurses\fP ()"
.br
.ti -1c
.RI "void \fBstartCurses\fP ()"
.br
.ti -1c
.RI "void \fBdrawFrame\fP (int, int, int, int)"
.br
.ti -1c
.RI "int \fBmygetch\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBCTRL_B\fP = 2"
.br
.ti -1c
.RI "const char \fBCTRL_R\fP = 18"
.br
.ti -1c
.RI "const char \fBCTRL_U\fP = 21"
.br
.ti -1c
.RI "const char \fBCTRL_X\fP = 24"
.br
.ti -1c
.RI "const char \fBCTRL_N\fP = 14"
.br
.ti -1c
.RI "bool \fBcurses_started\fP = \fBfalse\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BURN_THREAD   0"

.PP
Definition at line \fB59\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "#define SPOT_THREAD   1"

.PP
Definition at line \fB60\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "void drawFrame (int startrow, int startcol, int endrow, int endcol)"

.PP
Definition at line \fB243\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "void endCurses ()"

.PP
Definition at line \fB204\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "int mygetch ()"

.PP
Definition at line \fB63\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "void startCurses ()"

.PP
Definition at line \fB215\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const char CTRL_B = 2"

.PP
Definition at line \fB46\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "const char CTRL_N = 14"

.PP
Definition at line \fB50\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "const char CTRL_R = 18"

.PP
Definition at line \fB47\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "const char CTRL_U = 21"

.PP
Definition at line \fB48\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "const char CTRL_X = 24"

.PP
Definition at line \fB49\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SS "bool curses_started = \fBfalse\fP"

.PP
Definition at line \fB52\fP of file \fBfsxwburn4\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
