.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwattk.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwattk.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdlib\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include 'fsxwbar\&.h'\fP
.br
\fR#include 'fsxlandt\&.h'\fP
.br
\fR#include <time\&.h>\fP
.br
\fR#include <sys/timeb\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCrew\fP"
.br
.ti -1c
.RI "struct \fBCompoundCrew\fP"
.br
.ti -1c
.RI "struct \fBAttackData\fP"
.br
.ti -1c
.RI "class \fBAttack\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOMPOUNDINC\fP   20"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBSetupIndirectAttack\fP (long CrewNum, double *startpt, long numpts)"
.br
.ti -1c
.RI "long \fBResetIndirectAttack\fP (\fBAttackData\fP *atk, double *coords, long numpts)"
.br
.ti -1c
.RI "long \fBSetupDirectAttack\fP (long CrewNum, long FireNum, double *coords)"
.br
.ti -1c
.RI "long \fBResetDirectAttack\fP (\fBAttackData\fP *atk, long FireNum, double *coords)"
.br
.ti -1c
.RI "long \fBGetNumAttacks\fP ()"
.br
.ti -1c
.RI "long \fBGetFireNumberForAttack\fP (long AttackCounter)"
.br
.ti -1c
.RI "\fBAttackData\fP * \fBGetAttackForFireNumber\fP (long NumFire, long start, long *LastAttackNumber)"
.br
.ti -1c
.RI "void \fBSetNewFireNumberForAttack\fP (long oldnumfire, long newnumfire)"
.br
.ti -1c
.RI "long \fBGetNumCrews\fP ()"
.br
.ti -1c
.RI "\fBAttackData\fP * \fBGetReassignedAttack\fP ()"
.br
.ti -1c
.RI "void \fBReassignAttack\fP (\fBAttackData\fP *atk)"
.br
.ti -1c
.RI "\fBAttackData\fP * \fBGetAttack\fP (long AttackCounter)"
.br
.ti -1c
.RI "\fBAttackData\fP * \fBGetAttackByOrder\fP (long OrdinalAttackNum, bool IndirectOnly)"
.br
.ti -1c
.RI "void \fBLoadAttacks\fP (\fBAttackData\fP attackdata)"
.br
.ti -1c
.RI "void \fBCancelAttack\fP (long AttackCounter)"
.br
.ti -1c
.RI "void \fBFreeAllAttacks\fP ()"
.br
.ti -1c
.RI "void \fBWriteAttackLog\fP (\fBAttackData\fP *atk, long Type, long Var1, long Var2)"
.br
.ti -1c
.RI "bool \fBLoadCrews\fP (char *FileName, bool AppendList)"
.br
.ti -1c
.RI "\fBCrew\fP * \fBGetCrew\fP (long CrewNumber)"
.br
.ti -1c
.RI "long \fBSetCrew\fP (long CrewNumber)"
.br
.ti -1c
.RI "long \fBSetNewCrew\fP ()"
.br
.ti -1c
.RI "void \fBFreeCrew\fP (long CrewNumber)"
.br
.ti -1c
.RI "void \fBFreeAllCrews\fP ()"
.br
.ti -1c
.RI "long \fBGetNumCompoundCrews\fP ()"
.br
.ti -1c
.RI "long \fBSetCompoundCrew\fP (long GroupNumber, char *CrewName, long ExistingCrewNumber)"
.br
.ti -1c
.RI "\fBCompoundCrew\fP * \fBGetCompoundCrew\fP (long CrewNumber)"
.br
.ti -1c
.RI "void \fBFreeCompoundCrew\fP (long CrewNumber)"
.br
.ti -1c
.RI "void \fBRemoveFromCompoundCrew\fP (long CompNumber, long CrewNumber)"
.br
.ti -1c
.RI "void \fBFreeAllCompoundCrews\fP ()"
.br
.ti -1c
.RI "bool \fBLoadCompoundCrews\fP (char *FileName)"
.br
.ti -1c
.RI "bool \fBAddToCompoundCrew\fP (long CrewNumber, long NewCrew, double Mult)"
.br
.ti -1c
.RI "void \fBCalculateCompoundRates\fP (long CrewNumber)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COMPOUNDINC   20"

.PP
Definition at line \fB63\fP of file \fBfsxwattk\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "bool AddToCompoundCrew (long CrewNumber, long NewCrew, double Mult)"

.PP
Definition at line \fB3786\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void CalculateCompoundRates (long CrewNumber)"

.PP
Definition at line \fB3821\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void CancelAttack (long AttackCounter)"

.PP
Definition at line \fB3342\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void FreeAllAttacks ()"

.PP
Definition at line \fB3392\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void FreeAllCompoundCrews ()"

.PP
Definition at line \fB3899\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void FreeAllCrews ()"

.PP
Definition at line \fB3687\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void FreeCompoundCrew (long CrewNumber)"

.PP
Definition at line \fB3855\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void FreeCrew (long CrewNumber)"

.PP
Definition at line \fB3697\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "\fBAttackData\fP * GetAttack (long AttackCounter)"

.PP
Definition at line \fB3319\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "\fBAttackData\fP * GetAttackByOrder (long OrdinalAttackNum, bool IndirectOnly)"

.PP
Definition at line \fB3291\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "\fBAttackData\fP * GetAttackForFireNumber (long NumFire, long start, long * LastAttackNumber)"

.PP
Definition at line \fB3230\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "\fBCompoundCrew\fP * GetCompoundCrew (long CrewNumber)"

.PP
Definition at line \fB3850\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "\fBCrew\fP * GetCrew (long CrewNumber)"

.PP
Definition at line \fB3659\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long GetFireNumberForAttack (long AttackCounter)"

.PP
Definition at line \fB3213\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long GetNumAttacks ()"

.PP
Definition at line \fB3207\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long GetNumCompoundCrews ()"

.PP
Definition at line \fB3719\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long GetNumCrews ()"

.PP
Definition at line \fB3282\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "\fBAttackData\fP * GetReassignedAttack ()"

.PP
Definition at line \fB3381\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void LoadAttacks (\fBAttackData\fP attackdata)"

.PP
Definition at line \fB2890\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "bool LoadCompoundCrews (char * FileName)"

.PP
Definition at line \fB3916\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "bool LoadCrews (char * FileName, bool AppendList)"

.PP
Definition at line \fB3488\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void ReassignAttack (\fBAttackData\fP * atk)"

.PP
Definition at line \fB3386\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void RemoveFromCompoundCrew (long CompNumber, long CrewNumber)"

.PP
Definition at line \fB3956\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long ResetDirectAttack (\fBAttackData\fP * atk, long FireNum, double * coords)"

.PP
Definition at line \fB3066\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long ResetIndirectAttack (\fBAttackData\fP * atk, double * coords, long numpts)"

.PP
Definition at line \fB2968\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long SetCompoundCrew (long GroupNumber, char * CrewName, long ExistingCrewNumber)"

.PP
Definition at line \fB3749\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long SetCrew (long CrewNumber)"

.PP
Definition at line \fB3677\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long SetNewCrew ()"

.PP
Definition at line \fB3668\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void SetNewFireNumberForAttack (long oldnumfire, long newnumfire)"

.PP
Definition at line \fB3253\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long SetupDirectAttack (long CrewNum, long FireNum, double * coords)"

.PP
Definition at line \fB3003\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "long SetupIndirectAttack (long CrewNum, double * startpt, long numpts)"

.PP
Definition at line \fB2909\fP of file \fBfsxwattk\&.cpp\fP\&.
.SS "void WriteAttackLog (\fBAttackData\fP * atk, long Type, long Var1, long Var2)"

.PP
Definition at line \fB3421\fP of file \fBfsxwattk\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
