.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwatm.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwatm.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdlib\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAtmosphere\fP"
.br
.ti -1c
.RI "class \fBAtmosphereGrid\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBATMTEMP\fP   0"
.br
.ti -1c
.RI "#define \fBATMHUMID\fP   1"
.br
.ti -1c
.RI "#define \fBATMRAIN\fP   2"
.br
.ti -1c
.RI "#define \fBATMWSPD\fP   3"
.br
.ti -1c
.RI "#define \fBATMWDIR\fP   4"
.br
.ti -1c
.RI "#define \fBATMCLOUD\fP   5"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ATMCLOUD   5"

.PP
Definition at line \fB34\fP of file \fBfsxwatm\&.h\fP\&.
.SS "#define ATMHUMID   1"

.PP
Definition at line \fB30\fP of file \fBfsxwatm\&.h\fP\&.
.SS "#define ATMRAIN   2"

.PP
Definition at line \fB31\fP of file \fBfsxwatm\&.h\fP\&.
.SS "#define ATMTEMP   0"

.PP
Definition at line \fB29\fP of file \fBfsxwatm\&.h\fP\&.
.SS "#define ATMWDIR   4"

.PP
Definition at line \fB33\fP of file \fBfsxwatm\&.h\fP\&.
.SS "#define ATMWSPD   3"

.PP
Definition at line \fB32\fP of file \fBfsxwatm\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
