.TH "FuelConversions" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuelConversions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFuelConversions\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBType\fP [257]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB433\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FuelConversions::FuelConversions ()"

.PP
Definition at line \fB1211\fP of file \fBfsglbvar\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int FuelConversions::Type[257]"

.PP
Definition at line \fB435\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
