.TH "FuelStruct" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuelStruct
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <burnupw\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBwdry\fP"
.br
.ti -1c
.RI "double \fBhtval\fP"
.br
.ti -1c
.RI "double \fBfmois\fP"
.br
.ti -1c
.RI "double \fBdendry\fP"
.br
.ti -1c
.RI "double \fBsigma\fP"
.br
.ti -1c
.RI "double \fBcheat\fP"
.br
.ti -1c
.RI "double \fBcondry\fP"
.br
.ti -1c
.RI "double \fBtpig\fP"
.br
.ti -1c
.RI "double \fBtchar\fP"
.br
.ti -1c
.RI "double \fBash\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB41\fP of file \fBburnupw\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double FuelStruct::ash"

.PP
Definition at line \fB52\fP of file \fBburnupw\&.h\fP\&.
.SS "double FuelStruct::cheat"

.PP
Definition at line \fB48\fP of file \fBburnupw\&.h\fP\&.
.SS "double FuelStruct::condry"

.PP
Definition at line \fB49\fP of file \fBburnupw\&.h\fP\&.
.SS "double FuelStruct::dendry"

.PP
Definition at line \fB46\fP of file \fBburnupw\&.h\fP\&.
.SS "double FuelStruct::fmois"

.PP
Definition at line \fB45\fP of file \fBburnupw\&.h\fP\&.
.SS "double FuelStruct::htval"

.PP
Definition at line \fB44\fP of file \fBburnupw\&.h\fP\&.
.SS "double FuelStruct::sigma"

.PP
Definition at line \fB47\fP of file \fBburnupw\&.h\fP\&.
.SS "double FuelStruct::tchar"

.PP
Definition at line \fB51\fP of file \fBburnupw\&.h\fP\&.
.SS "double FuelStruct::tpig"

.PP
Definition at line \fB50\fP of file \fBburnupw\&.h\fP\&.
.SS "double FuelStruct::wdry"

.PP
Definition at line \fB43\fP of file \fBburnupw\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
