.TH "FuelMoistureMap" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuelMoistureMap
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFuelMoistureMap\fP ()"
.br
.ti -1c
.RI "\fB~FuelMoistureMap\fP ()"
.br
.ti -1c
.RI "void \fBSearchCondenseFuels\fP (long FuelSize)"
.br
.ti -1c
.RI "bool \fBAllocFuels\fP (long FuelSize)"
.br
.ti -1c
.RI "void \fBFreeFuels\fP (long FuelSize)"
.br
.ti -1c
.RI "bool \fBReAllocFuels\fP (long FuelSize)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBNumFuels\fP [4]"
.br
.ti -1c
.RI "long \fBFuelKey\fP [4][256]"
.br
.ti -1c
.RI "long \fBFmTolerance\fP [4][3]"
.br
.ti -1c
.RI "double \fBCuumRain\fP"
.br
.ti -1c
.RI "\fBFMS_Elevations\fP ** \fBFMS\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB773\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FuelMoistureMap::FuelMoistureMap ()"

.PP
Definition at line \fB2322\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "FuelMoistureMap::~FuelMoistureMap ()"

.PP
Definition at line \fB2350\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool FuelMoistureMap::AllocFuels (long FuelSize)"

.PP
Definition at line \fB2584\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FuelMoistureMap::FreeFuels (long FuelSize)"

.PP
Definition at line \fB2660\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "bool FuelMoistureMap::ReAllocFuels (long FuelSize)"

.PP
Definition at line \fB2461\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FuelMoistureMap::SearchCondenseFuels (long FuelSize)"

.PP
Definition at line \fB2359\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double FuelMoistureMap::CuumRain"

.PP
Definition at line \fB778\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBFMS_Elevations\fP** FuelMoistureMap::FMS[4]"

.PP
Definition at line \fB779\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FuelMoistureMap::FmTolerance[4][3]"

.PP
Definition at line \fB777\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FuelMoistureMap::FuelKey[4][256]"

.PP
Definition at line \fB776\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FuelMoistureMap::NumFuels[4]"

.PP
Definition at line \fB775\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
