.TH "GridTheme" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GridTheme
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <themes\&.h>\fP
.PP
Inherited by \fBLandscapeTheme\fP, and \fBRasterTheme\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGridTheme\fP ()"
.br
.ti -1c
.RI "\fB~GridTheme\fP ()"
.br
.ti -1c
.RI "void \fBCreateRamp\fP ()"
.br
.ti -1c
.RI "void \fBDeleteRamp\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBName\fP [256]"
.br
.ti -1c
.RI "long \fBContinuous\fP"
.br
.ti -1c
.RI "long \fBRedVal\fP"
.br
.ti -1c
.RI "long \fBGreenVal\fP"
.br
.ti -1c
.RI "long \fBBlueVal\fP"
.br
.ti -1c
.RI "long \fBVarVal\fP"
.br
.ti -1c
.RI "long \fBNumColors\fP"
.br
.ti -1c
.RI "long \fBMaxBrite\fP"
.br
.ti -1c
.RI "long \fBColorChange\fP"
.br
.ti -1c
.RI "bool \fBWantNewRamp\fP"
.br
.ti -1c
.RI "bool \fBWantNewColor\fP"
.br
.ti -1c
.RI "bool \fBLcpAscii\fP"
.br
.ti -1c
.RI "bool \fBOnOff\fP"
.br
.ti -1c
.RI "bool \fBOnOff3d\fP"
.br
.ti -1c
.RI "bool \fBChanged3d\fP"
.br
.ti -1c
.RI "bool \fBConvertFuelColors\fP"
.br
.ti -1c
.RI "long \fBCats\fP [100]"
.br
.ti -1c
.RI "long \fBNumCats\fP"
.br
.ti -1c
.RI "long \fBCatsOK\fP"
.br
.ti -1c
.RI "long \fBPriority\fP"
.br
.ti -1c
.RI "long \fBLegendNum\fP"
.br
.ti -1c
.RI "double \fBMaxVal\fP"
.br
.ti -1c
.RI "double \fBMinVal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB71\fP of file \fBthemes\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GridTheme::GridTheme ()"

.PP
Definition at line \fB31\fP of file \fBgridthem\&.cpp\fP\&.
.SS "GridTheme::~GridTheme ()"

.PP
Definition at line \fB51\fP of file \fBgridthem\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void GridTheme::CreateRamp ()"

.PP
Definition at line \fB58\fP of file \fBgridthem\&.cpp\fP\&.
.SS "void GridTheme::DeleteRamp ()"

.PP
Definition at line \fB86\fP of file \fBgridthem\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long GridTheme::BlueVal"

.PP
Definition at line \fB76\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::Cats[100]"

.PP
Definition at line \fB79\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::CatsOK"

.PP
Definition at line \fB79\fP of file \fBthemes\&.h\fP\&.
.SS "bool GridTheme::Changed3d"

.PP
Definition at line \fB77\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::ColorChange"

.PP
Definition at line \fB76\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::Continuous"

.PP
Definition at line \fB75\fP of file \fBthemes\&.h\fP\&.
.SS "bool GridTheme::ConvertFuelColors"

.PP
Definition at line \fB78\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::GreenVal"

.PP
Definition at line \fB76\fP of file \fBthemes\&.h\fP\&.
.SS "bool GridTheme::LcpAscii"

.PP
Definition at line \fB77\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::LegendNum"

.PP
Definition at line \fB80\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::MaxBrite"

.PP
Definition at line \fB76\fP of file \fBthemes\&.h\fP\&.
.SS "double GridTheme::MaxVal"

.PP
Definition at line \fB81\fP of file \fBthemes\&.h\fP\&.
.SS "double GridTheme::MinVal"

.PP
Definition at line \fB81\fP of file \fBthemes\&.h\fP\&.
.SS "char GridTheme::Name[256]"

.PP
Definition at line \fB74\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::NumCats"

.PP
Definition at line \fB79\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::NumColors"

.PP
Definition at line \fB76\fP of file \fBthemes\&.h\fP\&.
.SS "bool GridTheme::OnOff"

.PP
Definition at line \fB77\fP of file \fBthemes\&.h\fP\&.
.SS "bool GridTheme::OnOff3d"

.PP
Definition at line \fB77\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::Priority"

.PP
Definition at line \fB79\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::RedVal"

.PP
Definition at line \fB76\fP of file \fBthemes\&.h\fP\&.
.SS "long GridTheme::VarVal"

.PP
Definition at line \fB76\fP of file \fBthemes\&.h\fP\&.
.SS "bool GridTheme::WantNewColor"

.PP
Definition at line \fB77\fP of file \fBthemes\&.h\fP\&.
.SS "bool GridTheme::WantNewRamp"

.PP
Definition at line \fB77\fP of file \fBthemes\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
