.TH "grounddata" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grounddata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxlandt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBd\fP"
.br
.ti -1c
.RI "short \fBw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB46\fP of file \fBfsxlandt\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "short grounddata::d"

.PP
Definition at line \fB49\fP of file \fBfsxlandt\&.h\fP\&.
.SS "short grounddata::w"

.PP
Definition at line \fB50\fP of file \fBfsxlandt\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
