.TH "headdata" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headdata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBCrownFuels\fP"
.br
.ti -1c
.RI "long \fBGroundFuels\fP"
.br
.ti -1c
.RI "long \fBlatitude\fP"
.br
.ti -1c
.RI "double \fBloeast\fP"
.br
.ti -1c
.RI "double \fBhieast\fP"
.br
.ti -1c
.RI "double \fBlonorth\fP"
.br
.ti -1c
.RI "double \fBhinorth\fP"
.br
.ti -1c
.RI "long \fBloelev\fP"
.br
.ti -1c
.RI "long \fBhielev\fP"
.br
.ti -1c
.RI "long \fBnumelev\fP"
.br
.ti -1c
.RI "long \fBelevs\fP [100]"
.br
.ti -1c
.RI "long \fBloslope\fP"
.br
.ti -1c
.RI "long \fBhislope\fP"
.br
.ti -1c
.RI "long \fBnumslope\fP"
.br
.ti -1c
.RI "long \fBslopes\fP [100]"
.br
.ti -1c
.RI "long \fBloaspect\fP"
.br
.ti -1c
.RI "long \fBhiaspect\fP"
.br
.ti -1c
.RI "long \fBnumaspect\fP"
.br
.ti -1c
.RI "long \fBaspects\fP [100]"
.br
.ti -1c
.RI "long \fBlofuel\fP"
.br
.ti -1c
.RI "long \fBhifuel\fP"
.br
.ti -1c
.RI "long \fBnumfuel\fP"
.br
.ti -1c
.RI "long \fBfuels\fP [100]"
.br
.ti -1c
.RI "long \fBlocover\fP"
.br
.ti -1c
.RI "long \fBhicover\fP"
.br
.ti -1c
.RI "long \fBnumcover\fP"
.br
.ti -1c
.RI "long \fBcovers\fP [100]"
.br
.ti -1c
.RI "long \fBloheight\fP"
.br
.ti -1c
.RI "long \fBhiheight\fP"
.br
.ti -1c
.RI "long \fBnumheight\fP"
.br
.ti -1c
.RI "long \fBheights\fP [100]"
.br
.ti -1c
.RI "long \fBlobase\fP"
.br
.ti -1c
.RI "long \fBhibase\fP"
.br
.ti -1c
.RI "long \fBnumbase\fP"
.br
.ti -1c
.RI "long \fBbases\fP [100]"
.br
.ti -1c
.RI "long \fBlodensity\fP"
.br
.ti -1c
.RI "long \fBhidensity\fP"
.br
.ti -1c
.RI "long \fBnumdensity\fP"
.br
.ti -1c
.RI "long \fBdensities\fP [100]"
.br
.ti -1c
.RI "long \fBloduff\fP"
.br
.ti -1c
.RI "long \fBhiduff\fP"
.br
.ti -1c
.RI "long \fBnumduff\fP"
.br
.ti -1c
.RI "long \fBduffs\fP [100]"
.br
.ti -1c
.RI "long \fBlowoody\fP"
.br
.ti -1c
.RI "long \fBhiwoody\fP"
.br
.ti -1c
.RI "long \fBnumwoody\fP"
.br
.ti -1c
.RI "long \fBwoodies\fP [100]"
.br
.ti -1c
.RI "long \fBnumeast\fP"
.br
.ti -1c
.RI "long \fBnumnorth\fP"
.br
.ti -1c
.RI "double \fBEastUtm\fP"
.br
.ti -1c
.RI "double \fBWestUtm\fP"
.br
.ti -1c
.RI "double \fBNorthUtm\fP"
.br
.ti -1c
.RI "double \fBSouthUtm\fP"
.br
.ti -1c
.RI "long \fBGridUnits\fP"
.br
.ti -1c
.RI "double \fBXResol\fP"
.br
.ti -1c
.RI "double \fBYResol\fP"
.br
.ti -1c
.RI "short \fBEUnits\fP"
.br
.ti -1c
.RI "short \fBSUnits\fP"
.br
.ti -1c
.RI "short \fBAUnits\fP"
.br
.ti -1c
.RI "short \fBFOptions\fP"
.br
.ti -1c
.RI "short \fBCUnits\fP"
.br
.ti -1c
.RI "short \fBHUnits\fP"
.br
.ti -1c
.RI "short \fBBUnits\fP"
.br
.ti -1c
.RI "short \fBPUnits\fP"
.br
.ti -1c
.RI "short \fBDUnits\fP"
.br
.ti -1c
.RI "short \fBWOptions\fP"
.br
.ti -1c
.RI "char \fBElevFile\fP [256]"
.br
.ti -1c
.RI "char \fBSlopeFile\fP [256]"
.br
.ti -1c
.RI "char \fBAspectFile\fP [256]"
.br
.ti -1c
.RI "char \fBFuelFile\fP [256]"
.br
.ti -1c
.RI "char \fBCoverFile\fP [256]"
.br
.ti -1c
.RI "char \fBHeightFile\fP [256]"
.br
.ti -1c
.RI "char \fBBaseFile\fP [256]"
.br
.ti -1c
.RI "char \fBDensityFile\fP [256]"
.br
.ti -1c
.RI "char \fBDuffFile\fP [256]"
.br
.ti -1c
.RI "char \fBWoodyFile\fP [256]"
.br
.ti -1c
.RI "char \fBDescription\fP [512]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB693\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char headdata::AspectFile[256]"

.PP
Definition at line \fB763\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::aspects[100]"

.PP
Definition at line \fB713\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::AUnits"

.PP
Definition at line \fB753\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::BaseFile[256]"

.PP
Definition at line \fB767\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::bases[100]"

.PP
Definition at line \fB729\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::BUnits"

.PP
Definition at line \fB757\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::CoverFile[256]"

.PP
Definition at line \fB765\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::covers[100]"

.PP
Definition at line \fB721\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::CrownFuels"

.PP
Definition at line \fB695\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::CUnits"

.PP
Definition at line \fB755\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::densities[100]"

.PP
Definition at line \fB733\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::DensityFile[256]"

.PP
Definition at line \fB768\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::Description[512]"

.PP
Definition at line \fB771\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::DuffFile[256]"

.PP
Definition at line \fB769\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::duffs[100]"

.PP
Definition at line \fB737\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::DUnits"

.PP
Definition at line \fB759\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::EastUtm"

.PP
Definition at line \fB744\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::ElevFile[256]"

.PP
Definition at line \fB761\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::elevs[100]"

.PP
Definition at line \fB705\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::EUnits"

.PP
Definition at line \fB751\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::FOptions"

.PP
Definition at line \fB754\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::FuelFile[256]"

.PP
Definition at line \fB764\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::fuels[100]"

.PP
Definition at line \fB717\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::GridUnits"

.PP
Definition at line \fB748\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::GroundFuels"

.PP
Definition at line \fB696\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::HeightFile[256]"

.PP
Definition at line \fB766\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::heights[100]"

.PP
Definition at line \fB725\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hiaspect"

.PP
Definition at line \fB711\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hibase"

.PP
Definition at line \fB727\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hicover"

.PP
Definition at line \fB719\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hidensity"

.PP
Definition at line \fB731\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hiduff"

.PP
Definition at line \fB735\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::hieast"

.PP
Definition at line \fB699\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hielev"

.PP
Definition at line \fB703\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hifuel"

.PP
Definition at line \fB715\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hiheight"

.PP
Definition at line \fB723\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::hinorth"

.PP
Definition at line \fB701\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hislope"

.PP
Definition at line \fB707\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::hiwoody"

.PP
Definition at line \fB739\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::HUnits"

.PP
Definition at line \fB756\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::latitude"

.PP
Definition at line \fB697\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::loaspect"

.PP
Definition at line \fB710\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::lobase"

.PP
Definition at line \fB726\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::locover"

.PP
Definition at line \fB718\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::lodensity"

.PP
Definition at line \fB730\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::loduff"

.PP
Definition at line \fB734\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::loeast"

.PP
Definition at line \fB698\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::loelev"

.PP
Definition at line \fB702\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::lofuel"

.PP
Definition at line \fB714\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::loheight"

.PP
Definition at line \fB722\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::lonorth"

.PP
Definition at line \fB700\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::loslope"

.PP
Definition at line \fB706\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::lowoody"

.PP
Definition at line \fB738\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::NorthUtm"

.PP
Definition at line \fB746\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numaspect"

.PP
Definition at line \fB712\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numbase"

.PP
Definition at line \fB728\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numcover"

.PP
Definition at line \fB720\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numdensity"

.PP
Definition at line \fB732\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numduff"

.PP
Definition at line \fB736\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numeast"

.PP
Definition at line \fB742\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numelev"

.PP
Definition at line \fB704\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numfuel"

.PP
Definition at line \fB716\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numheight"

.PP
Definition at line \fB724\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numnorth"

.PP
Definition at line \fB743\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numslope"

.PP
Definition at line \fB708\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::numwoody"

.PP
Definition at line \fB740\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::PUnits"

.PP
Definition at line \fB758\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::SlopeFile[256]"

.PP
Definition at line \fB762\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::slopes[100]"

.PP
Definition at line \fB709\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::SouthUtm"

.PP
Definition at line \fB747\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::SUnits"

.PP
Definition at line \fB752\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::WestUtm"

.PP
Definition at line \fB745\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata::woodies[100]"

.PP
Definition at line \fB741\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char headdata::WoodyFile[256]"

.PP
Definition at line \fB770\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata::WOptions"

.PP
Definition at line \fB760\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::XResol"

.PP
Definition at line \fB749\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata::YResol"

.PP
Definition at line \fB750\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
