.TH "ImportVectors" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImportVectors
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxwdvct\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImportVectors\fP (char *FileName)"
.br
.ti -1c
.RI "\fBImportVectors\fP ()"
.br
.ti -1c
.RI "bool \fBTestForShapeFile\fP ()"
.br
.ti -1c
.RI "bool \fBTestForGrassFile\fP ()"
.br
.ti -1c
.RI "bool \fBTestForArcFile\fP ()"
.br
.ti -1c
.RI "bool \fBTestForVisFile\fP ()"
.br
.ti -1c
.RI "bool \fBSetArcFileType\fP (char *Type)"
.br
.ti -1c
.RI "bool \fBDrawFile\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVectorTheme\fP \fBtheme\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBfsxwdvct\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ImportVectors::ImportVectors (char * FileName)"

.SS "ImportVectors::ImportVectors ()"

.SH "Member Function Documentation"
.PP 
.SS "bool ImportVectors::DrawFile ()"

.SS "bool ImportVectors::SetArcFileType (char * Type)"

.SS "bool ImportVectors::TestForArcFile ()"

.SS "bool ImportVectors::TestForGrassFile ()"

.SS "bool ImportVectors::TestForShapeFile ()"

.SS "bool ImportVectors::TestForVisFile ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBVectorTheme\fP ImportVectors::theme"

.PP
Definition at line \fB57\fP of file \fBfsxwdvct\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
