.TH "InitialFuelMoisture" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InitialFuelMoisture
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBFuelMoistureIsHere\fP"
.br
.ti -1c
.RI "long \fBTL1\fP"
.br
.ti -1c
.RI "long \fBTL10\fP"
.br
.ti -1c
.RI "long \fBTL100\fP"
.br
.ti -1c
.RI "long \fBTLLH\fP"
.br
.ti -1c
.RI "long \fBTLLW\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB932\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool InitialFuelMoisture::FuelMoistureIsHere"

.PP
Definition at line \fB934\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long InitialFuelMoisture::TL1"

.PP
Definition at line \fB935\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long InitialFuelMoisture::TL10"

.PP
Definition at line \fB936\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long InitialFuelMoisture::TL100"

.PP
Definition at line \fB937\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long InitialFuelMoisture::TLLH"

.PP
Definition at line \fB938\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long InitialFuelMoisture::TLLW"

.PP
Definition at line \fB939\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
