.TH "Intersections" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Intersections
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.PP
Inherits \fBXUtilities\fP, \fBCompareRect\fP, and \fBStandardizePolygon\fP\&.
.PP
Inherited by \fBBurn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntersections\fP ()"
.br
.ti -1c
.RI "\fB~Intersections\fP ()"
.br
.ti -1c
.RI "double \fBarp\fP (int PerimNum, long count)"
.br
.ti -1c
.RI "void \fBCrossFires\fP (int check, long *firenum)"
.br
.ti -1c
.RI "void \fBCrossesWithBarriers\fP (long FireNum)"
.br
.ti -1c
.RI "void \fBCleanPerimeter\fP (long CurrentFire)"
.br
.ti -1c
.RI "void \fBResetIntersectionArrays\fP ()"
.br
.ti -1c
.RI "void \fBCloseCrossThreads\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBXUtilities\fP
.in +1c
.ti -1c
.RI "\fBXUtilities\fP ()"
.br
.ti -1c
.RI "\fB~XUtilities\fP ()"
.br
.ti -1c
.RI "void \fBAllocSwap\fP (long NumPoint)"
.br
.ti -1c
.RI "void \fBFreeSwap\fP ()"
.br
.ti -1c
.RI "void \fBGetSwap\fP (long NumPoint, double *xpt, double *ypt, double *ros, double *fli, double *rct)"
.br
.ti -1c
.RI "void \fBSetSwap\fP (long NumPoint, double xpt, double ypt, double ros, double fli, double rct)"
.br
.ti -1c
.RI "void \fBSwapTranz\fP (long writefire, long nump)"
.br
.ti -1c
.RI "void \fBtranz\fP (long count, long nump)"
.br
.ti -1c
.RI "void \fBrediscretize\fP (long *count, bool Reorder)"
.br
.ti -1c
.RI "void \fBRePositionFire\fP (long *firenum)"
.br
.ti -1c
.RI "void \fBRestoreDeadPoints\fP (long firenum)"
.br
.in -1c

Public Member Functions inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "\fBAPolygon\fP ()"
.br
.ti -1c
.RI "\fB~APolygon\fP ()"
.br
.ti -1c
.RI "long \fBOverlap\fP (long count)"
.br
.ti -1c
.RI "double \fBdirection\fP (double xpt1, double ypt1)"
.br
.in -1c

Public Member Functions inherited from \fBCompareRect\fP
.in +1c
.ti -1c
.RI "\fBCompareRect\fP ()"
.br
.ti -1c
.RI "\fB~CompareRect\fP ()"
.br
.ti -1c
.RI "void \fBInitRect\fP (long FireNum)"
.br
.ti -1c
.RI "void \fBWriteHiLo\fP (long FireNum)"
.br
.ti -1c
.RI "void \fBExchangeRect\fP (long FireNum)"
.br
.ti -1c
.RI "bool \fBXOverlap\fP ()"
.br
.ti -1c
.RI "bool \fBYOverlap\fP ()"
.br
.ti -1c
.RI "bool \fBBoundCross\fP (long Fire1, long Fire2)"
.br
.ti -1c
.RI "void \fBDetermineHiLo\fP (double xpt, double ypt)"
.br
.ti -1c
.RI "bool \fBMergeInAndOutOK1\fP (long Fire1, long Fire2)"
.br
.in -1c

Public Member Functions inherited from \fBStandardizePolygon\fP
.in +1c
.ti -1c
.RI "\fBStandardizePolygon\fP ()"
.br
.ti -1c
.RI "\fB~StandardizePolygon\fP ()"
.br
.ti -1c
.RI "long \fBFindExternalPoint\fP (long CurrentFire, long type)"
.br
.ti -1c
.RI "void \fBReorderPerimeter\fP (long CurrentFire, long NewBeginning)"
.br
.ti -1c
.RI "void \fBFindOuterFirePerimeter\fP (long CurrentFire)"
.br
.ti -1c
.RI "bool \fBCross\fP (double xpt1, double ypt1, double xpt2, double ypt2, double xpt1n, double ypt1n, double xpt2n, double ypt2n, double *newx, double *newy, long *dup1, long *dup2)"
.br
.ti -1c
.RI "void \fBDensityControl\fP (long CurrentFire)"
.br
.ti -1c
.RI "void \fBRemoveDuplicatePoints\fP (long CurrentFire)"
.br
.ti -1c
.RI "void \fBRemoveIdenticalPoints\fP (long FireNum)"
.br
.ti -1c
.RI "void \fBBoundingBox\fP (long CurrentFire)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPostFrontal\fP \fBpost\fP"
.br
.in -1c

Public Attributes inherited from \fBXUtilities\fP
.in +1c
.ti -1c
.RI "long \fBExNumPts\fP"
.br
.ti -1c
.RI "long \fBOldNumPoints\fP"
.br
.ti -1c
.RI "double * \fBswapperim\fP"
.br
.in -1c

Public Attributes inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "double \fBstartx\fP"
.br
.ti -1c
.RI "double \fBstarty\fP"
.br
.in -1c

Public Attributes inherited from \fBCompareRect\fP
.in +1c
.ti -1c
.RI "double \fBXLO\fP"
.br
.ti -1c
.RI "double \fBXHI\fP"
.br
.ti -1c
.RI "double \fBYLO\fP"
.br
.ti -1c
.RI "double \fBYHI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB219\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Intersections::Intersections ()"

.PP
Definition at line \fB436\fP of file \fBfsxwutil\&.cpp\fP\&.
.SS "Intersections::~Intersections ()"

.PP
Definition at line \fB457\fP of file \fBfsxwutil\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double Intersections::arp (int PerimNum, long count)"

.PP
Definition at line \fB3819\fP of file \fBfsxwutil\&.cpp\fP\&.
.SS "void Intersections::CleanPerimeter (long CurrentFire)"

.PP
Definition at line \fB229\fP of file \fBnewclip\&.cpp\fP\&.
.SS "void Intersections::CloseCrossThreads ()"

.PP
Definition at line \fB1361\fP of file \fBfsxwutil\&.cpp\fP\&.
.SS "void Intersections::CrossesWithBarriers (long FireNum)"

.PP
Definition at line \fB1088\fP of file \fBfsxwutil\&.cpp\fP\&.
.SS "void Intersections::CrossFires (int check, long * firenum)"

.PP
Definition at line \fB1111\fP of file \fBfsxwutil\&.cpp\fP\&.
.SS "void Intersections::ResetIntersectionArrays ()"

.PP
Definition at line \fB467\fP of file \fBfsxwutil\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPostFrontal\fP Intersections::post"

.PP
Definition at line \fB284\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
