.TH "LandscapeStruct" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LandscapeStruct
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxlandt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBelev\fP"
.br
.ti -1c
.RI "short \fBslope\fP"
.br
.ti -1c
.RI "short \fBaspect\fP"
.br
.ti -1c
.RI "short \fBfuel\fP"
.br
.ti -1c
.RI "short \fBcover\fP"
.br
.ti -1c
.RI "double \fBaspectf\fP"
.br
.ti -1c
.RI "double \fBheight\fP"
.br
.ti -1c
.RI "double \fBbase\fP"
.br
.ti -1c
.RI "double \fBdensity\fP"
.br
.ti -1c
.RI "double \fBduff\fP"
.br
.ti -1c
.RI "long \fBwoody\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB71\fP of file \fBfsxlandt\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "short LandscapeStruct::aspect"

.PP
Definition at line \fB75\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double LandscapeStruct::aspectf"

.PP
Definition at line \fB78\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double LandscapeStruct::base"

.PP
Definition at line \fB80\fP of file \fBfsxlandt\&.h\fP\&.
.SS "short LandscapeStruct::cover"

.PP
Definition at line \fB77\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double LandscapeStruct::density"

.PP
Definition at line \fB81\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double LandscapeStruct::duff"

.PP
Definition at line \fB82\fP of file \fBfsxlandt\&.h\fP\&.
.SS "short LandscapeStruct::elev"

.PP
Definition at line \fB73\fP of file \fBfsxlandt\&.h\fP\&.
.SS "short LandscapeStruct::fuel"

.PP
Definition at line \fB76\fP of file \fBfsxlandt\&.h\fP\&.
.SS "double LandscapeStruct::height"

.PP
Definition at line \fB79\fP of file \fBfsxlandt\&.h\fP\&.
.SS "short LandscapeStruct::slope"

.PP
Definition at line \fB74\fP of file \fBfsxlandt\&.h\fP\&.
.SS "long LandscapeStruct::woody"

.PP
Definition at line \fB83\fP of file \fBfsxlandt\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
