.TH "LandscapeTheme" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LandscapeTheme
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <themes\&.h>\fP
.PP
Inherits \fBGridTheme\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLandscapeTheme\fP (bool Analyze)"
.br
.ti -1c
.RI "void \fBCopyStats\fP (long layer)"
.br
.ti -1c
.RI "void \fBReadStats\fP ()"
.br
.ti -1c
.RI "void \fBAnalyzeStats\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBGridTheme\fP
.in +1c
.ti -1c
.RI "\fBGridTheme\fP ()"
.br
.ti -1c
.RI "\fB~GridTheme\fP ()"
.br
.ti -1c
.RI "void \fBCreateRamp\fP ()"
.br
.ti -1c
.RI "void \fBDeleteRamp\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBNumAllCats\fP [10]"
.br
.ti -1c
.RI "long \fBAllCats\fP [10][100]"
.br
.ti -1c
.RI "double \fBmaxval\fP [10]"
.br
.ti -1c
.RI "double \fBminval\fP [10]"
.br
.in -1c

Public Attributes inherited from \fBGridTheme\fP
.in +1c
.ti -1c
.RI "char \fBName\fP [256]"
.br
.ti -1c
.RI "long \fBContinuous\fP"
.br
.ti -1c
.RI "long \fBRedVal\fP"
.br
.ti -1c
.RI "long \fBGreenVal\fP"
.br
.ti -1c
.RI "long \fBBlueVal\fP"
.br
.ti -1c
.RI "long \fBVarVal\fP"
.br
.ti -1c
.RI "long \fBNumColors\fP"
.br
.ti -1c
.RI "long \fBMaxBrite\fP"
.br
.ti -1c
.RI "long \fBColorChange\fP"
.br
.ti -1c
.RI "bool \fBWantNewRamp\fP"
.br
.ti -1c
.RI "bool \fBWantNewColor\fP"
.br
.ti -1c
.RI "bool \fBLcpAscii\fP"
.br
.ti -1c
.RI "bool \fBOnOff\fP"
.br
.ti -1c
.RI "bool \fBOnOff3d\fP"
.br
.ti -1c
.RI "bool \fBChanged3d\fP"
.br
.ti -1c
.RI "bool \fBConvertFuelColors\fP"
.br
.ti -1c
.RI "long \fBCats\fP [100]"
.br
.ti -1c
.RI "long \fBNumCats\fP"
.br
.ti -1c
.RI "long \fBCatsOK\fP"
.br
.ti -1c
.RI "long \fBPriority\fP"
.br
.ti -1c
.RI "long \fBLegendNum\fP"
.br
.ti -1c
.RI "double \fBMaxVal\fP"
.br
.ti -1c
.RI "double \fBMinVal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB94\fP of file \fBthemes\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LandscapeTheme::LandscapeTheme (bool Analyze)"

.PP
Definition at line \fB3286\fP of file \fBfsglbvar\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LandscapeTheme::AnalyzeStats ()"

.PP
Definition at line \fB3352\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void LandscapeTheme::CopyStats (long layer)"

.PP
Definition at line \fB3407\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "void LandscapeTheme::ReadStats ()"

.PP
Definition at line \fB3306\fP of file \fBfsglbvar\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long LandscapeTheme::AllCats[10][100]"

.PP
Definition at line \fB101\fP of file \fBthemes\&.h\fP\&.
.SS "double LandscapeTheme::maxval[10]"

.PP
Definition at line \fB102\fP of file \fBthemes\&.h\fP\&.
.SS "double LandscapeTheme::minval[10]"

.PP
Definition at line \fB102\fP of file \fBthemes\&.h\fP\&.
.SS "long LandscapeTheme::NumAllCats[10]"

.PP
Definition at line \fB100\fP of file \fBthemes\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
