.TH "LandscapeData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LandscapeData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxlandt\&.h>\fP
.PP
Inherited by \fBFELocalSite\fP, and \fBFireEnvironment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBElevConvert\fP (short)"
.br
.ti -1c
.RI "void \fBSlopeConvert\fP (short)"
.br
.ti -1c
.RI "void \fBAspectConvert\fP (short)"
.br
.ti -1c
.RI "void \fBFuelConvert\fP (short)"
.br
.ti -1c
.RI "void \fBCoverConvert\fP (short)"
.br
.ti -1c
.RI "void \fBHeightConvert\fP (short)"
.br
.ti -1c
.RI "void \fBBaseConvert\fP (short)"
.br
.ti -1c
.RI "void \fBDensityConvert\fP (short)"
.br
.ti -1c
.RI "void \fBDuffConvert\fP (short)"
.br
.ti -1c
.RI "void \fBWoodyConvert\fP (short)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLandscapeStruct\fP \fBld\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB87\fP of file \fBfsxlandt\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LandscapeData::AspectConvert (short as)"

.PP
Definition at line \fB146\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "void LandscapeData::BaseConvert (short base)"

.PP
Definition at line \fB228\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "void LandscapeData::CoverConvert (short cov)"

.PP
Definition at line \fB183\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "void LandscapeData::DensityConvert (short density)"

.PP
Definition at line \fB248\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "void LandscapeData::DuffConvert (short duff)"

.PP
Definition at line \fB270\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "void LandscapeData::ElevConvert (short el)"

.PP
Definition at line \fB99\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "void LandscapeData::FuelConvert (short fl)"

.PP
Definition at line \fB93\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "void LandscapeData::HeightConvert (short height)"

.PP
Definition at line \fB207\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "void LandscapeData::SlopeConvert (short sl)"

.PP
Definition at line \fB117\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SS "void LandscapeData::WoodyConvert (short woody)"

.PP
Definition at line \fB287\fP of file \fBfsxwenvt2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLandscapeStruct\fP LandscapeData::ld"

.PP
Definition at line \fB90\fP of file \fBfsxlandt\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
