.TH "LandDisplayData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LandDisplayData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBGridOnOff\fP"
.br
.ti -1c
.RI "int \fBShadeOnOff\fP"
.br
.ti -1c
.RI "int \fBLN\fP"
.br
.ti -1c
.RI "int \fBLS\fP"
.br
.ti -1c
.RI "int \fBLE\fP"
.br
.ti -1c
.RI "int \fBLW\fP"
.br
.ti -1c
.RI "int \fBLNE\fP"
.br
.ti -1c
.RI "int \fBLNW\fP"
.br
.ti -1c
.RI "int \fBLSE\fP"
.br
.ti -1c
.RI "int \fBLSW\fP"
.br
.ti -1c
.RI "int \fBwhite\fP"
.br
.ti -1c
.RI "int \fBlgray\fP"
.br
.ti -1c
.RI "int \fBdgray\fP"
.br
.ti -1c
.RI "int \fBblack\fP"
.br
.ti -1c
.RI "int \fBVE\fP"
.br
.ti -1c
.RI "int \fBVS\fP"
.br
.ti -1c
.RI "int \fBVA\fP"
.br
.ti -1c
.RI "int \fBVF\fP"
.br
.ti -1c
.RI "int \fBVC\fP"
.br
.ti -1c
.RI "int \fBVH\fP"
.br
.ti -1c
.RI "int \fBVB\fP"
.br
.ti -1c
.RI "int \fBVP\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBRes\fP"
.br
.ti -1c
.RI "char \fBRES\fP [10]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB159\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int LandDisplayData::black"

.PP
Definition at line \fB163\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::dgray"

.PP
Definition at line \fB163\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::GridOnOff"

.PP
Definition at line \fB161\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::LE"

.PP
Definition at line \fB162\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::lgray"

.PP
Definition at line \fB163\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::LN"

.PP
Definition at line \fB162\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::LNE"

.PP
Definition at line \fB162\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::LNW"

.PP
Definition at line \fB162\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::LS"

.PP
Definition at line \fB162\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::LSE"

.PP
Definition at line \fB162\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::LSW"

.PP
Definition at line \fB162\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::LW"

.PP
Definition at line \fB162\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP LandDisplayData::Res"

.PP
Definition at line \fB165\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char LandDisplayData::RES[10]"

.PP
Definition at line \fB166\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::ShadeOnOff"

.PP
Definition at line \fB161\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::VA"

.PP
Definition at line \fB164\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::VB"

.PP
Definition at line \fB164\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::VC"

.PP
Definition at line \fB164\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::VE"

.PP
Definition at line \fB164\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::VF"

.PP
Definition at line \fB164\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::VH"

.PP
Definition at line \fB164\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::VP"

.PP
Definition at line \fB164\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::VS"

.PP
Definition at line \fB164\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int LandDisplayData::white"

.PP
Definition at line \fB163\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
