.TH "MechCalls" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MechCalls
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.PP
Inherits \fBMechanix\fP\&.
.PP
Inherited by \fBBurnThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMechCalls\fP ()"
.br
.ti -1c
.RI "\fB~MechCalls\fP ()"
.br
.ti -1c
.RI "void \fBGetPoints\fP (long CurrentFire, long CurrentPoint)"
.br
.ti -1c
.RI "bool \fBNormalizeDirectionWithLocalSlope\fP ()"
.br
.ti -1c
.RI "void \fBVecSurf\fP ()"
.br
.ti -1c
.RI "void \fBVecCrown\fP ()"
.br
.ti -1c
.RI "void \fBSpreadCorrect\fP ()"
.br
.ti -1c
.RI "void \fBGetAccelConst\fP ()"
.br
.ti -1c
.RI "void \fBAccelSurf1\fP ()"
.br
.ti -1c
.RI "void \fBAccelSurf2\fP ()"
.br
.ti -1c
.RI "void \fBAccelCrown1\fP ()"
.br
.ti -1c
.RI "void \fBAccelCrown2\fP ()"
.br
.ti -1c
.RI "void \fBSlopeCorrect\fP (int spreadkind)"
.br
.ti -1c
.RI "void \fBLoadGlobalFEData\fP (\fBFELocalSite\fP *fe)"
.br
.ti -1c
.RI "void \fBLoadLocalFEData\fP (\fBFELocalSite\fP *fe)"
.br
.in -1c

Public Member Functions inherited from \fBMechanix\fP
.in +1c
.ti -1c
.RI "\fBMechanix\fP ()"
.br
.ti -1c
.RI "\fB~Mechanix\fP ()"
.br
.ti -1c
.RI "void \fBlimgrow\fP (void)"
.br
.ti -1c
.RI "void \fBgrow\fP (double ivecdir)"
.br
.ti -1c
.RI "void \fBdistchek\fP (long CurrentFire)"
.br
.ti -1c
.RI "void \fBellipse\fP (double iros, double wspeed)"
.br
.ti -1c
.RI "void \fBscorrect\fP (long slope, double aspectf)"
.br
.ti -1c
.RI "double \fBspreadrate\fP (long slope, double windspd, int fuel)"
.br
.ti -1c
.RI "void \fBGetEquationTerms\fP (double *\fBphiw\fP, double *\fBphis\fP, double *b, double *part1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBA\fP"
.br
.ti -1c
.RI "double \fBSubTimeStep\fP"
.br
.ti -1c
.RI "\fBEnvironmentData\fP \fBgmw\fP"
.br
.ti -1c
.RI "\fBEnvironmentData\fP \fBlmw\fP"
.br
.ti -1c
.RI "\fBLandscapeStruct\fP \fBld\fP"
.br
.in -1c

Public Attributes inherited from \fBMechanix\fP
.in +1c
.ti -1c
.RI "double \fBxpt\fP"
.br
.ti -1c
.RI "double \fBypt\fP"
.br
.ti -1c
.RI "double \fBmidx\fP"
.br
.ti -1c
.RI "double \fBmidy\fP"
.br
.ti -1c
.RI "double \fBxt\fP"
.br
.ti -1c
.RI "double \fByt\fP"
.br
.ti -1c
.RI "double \fBxptn\fP"
.br
.ti -1c
.RI "double \fByptn\fP"
.br
.ti -1c
.RI "double \fBxptl\fP"
.br
.ti -1c
.RI "double \fByptl\fP"
.br
.ti -1c
.RI "double \fBxdiff\fP"
.br
.ti -1c
.RI "double \fBydiff\fP"
.br
.ti -1c
.RI "double \fBvecspeed\fP"
.br
.ti -1c
.RI "double \fBivecspeed\fP"
.br
.ti -1c
.RI "double \fBvecdir\fP"
.br
.ti -1c
.RI "double \fBm_windspd\fP"
.br
.ti -1c
.RI "double \fBm_winddir\fP"
.br
.ti -1c
.RI "double \fBm_twindspd\fP"
.br
.ti -1c
.RI "double \fBActualSurfaceSpread\fP"
.br
.ti -1c
.RI "double \fBHorizSpread\fP"
.br
.ti -1c
.RI "double \fBavgros\fP"
.br
.ti -1c
.RI "double \fBcros\fP"
.br
.ti -1c
.RI "double \fBfros\fP"
.br
.ti -1c
.RI "double \fBvecros\fP"
.br
.ti -1c
.RI "double \fBRosT1\fP"
.br
.ti -1c
.RI "double \fBRosT\fP"
.br
.ti -1c
.RI "double \fBR10\fP"
.br
.ti -1c
.RI "double \fBfli\fP"
.br
.ti -1c
.RI "double \fBFliFinal\fP"
.br
.ti -1c
.RI "double \fBExpansionRate\fP"
.br
.ti -1c
.RI "double \fBtimerem\fP"
.br
.ti -1c
.RI "double \fBreact\fP"
.br
.ti -1c
.RI "double \fBsavx\fP"
.br
.ti -1c
.RI "double \fBcosslope\fP"
.br
.ti -1c
.RI "double \fBCurrentTime\fP"
.br
.ti -1c
.RI "double \fBFlameLength\fP"
.br
.ti -1c
.RI "double \fBCrownLoadingBurned\fP"
.br
.ti -1c
.RI "double \fBCrownFractionBurned\fP"
.br
.ti -1c
.RI "double \fBhead\fP"
.br
.ti -1c
.RI "double \fBback\fP"
.br
.ti -1c
.RI "double \fBflank\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMechanix\fP
.in +1c
.ti -1c
.RI "double \fBaccel\fP (double RosE, double \fBRosT\fP, double \fBA\fP, double *\fBavgros\fP, double *\fBcosslope\fP)"
.br
.ti -1c
.RI "void \fBTransformWindDir\fP (long slope, double aspectf)"
.br
.ti -1c
.RI "double \fBvectordir\fP (double aspectf)"
.br
.ti -1c
.RI "double \fBvectorspd\fP (double *VWindSpeed, double aspectf, long FireType)"
.br
.in -1c

Protected Attributes inherited from \fBMechanix\fP
.in +1c
.ti -1c
.RI "double \fBm_ones\fP"
.br
.ti -1c
.RI "double \fBm_tens\fP"
.br
.ti -1c
.RI "double \fBm_hundreds\fP"
.br
.ti -1c
.RI "double \fBm_livew\fP"
.br
.ti -1c
.RI "double \fBm_liveh\fP"
.br
.ti -1c
.RI "double \fBphiw\fP"
.br
.ti -1c
.RI "double \fBphis\fP"
.br
.ti -1c
.RI "double \fBphiew\fP"
.br
.ti -1c
.RI "double \fBLocalWindDir\fP"
.br
.ti -1c
.RI "double \fBFirePerimeterDist\fP"
.br
.ti -1c
.RI "double \fBslopespd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB919\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MechCalls::MechCalls ()"

.PP
Definition at line \fB67\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "MechCalls::~MechCalls ()"

.PP
Definition at line \fB71\fP of file \fBfsxwmech\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MechCalls::AccelCrown1 ()"

.PP
Definition at line \fB373\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::AccelCrown2 ()"

.PP
Definition at line \fB389\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::AccelSurf1 ()"

.PP
Definition at line \fB317\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::AccelSurf2 ()"

.PP
Definition at line \fB341\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::GetAccelConst ()"

.PP
Definition at line \fB306\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::GetPoints (long CurrentFire, long CurrentPoint)"

.PP
Definition at line \fB134\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::LoadGlobalFEData (\fBFELocalSite\fP * fe)"

.PP
Definition at line \fB76\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::LoadLocalFEData (\fBFELocalSite\fP * fe)"

.PP
Definition at line \fB112\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "bool MechCalls::NormalizeDirectionWithLocalSlope ()"

.PP
Definition at line \fB224\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::SlopeCorrect (int spreadkind)"

.PP
Definition at line \fB411\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::SpreadCorrect ()"

.PP
Definition at line \fB493\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::VecCrown ()"

.PP
Definition at line \fB466\fP of file \fBfsxwmech\&.cpp\fP\&.
.SS "void MechCalls::VecSurf ()"

.PP
Definition at line \fB441\fP of file \fBfsxwmech\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double MechCalls::A"

.PP
Definition at line \fB922\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBEnvironmentData\fP MechCalls::gmw"

.PP
Definition at line \fB923\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBLandscapeStruct\fP MechCalls::ld"

.PP
Definition at line \fB924\fP of file \fBfsx4\&.hpp\fP\&.
.SS "\fBEnvironmentData\fP MechCalls::lmw"

.PP
Definition at line \fB923\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double MechCalls::SubTimeStep"

.PP
Definition at line \fB922\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
