.TH "MergePoints" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MergePoints
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxpfront\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBStatus\fP"
.br
.ti -1c
.RI "long \fBFireID\fP"
.br
.ti -1c
.RI "long \fBVertexID\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB101\fP of file \fBfsxpfront\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long MergePoints::FireID"

.PP
Definition at line \fB104\fP of file \fBfsxpfront\&.h\fP\&.
.SS "short MergePoints::Status"

.PP
Definition at line \fB103\fP of file \fBfsxpfront\&.h\fP\&.
.SS "long MergePoints::VertexID"

.PP
Definition at line \fB105\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double MergePoints::x"

.PP
Definition at line \fB106\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double MergePoints::y"

.PP
Definition at line \fB106\fP of file \fBfsxpfront\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
