.TH "ModelData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTScrollBarData\fP \fBDTS\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBDVTS\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBDPRES\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBDSRES\fP"
.br
.ti -1c
.RI "int \fBChkV1\fP"
.br
.ti -1c
.RI "int \fBChkV2\fP"
.br
.ti -1c
.RI "int \fBMetric\fP"
.br
.ti -1c
.RI "int \fBEnglish\fP"
.br
.ti -1c
.RI "char \fBSDTS\fP [20]"
.br
.ti -1c
.RI "char \fBSDVTS\fP [20]"
.br
.ti -1c
.RI "char \fBSDVTS2\fP [20]"
.br
.ti -1c
.RI "char \fBSDPRES\fP [20]"
.br
.ti -1c
.RI "char \fBSDSRES\fP [20]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB208\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ModelData::ChkV1"

.PP
Definition at line \fB211\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int ModelData::ChkV2"

.PP
Definition at line \fB211\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP ModelData::DPRES"

.PP
Definition at line \fB210\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP ModelData::DSRES"

.PP
Definition at line \fB210\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP ModelData::DTS"

.PP
Definition at line \fB210\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP ModelData::DVTS"

.PP
Definition at line \fB210\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int ModelData::English"

.PP
Definition at line \fB211\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int ModelData::Metric"

.PP
Definition at line \fB211\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char ModelData::SDPRES[20]"

.PP
Definition at line \fB212\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char ModelData::SDSRES[20]"

.PP
Definition at line \fB212\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char ModelData::SDTS[20]"

.PP
Definition at line \fB212\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char ModelData::SDVTS[20]"

.PP
Definition at line \fB212\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char ModelData::SDVTS2[20]"

.PP
Definition at line \fB212\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
