.TH "NewFuel" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewFuel
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBnumber\fP"
.br
.ti -1c
.RI "char \fBcode\fP [8]"
.br
.ti -1c
.RI "double \fBh1\fP"
.br
.ti -1c
.RI "double \fBh10\fP"
.br
.ti -1c
.RI "double \fBh100\fP"
.br
.ti -1c
.RI "double \fBlh\fP"
.br
.ti -1c
.RI "double \fBlw\fP"
.br
.ti -1c
.RI "long \fBdynamic\fP"
.br
.ti -1c
.RI "long \fBsav1\fP"
.br
.ti -1c
.RI "long \fBsavlh\fP"
.br
.ti -1c
.RI "long \fBsavlw\fP"
.br
.ti -1c
.RI "double \fBdepth\fP"
.br
.ti -1c
.RI "double \fBxmext\fP"
.br
.ti -1c
.RI "double \fBheatd\fP"
.br
.ti -1c
.RI "double \fBheatl\fP"
.br
.ti -1c
.RI "char \fBdesc\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1015\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char NewFuel::code[8]"

.PP
Definition at line \fB1018\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double NewFuel::depth"

.PP
Definition at line \fB1028\fP of file \fBfsglbvar\&.h\fP\&.
.SS "char NewFuel::desc[256]"

.PP
Definition at line \fB1032\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long NewFuel::dynamic"

.PP
Definition at line \fB1024\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double NewFuel::h1"

.PP
Definition at line \fB1019\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double NewFuel::h10"

.PP
Definition at line \fB1020\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double NewFuel::h100"

.PP
Definition at line \fB1021\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double NewFuel::heatd"

.PP
Definition at line \fB1030\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double NewFuel::heatl"

.PP
Definition at line \fB1031\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double NewFuel::lh"

.PP
Definition at line \fB1022\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double NewFuel::lw"

.PP
Definition at line \fB1023\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long NewFuel::number"

.PP
Definition at line \fB1017\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long NewFuel::sav1"

.PP
Definition at line \fB1025\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long NewFuel::savlh"

.PP
Definition at line \fB1026\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long NewFuel::savlw"

.PP
Definition at line \fB1027\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double NewFuel::xmext"

.PP
Definition at line \fB1029\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
