.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/nonlin.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/nonlin.h
.SH SYNOPSIS
.br
.PP
\fR#include 'nrutil\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBpow2\fP (double input)"
.br
.ti -1c
.RI "void \fBmrqmin\fP (double x[], double y[], double sig[], long ndata, double a[], long ia[], long ma, double **covar, double **alpha, double *chisq, void(*funcs)(double, double[], double *, double[], long), double *alamda)"
.br
.ti -1c
.RI "void \fBcovsrt\fP (double **covar, long ma, long ia[], long mfit)"
.br
.ti -1c
.RI "void \fBgaussj\fP (double **a, long n, double **b, long m)"
.br
.ti -1c
.RI "void \fBmrqcof\fP (double x[], double y[], double sig[], long ndata, double a[], long ia[], long ma, double **alpha, double beta[], double *chisq, void(*funcs)(double, double[], double *, double[], long))"
.br
.ti -1c
.RI "void \fBlfit\fP (double x[], double y[], double sig[], long ndat, double a[], long ia[], long ma, double **covar, double *chisq, void(*funcs)(double, double[], long))"
.br
.ti -1c
.RI "void \fBsvdfit\fP (double x[], double y[], double sig[], long ndata, double a[], long ma, double **u, double **v, double w[], double *chisq, void(*funcs)(double, double[], long))"
.br
.ti -1c
.RI "void \fBsvdar\fP (double **v, long ma, double w[], double **cvm)"
.br
.ti -1c
.RI "void \fBsvbksb\fP (double **u, double w[], double **v, long m, long n, double b[], double x[])"
.br
.ti -1c
.RI "void \fBsvdcmp\fP (double **a, long m, long n, double w[], double **v)"
.br
.ti -1c
.RI "double \fBpythag\fP (double a, double b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void covsrt (double ** covar, long ma, long ia[], long mfit)"

.SS "void gaussj (double ** a, long n, double ** b, long m)"

.SS "void lfit (double x[], double y[], double sig[], long ndat, double a[], long ia[], long ma, double ** covar, double * chisq, void(*)(double, double[], long) funcs)"

.SS "void mrqcof (double x[], double y[], double sig[], long ndata, double a[], long ia[], long ma, double ** alpha, double beta[], double * chisq, void(*)(double, double[], double *, double[], long) funcs)"

.SS "void mrqmin (double x[], double y[], double sig[], long ndata, double a[], long ia[], long ma, double ** covar, double ** alpha, double * chisq, void(*)(double, double[], double *, double[], long) funcs, double * alamda)"

.SS "double pow2 (double input)"

.PP
Definition at line \fB708\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "double pythag (double a, double b)"

.SS "void svbksb (double ** u, double w[], double ** v, long m, long n, double b[], double x[])"

.SS "void svdar (double ** v, long ma, double w[], double ** cvm)"

.SS "void svdcmp (double ** a, long m, long n, double w[], double ** v)"

.SS "void svdfit (double x[], double y[], double sig[], long ndata, double a[], long ma, double ** u, double ** v, double w[], double * chisq, void(*)(double, double[], long) funcs)"

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
