.TH "oldcelldata" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
oldcelldata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBx\fP"
.br
.ti -1c
.RI "long \fBy\fP"
.br
.ti -1c
.RI "short \fBe\fP"
.br
.ti -1c
.RI "short \fBs\fP"
.br
.ti -1c
.RI "short \fBa\fP"
.br
.ti -1c
.RI "short \fBf\fP"
.br
.ti -1c
.RI "short \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB488\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "short oldcelldata::a"

.PP
Definition at line \fB494\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldcelldata::c"

.PP
Definition at line \fB496\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldcelldata::e"

.PP
Definition at line \fB492\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldcelldata::f"

.PP
Definition at line \fB495\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldcelldata::s"

.PP
Definition at line \fB493\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldcelldata::x"

.PP
Definition at line \fB490\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldcelldata::y"

.PP
Definition at line \fB491\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
