.TH "oldheaddata" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
oldheaddata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBCrownFuels\fP"
.br
.ti -1c
.RI "long \fBlatitude\fP"
.br
.ti -1c
.RI "long \fBloeast\fP"
.br
.ti -1c
.RI "long \fBhieast\fP"
.br
.ti -1c
.RI "long \fBlonorth\fP"
.br
.ti -1c
.RI "long \fBhinorth\fP"
.br
.ti -1c
.RI "long \fBloelev\fP"
.br
.ti -1c
.RI "long \fBhielev\fP"
.br
.ti -1c
.RI "long \fBnumeast\fP"
.br
.ti -1c
.RI "long \fBnumnorth\fP"
.br
.ti -1c
.RI "double \fBEastUtm\fP"
.br
.ti -1c
.RI "double \fBWestUtm\fP"
.br
.ti -1c
.RI "double \fBNorthUtm\fP"
.br
.ti -1c
.RI "double \fBSouthUtm\fP"
.br
.ti -1c
.RI "long \fBGridUnits\fP"
.br
.ti -1c
.RI "double \fBXResol\fP"
.br
.ti -1c
.RI "double \fBYResol\fP"
.br
.ti -1c
.RI "short \fBEUnits\fP"
.br
.ti -1c
.RI "short \fBSUnits\fP"
.br
.ti -1c
.RI "short \fBAUnits\fP"
.br
.ti -1c
.RI "short \fBFOptions\fP"
.br
.ti -1c
.RI "short \fBCUnits\fP"
.br
.ti -1c
.RI "short \fBHUnits\fP"
.br
.ti -1c
.RI "short \fBBUnits\fP"
.br
.ti -1c
.RI "short \fBPUnits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB526\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "short oldheaddata::AUnits"

.PP
Definition at line \fB547\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldheaddata::BUnits"

.PP
Definition at line \fB551\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::CrownFuels"

.PP
Definition at line \fB528\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldheaddata::CUnits"

.PP
Definition at line \fB549\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double oldheaddata::EastUtm"

.PP
Definition at line \fB538\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldheaddata::EUnits"

.PP
Definition at line \fB545\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldheaddata::FOptions"

.PP
Definition at line \fB548\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::GridUnits"

.PP
Definition at line \fB542\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::hieast"

.PP
Definition at line \fB531\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::hielev"

.PP
Definition at line \fB535\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::hinorth"

.PP
Definition at line \fB533\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldheaddata::HUnits"

.PP
Definition at line \fB550\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::latitude"

.PP
Definition at line \fB529\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::loeast"

.PP
Definition at line \fB530\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::loelev"

.PP
Definition at line \fB534\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::lonorth"

.PP
Definition at line \fB532\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double oldheaddata::NorthUtm"

.PP
Definition at line \fB540\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::numeast"

.PP
Definition at line \fB536\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long oldheaddata::numnorth"

.PP
Definition at line \fB537\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldheaddata::PUnits"

.PP
Definition at line \fB552\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double oldheaddata::SouthUtm"

.PP
Definition at line \fB541\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short oldheaddata::SUnits"

.PP
Definition at line \fB546\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double oldheaddata::WestUtm"

.PP
Definition at line \fB539\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double oldheaddata::XResol"

.PP
Definition at line \fB543\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double oldheaddata::YResol"

.PP
Definition at line \fB544\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
