.TH "OptionsData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionsData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTScrollBarData\fP \fBPIgnite\fP"
.br
.ti -1c
.RI "int \fBMeth1\fP"
.br
.ti -1c
.RI "int \fBMeth2\fP"
.br
.ti -1c
.RI "int \fBExpChk\fP"
.br
.ti -1c
.RI "int \fBCrown\fP"
.br
.ti -1c
.RI "int \fBLink\fP"
.br
.ti -1c
.RI "int \fBSSpot\fP"
.br
.ti -1c
.RI "int \fBTSpot\fP"
.br
.ti -1c
.RI "int \fBSGrowth\fP"
.br
.ti -1c
.RI "int \fBBack\fP"
.br
.ti -1c
.RI "char \fBpignite\fP [20]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB225\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int OptionsData::Back"

.PP
Definition at line \fB229\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OptionsData::Crown"

.PP
Definition at line \fB228\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OptionsData::ExpChk"

.PP
Definition at line \fB228\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OptionsData::Link"

.PP
Definition at line \fB228\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OptionsData::Meth1"

.PP
Definition at line \fB228\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OptionsData::Meth2"

.PP
Definition at line \fB228\fP of file \fBfarsite\&.hpp\fP\&.
.SS "\fBTScrollBarData\fP OptionsData::PIgnite"

.PP
Definition at line \fB227\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char OptionsData::pignite[20]"

.PP
Definition at line \fB230\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OptionsData::SGrowth"

.PP
Definition at line \fB228\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OptionsData::SSpot"

.PP
Definition at line \fB228\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OptionsData::TSpot"

.PP
Definition at line \fB228\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
