.TH "OutputData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutputData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBCheckR\fP"
.br
.ti -1c
.RI "int \fBCheckV\fP"
.br
.ti -1c
.RI "int \fBOCheckTOA\fP"
.br
.ti -1c
.RI "int \fBOCheckFLI\fP"
.br
.ti -1c
.RI "int \fBOCheckFL\fP"
.br
.ti -1c
.RI "int \fBOCheckROS\fP"
.br
.ti -1c
.RI "int \fBOCheckHA\fP"
.br
.ti -1c
.RI "int \fBOCheckRI\fP"
.br
.ti -1c
.RI "int \fBOCheckCF\fP"
.br
.ti -1c
.RI "int \fBOCheckFD\fP"
.br
.ti -1c
.RI "int \fBDispEng\fP"
.br
.ti -1c
.RI "int \fBDispMet\fP"
.br
.ti -1c
.RI "int \fBOtpEng\fP"
.br
.ti -1c
.RI "int \fBOtpMet\fP"
.br
.ti -1c
.RI "int \fBCheckArcVect\fP"
.br
.ti -1c
.RI "int \fBCheckOptVect\fP"
.br
.ti -1c
.RI "int \fBCheckGrassRast\fP"
.br
.ti -1c
.RI "int \fBCheckGridRast\fP"
.br
.ti -1c
.RI "int \fBCheckOptRast\fP"
.br
.ti -1c
.RI "int \fBCheckVisOnly\fP"
.br
.ti -1c
.RI "int \fBCheckShape\fP"
.br
.ti -1c
.RI "int \fBCheckShapeVisOnly\fP"
.br
.ti -1c
.RI "int \fBCheckShapeBarSep\fP"
.br
.ti -1c
.RI "int \fBCheckLine\fP"
.br
.ti -1c
.RI "int \fBCheckPoly\fP"
.br
.ti -1c
.RI "int \fBlogfile\fP"
.br
.ti -1c
.RI "char \fBRastStatX\fP [15]"
.br
.ti -1c
.RI "char \fBRastStatY\fP [15]"
.br
.ti -1c
.RI "double \fBxres\fP"
.br
.ti -1c
.RI "double \fByres\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB181\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int OutputData::CheckArcVect"

.PP
Definition at line \fB187\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckGrassRast"

.PP
Definition at line \fB187\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckGridRast"

.PP
Definition at line \fB187\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckLine"

.PP
Definition at line \fB190\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckOptRast"

.PP
Definition at line \fB188\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckOptVect"

.PP
Definition at line \fB187\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckPoly"

.PP
Definition at line \fB190\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckR"

.PP
Definition at line \fB183\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckShape"

.PP
Definition at line \fB190\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckShapeBarSep"

.PP
Definition at line \fB190\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckShapeVisOnly"

.PP
Definition at line \fB190\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckV"

.PP
Definition at line \fB183\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::CheckVisOnly"

.PP
Definition at line \fB189\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::DispEng"

.PP
Definition at line \fB186\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::DispMet"

.PP
Definition at line \fB186\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::logfile"

.PP
Definition at line \fB191\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OCheckCF"

.PP
Definition at line \fB185\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OCheckFD"

.PP
Definition at line \fB185\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OCheckFL"

.PP
Definition at line \fB184\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OCheckFLI"

.PP
Definition at line \fB184\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OCheckHA"

.PP
Definition at line \fB184\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OCheckRI"

.PP
Definition at line \fB184\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OCheckROS"

.PP
Definition at line \fB184\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OCheckTOA"

.PP
Definition at line \fB184\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OtpEng"

.PP
Definition at line \fB186\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int OutputData::OtpMet"

.PP
Definition at line \fB186\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char OutputData::RastStatX[15]"

.PP
Definition at line \fB192\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char OutputData::RastStatY[15]"

.PP
Definition at line \fB193\fP of file \fBfarsite\&.hpp\fP\&.
.SS "double OutputData::xres"

.PP
Definition at line \fB194\fP of file \fBfarsite\&.hpp\fP\&.
.SS "double OutputData::yres"

.PP
Definition at line \fB194\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
