.TH "OutputFile::RastData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutputFile::RastData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBTime\fP"
.br
.ti -1c
.RI "double \fBFli\fP"
.br
.ti -1c
.RI "double \fBRos\fP"
.br
.ti -1c
.RI "double \fBRcx\fP"
.br
.ti -1c
.RI "long \fBDir\fP"
.br
.ti -1c
.RI "bool \fBWrite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB336\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long OutputFile::RastData::Dir"

.PP
Definition at line \fB343\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double OutputFile::RastData::Fli"

.PP
Definition at line \fB340\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double OutputFile::RastData::Rcx"

.PP
Definition at line \fB342\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double OutputFile::RastData::Ros"

.PP
Definition at line \fB341\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double OutputFile::RastData::Time"

.PP
Definition at line \fB339\fP of file \fBfsx4\&.hpp\fP\&.
.SS "bool OutputFile::RastData::Write"

.PP
Definition at line \fB344\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double OutputFile::RastData::x"

.PP
Definition at line \fB338\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double OutputFile::RastData::y"

.PP
Definition at line \fB338\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
