.TH "PerimPoints" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerimPoints
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxpfront\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBStatus\fP"
.br
.ti -1c
.RI "double \fBx1\fP"
.br
.ti -1c
.RI "double \fBx2\fP"
.br
.ti -1c
.RI "double \fBy1\fP"
.br
.ti -1c
.RI "double \fBy2\fP"
.br
.ti -1c
.RI "double \fBSizeMult\fP"
.br
.ti -1c
.RI "double \fBArea\fP"
.br
.ti -1c
.RI "double \fBl1\fP"
.br
.ti -1c
.RI "double \fBl2\fP"
.br
.ti -1c
.RI "double \fBh\fP"
.br
.ti -1c
.RI "\fBBurnHistory\fP \fBhist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB135\fP of file \fBfsxpfront\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double PerimPoints::Area"

.PP
Definition at line \fB140\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PerimPoints::h"

.PP
Definition at line \fB141\fP of file \fBfsxpfront\&.h\fP\&.
.SS "\fBBurnHistory\fP PerimPoints::hist"

.PP
Definition at line \fB142\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PerimPoints::l1"

.PP
Definition at line \fB141\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PerimPoints::l2"

.PP
Definition at line \fB141\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PerimPoints::SizeMult"

.PP
Definition at line \fB139\fP of file \fBfsxpfront\&.h\fP\&.
.SS "short PerimPoints::Status"

.PP
Definition at line \fB137\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PerimPoints::x1"

.PP
Definition at line \fB138\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PerimPoints::x2"

.PP
Definition at line \fB138\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PerimPoints::y1"

.PP
Definition at line \fB138\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PerimPoints::y2"

.PP
Definition at line \fB138\fP of file \fBfsxpfront\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
