.TH "PFrontData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFrontData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxpfront\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPFrontData\fP ()"
.br
.ti -1c
.RI "\fB~PFrontData\fP ()"
.br
.ti -1c
.RI "void \fBSetData\fP (double Time, double Flame, double Smolder)"
.br
.ti -1c
.RI "double \fBGetPostFrontalProducts\fP (long Species, long Phase, long Num)"
.br
.ti -1c
.RI "double \fBGetTime\fP (long Num)"
.br
.ti -1c
.RI "void \fBResetData\fP ()"
.br
.ti -1c
.RI "double \fBGetMax\fP (long Species, long Phase)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBnumber\fP"
.br
.ti -1c
.RI "double \fBMaxTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB75\fP of file \fBfsxpfront\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PFrontData::PFrontData ()"

.PP
Definition at line \fB4807\fP of file \fBfsxpfront\&.cpp\fP\&.
.SS "PFrontData::~PFrontData ()"

.PP
Definition at line \fB4831\fP of file \fBfsxpfront\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double PFrontData::GetMax (long Species, long Phase)"

.PP
Definition at line \fB4838\fP of file \fBfsxpfront\&.cpp\fP\&.
.SS "double PFrontData::GetPostFrontalProducts (long Species, long Phase, long Num)"

.PP
Definition at line \fB4985\fP of file \fBfsxpfront\&.cpp\fP\&.
.SS "double PFrontData::GetTime (long Num)"

.PP
Definition at line \fB5003\fP of file \fBfsxpfront\&.cpp\fP\&.
.SS "void PFrontData::ResetData ()"

.PP
Definition at line \fB4901\fP of file \fBfsxpfront\&.cpp\fP\&.
.SS "void PFrontData::SetData (double Time, double Flame, double Smolder)"

.PP
Definition at line \fB4860\fP of file \fBfsxpfront\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double PFrontData::MaxTime"

.PP
Definition at line \fB88\fP of file \fBfsxpfront\&.h\fP\&.
.SS "long PFrontData::number"

.PP
Definition at line \fB87\fP of file \fBfsxpfront\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
