.TH "PFrontStruct" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFrontStruct
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxpfront\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBTime\fP"
.br
.ti -1c
.RI "double \fBFlaming\fP"
.br
.ti -1c
.RI "double \fBSmoldering\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB67\fP of file \fBfsxpfront\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double PFrontStruct::Flaming"

.PP
Definition at line \fB70\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PFrontStruct::Smoldering"

.PP
Definition at line \fB71\fP of file \fBfsxpfront\&.h\fP\&.
.SS "double PFrontStruct::Time"

.PP
Definition at line \fB69\fP of file \fBfsxpfront\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
