.TH "Proc_INFO" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Proc_INFO
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long long \fBval\fP [4]"
.br
.ti -1c
.RI "long long \fBtot\fP [4]"
.br
.ti -1c
.RI "long long \fBcount\fP"
.br
.ti -1c
.RI "int \fBEventSet\fP"
.br
.ti -1c
.RI "double \fBSum\fP"
.br
.ti -1c
.RI "double \fBSumSQR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBSamplePapiMT\&.c\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long long Proc_INFO::count"

.PP
Definition at line \fB21\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "int Proc_INFO::EventSet"

.PP
Definition at line \fB22\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "double Proc_INFO::Sum"

.PP
Definition at line \fB23\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "double Proc_INFO::SumSQR"

.PP
Definition at line \fB23\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "long long Proc_INFO::tot[4]"

.PP
Definition at line \fB20\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "long long Proc_INFO::val[4]"

.PP
Definition at line \fB19\fP of file \fBSamplePapiMT\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
