.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/rand2.cpp" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/rand2.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <stdlib\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIM1\fP   2147483563"
.br
.ti -1c
.RI "#define \fBIM2\fP   2147483399"
.br
.ti -1c
.RI "#define \fBAM\fP   (1\&.0/\fBIM1\fP)"
.br
.ti -1c
.RI "#define \fBIMM1\fP   (\fBIM1\fP\-1)"
.br
.ti -1c
.RI "#define \fBIA1\fP   40014"
.br
.ti -1c
.RI "#define \fBIA2\fP   40692"
.br
.ti -1c
.RI "#define \fBIQ1\fP   53668"
.br
.ti -1c
.RI "#define \fBIQ2\fP   52774"
.br
.ti -1c
.RI "#define \fBIR1\fP   12211"
.br
.ti -1c
.RI "#define \fBIR2\fP   3791"
.br
.ti -1c
.RI "#define \fBNTAB\fP   32"
.br
.ti -1c
.RI "#define \fBNDIV\fP   (1+\fBIMM1\fP/\fBNTAB\fP)"
.br
.ti -1c
.RI "#define \fBEPS\fP   1\&.2e\-7"
.br
.ti -1c
.RI "#define \fBRNMX\fP   (1\&.0\-\fBEPS\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBrand2\fP (long *idum)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AM   (1\&.0/\fBIM1\fP)"

.PP
Definition at line \fB38\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define EPS   1\&.2e\-7"

.PP
Definition at line \fB48\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define IA1   40014"

.PP
Definition at line \fB40\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define IA2   40692"

.PP
Definition at line \fB41\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define IM1   2147483563"

.PP
Definition at line \fB36\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define IM2   2147483399"

.PP
Definition at line \fB37\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define IMM1   (\fBIM1\fP\-1)"

.PP
Definition at line \fB39\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define IQ1   53668"

.PP
Definition at line \fB42\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define IQ2   52774"

.PP
Definition at line \fB43\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define IR1   12211"

.PP
Definition at line \fB44\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define IR2   3791"

.PP
Definition at line \fB45\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define NDIV   (1+\fBIMM1\fP/\fBNTAB\fP)"

.PP
Definition at line \fB47\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define NTAB   32"

.PP
Definition at line \fB46\fP of file \fBrand2\&.cpp\fP\&.
.SS "#define RNMX   (1\&.0\-\fBEPS\fP)"

.PP
Definition at line \fB49\fP of file \fBrand2\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "double rand2 (long * idum)"

.PP
Definition at line \fB67\fP of file \fBrand2\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
