.TH "Rasterize" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rasterize
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.PP
Inherits \fBAPolygon\fP, and \fBOutputFile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRasterize\fP ()"
.br
.ti -1c
.RI "\fB~Rasterize\fP ()"
.br
.ti -1c
.RI "void \fBrasterinit\fP (long CurrentFire, long ExNumPts, double SIMTIME, double TimeIncrement, double CuumTimeIncrement)"
.br
.ti -1c
.RI "void \fBRasterizePostFrontal\fP (double Resolution, char *FileName, bool ViewPort, long ThemeNumber)"
.br
.ti -1c
.RI "void \fBRasterReset\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "\fBAPolygon\fP ()"
.br
.ti -1c
.RI "\fB~APolygon\fP ()"
.br
.ti -1c
.RI "long \fBOverlap\fP (long count)"
.br
.ti -1c
.RI "double \fBdirection\fP (double xpt1, double ypt1)"
.br
.in -1c

Public Member Functions inherited from \fBOutputFile\fP
.in +1c
.ti -1c
.RI "\fBOutputFile\fP ()"
.br
.ti -1c
.RI "\fB~OutputFile\fP ()"
.br
.ti -1c
.RI "void \fBsetHeaderType\fP (long type)"
.br
.ti -1c
.RI "void \fBSelectOutputs\fP (long Type)"
.br
.ti -1c
.RI "void \fBSelectMemOutputs\fP (long Type)"
.br
.ti -1c
.RI "void \fBOptionalOutput\fP (bool FromMemory)"
.br
.ti -1c
.RI "void \fBConvF\fP ()"
.br
.ti -1c
.RI "void \fBInitRasterFiles\fP (long \fBHeaderType\fP)"
.br
.ti -1c
.RI "void \fBGetRasterExtent\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBAPolygon\fP
.in +1c
.ti -1c
.RI "double \fBstartx\fP"
.br
.ti -1c
.RI "double \fBstarty\fP"
.br
.in -1c

Protected Types inherited from \fBOutputFile\fP
.in +1c
.ti -1c
.RI "enum \fBCalcType\fP { \fBFLAME_LENGTH\fP, \fBHEAT_PER_AREA\fP, \fBFL_AND_HPA\fP, \fBCROWNFIRE\fP, \fBFIRELINE_INTENSITY\fP, \fBREACTION_INTENSITY\fP }"
.br
.ti -1c
.RI "typedef std::pair< long, long > \fBcoordinate\fP"
.br
.ti -1c
.RI "typedef std::map< \fBcoordinate\fP, \fBRastData\fP > \fBRasterMap\fP"
.br
.in -1c

Protected Member Functions inherited from \fBOutputFile\fP
.in +1c
.ti -1c
.RI "void \fBCalcs\fP (\fBCalcType\fP TYPE)"
.br
.ti -1c
.RI "void \fBFreeRastData\fP ()"
.br
.ti -1c
.RI "bool \fBSetRastData\fP (double xpt, double ypt, double time, double fli, double ros, double rcx, long dir)"
.br
.RI "Aggregates the provided set of fire behavior characteristics onto the raster\&. 
.br
 "
.ti -1c
.RI "void \fBWriteOptionalFile\fP ()"
.br
.RI "Writes a single value to the already opened, already positioned output file\&. 
.br
 "
.ti -1c
.RI "void \fBWriteRastMemFiles\fP ()"
.br
.ti -1c
.RI "bool \fBRastMemFile\fP (long Type)"
.br
.ti -1c
.RI "void \fBWriteFile\fP (long Type)"
.br
.in -1c

Protected Attributes inherited from \fBOutputFile\fP
.in +1c
.ti -1c
.RI "FILE * \fBotpfile\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBt\fP"
.br
.ti -1c
.RI "double \fBf\fP"
.br
.ti -1c
.RI "double \fBl\fP"
.br
.ti -1c
.RI "double \fBr\fP"
.br
.ti -1c
.RI "double \fBh\fP"
.br
.ti -1c
.RI "double \fBrx\fP"
.br
.ti -1c
.RI "double \fBNorth\fP"
.br
.ti -1c
.RI "double \fBSouth\fP"
.br
.ti -1c
.RI "double \fBEast\fP"
.br
.ti -1c
.RI "double \fBWest\fP"
.br
.ti -1c
.RI "long \fBc\fP"
.br
.ti -1c
.RI "long \fBd\fP"
.br
.ti -1c
.RI "double \fBconvf1\fP"
.br
.ti -1c
.RI "double \fBconvf2\fP"
.br
.ti -1c
.RI "double \fBconvf3\fP"
.br
.ti -1c
.RI "long \fBfilepos\fP"
.br
.ti -1c
.RI "long \fBFileOutput\fP"
.br
.ti -1c
.RI "long \fBnumrows\fP"
.br
.ti -1c
.RI "long \fBnumcols\fP"
.br
.ti -1c
.RI "long \fBNumRastAlloc\fP"
.br
.ti -1c
.RI "long \fBNumRastData\fP"
.br
.ti -1c
.RI "long \fBHeaderType\fP"
.br
.ti -1c
.RI "\fBRasterMap\fP \fBrd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB403\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Rasterize::Rasterize ()"

.PP
Definition at line \fB39\fP of file \fBfsxwrast\&.cpp\fP\&.
.SS "Rasterize::~Rasterize ()"

.PP
Definition at line \fB45\fP of file \fBfsxwrast\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Rasterize::rasterinit (long CurrentFire, long ExNumPts, double SIMTIME, double TimeIncrement, double CuumTimeIncrement)"

.PP
Definition at line \fB49\fP of file \fBfsxwrast\&.cpp\fP\&.
.SS "void Rasterize::RasterizePostFrontal (double Resolution, char * FileName, bool ViewPort, long ThemeNumber)"

.PP
Definition at line \fB356\fP of file \fBfsxwrast\&.cpp\fP\&.
.SS "void Rasterize::RasterReset ()"

.PP
Definition at line \fB66\fP of file \fBfsxwrast\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
