.TH "RelativeBurnPeriod" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RelativeBurnPeriod
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBStart\fP"
.br
.ti -1c
.RI "double \fBEnd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB908\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double RelativeBurnPeriod::End"

.PP
Definition at line \fB911\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double RelativeBurnPeriod::Start"

.PP
Definition at line \fB910\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
