.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/SamplePapiMT.c" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/SamplePapiMT.c
.SH SYNOPSIS
.br
.PP
\fR#include <sched\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include <assert\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <papi\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBProc_INFO\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_GNU_SOURCE\fP"
.br
.ti -1c
.RI "#define \fBMAX_PROCS\fP   32"
.br
.ti -1c
.RI "#define \fBERROR_RETURN\fP(retval)   { fprintf(stderr, 'Error %d %s:line %d: \\n', retval,__FILE__,__LINE__);  exit(retval); }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBproc_get_num_cpus\fP (void)"
.br
.ti -1c
.RI "void \fBSample_SetCPU\fP (int cpu_id)"
.br
.ti -1c
.RI "void \fBSample_ON\fP (int i)"
.br
.ti -1c
.RI "void \fBSample_OFF\fP (int i)"
.br
.ti -1c
.RI "void \fBSample_Value\fP (int i, long long V)"
.br
.ti -1c
.RI "void \fBSample_ValueDiff\fP (int i, long long V)"
.br
.ti -1c
.RI "void \fBread_events\fP ()"
.br
.ti -1c
.RI "void \fBSample_Init\fP ()"
.br
.ti -1c
.RI "void \fBSample_End\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBProc_INFO\fP \fBSample_INFO\fP [\fBMAX_PROCS\fP]"
.br
.ti -1c
.RI "char * \fBEventStr\fP [4]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _GNU_SOURCE"

.PP
Definition at line \fB1\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "#define ERROR_RETURN(retval)   { fprintf(stderr, 'Error %d %s:line %d: \\n', retval,__FILE__,__LINE__);  exit(retval); }"

.PP
Definition at line \fB29\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "#define MAX_PROCS   32"

.PP
Definition at line \fB15\fP of file \fBSamplePapiMT\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int proc_get_num_cpus (void)"

.PP
Definition at line \fB38\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "void read_events ()"

.PP
Definition at line \fB137\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "void Sample_End (void)"

.PP
Definition at line \fB201\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "void Sample_Init (void)"

.PP
Definition at line \fB172\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "void Sample_OFF (int i)"

.PP
Definition at line \fB65\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "void Sample_ON (int i)"

.PP
Definition at line \fB51\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "void Sample_SetCPU (int cpu_id)"

.PP
Definition at line \fB42\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "void Sample_Value (int i, long long V)"

.PP
Definition at line \fB77\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "void Sample_ValueDiff (int i, long long V)"

.PP
Definition at line \fB102\fP of file \fBSamplePapiMT\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char* EventStr[4]"

.PP
Definition at line \fB27\fP of file \fBSamplePapiMT\&.c\fP\&.
.SS "struct \fBProc_INFO\fP Sample_INFO[\fBMAX_PROCS\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
