.TH "SHPObject" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SHPObject
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shapefil\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnSHPType\fP"
.br
.ti -1c
.RI "int \fBnShapeId\fP"
.br
.ti -1c
.RI "int \fBnParts\fP"
.br
.ti -1c
.RI "int * \fBpanPartStart\fP"
.br
.ti -1c
.RI "int * \fBpanPartType\fP"
.br
.ti -1c
.RI "int \fBnVertices\fP"
.br
.ti -1c
.RI "double * \fBpadfX\fP"
.br
.ti -1c
.RI "double * \fBpadfY\fP"
.br
.ti -1c
.RI "double * \fBpadfZ\fP"
.br
.ti -1c
.RI "double * \fBpadfM\fP"
.br
.ti -1c
.RI "double \fBdfXMin\fP"
.br
.ti -1c
.RI "double \fBdfYMin\fP"
.br
.ti -1c
.RI "double \fBdfZMin\fP"
.br
.ti -1c
.RI "double \fBdfMMin\fP"
.br
.ti -1c
.RI "double \fBdfXMax\fP"
.br
.ti -1c
.RI "double \fBdfYMax\fP"
.br
.ti -1c
.RI "double \fBdfZMax\fP"
.br
.ti -1c
.RI "double \fBdfMMax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB215\fP of file \fBshapefil\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double SHPObject::dfMMax"

.PP
Definition at line \fB239\fP of file \fBshapefil\&.h\fP\&.
.SS "double SHPObject::dfMMin"

.PP
Definition at line \fB234\fP of file \fBshapefil\&.h\fP\&.
.SS "double SHPObject::dfXMax"

.PP
Definition at line \fB236\fP of file \fBshapefil\&.h\fP\&.
.SS "double SHPObject::dfXMin"

.PP
Definition at line \fB231\fP of file \fBshapefil\&.h\fP\&.
.SS "double SHPObject::dfYMax"

.PP
Definition at line \fB237\fP of file \fBshapefil\&.h\fP\&.
.SS "double SHPObject::dfYMin"

.PP
Definition at line \fB232\fP of file \fBshapefil\&.h\fP\&.
.SS "double SHPObject::dfZMax"

.PP
Definition at line \fB238\fP of file \fBshapefil\&.h\fP\&.
.SS "double SHPObject::dfZMin"

.PP
Definition at line \fB233\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPObject::nParts"

.PP
Definition at line \fB221\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPObject::nShapeId"

.PP
Definition at line \fB219\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPObject::nSHPType"

.PP
Definition at line \fB217\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPObject::nVertices"

.PP
Definition at line \fB225\fP of file \fBshapefil\&.h\fP\&.
.SS "double* SHPObject::padfM"

.PP
Definition at line \fB229\fP of file \fBshapefil\&.h\fP\&.
.SS "double* SHPObject::padfX"

.PP
Definition at line \fB226\fP of file \fBshapefil\&.h\fP\&.
.SS "double* SHPObject::padfY"

.PP
Definition at line \fB227\fP of file \fBshapefil\&.h\fP\&.
.SS "double* SHPObject::padfZ"

.PP
Definition at line \fB228\fP of file \fBshapefil\&.h\fP\&.
.SS "int* SHPObject::panPartStart"

.PP
Definition at line \fB222\fP of file \fBshapefil\&.h\fP\&.
.SS "int* SHPObject::panPartType"

.PP
Definition at line \fB223\fP of file \fBshapefil\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
