.TH "SHPTree" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SHPTree
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shapefil\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSHPHandle\fP \fBhSHP\fP"
.br
.ti -1c
.RI "int \fBnMaxDepth\fP"
.br
.ti -1c
.RI "int \fBnDimension\fP"
.br
.ti -1c
.RI "\fBSHPTreeNode\fP * \fBpsRoot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB296\fP of file \fBshapefil\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSHPHandle\fP SHPTree::hSHP"

.PP
Definition at line \fB298\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPTree::nDimension"

.PP
Definition at line \fB301\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPTree::nMaxDepth"

.PP
Definition at line \fB300\fP of file \fBshapefil\&.h\fP\&.
.SS "\fBSHPTreeNode\fP* SHPTree::psRoot"

.PP
Definition at line \fB303\fP of file \fBshapefil\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
