.TH "StationGrid" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StationGrid
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStationGrid\fP ()"
.br
.ti -1c
.RI "\fB~StationGrid\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBXDim\fP"
.br
.ti -1c
.RI "long \fBYDim\fP"
.br
.ti -1c
.RI "double \fBWidth\fP"
.br
.ti -1c
.RI "double \fBHeight\fP"
.br
.ti -1c
.RI "long * \fBGrid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB378\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StationGrid::StationGrid ()"

.PP
Definition at line \fB3137\fP of file \fBfsglbvar\&.cpp\fP\&.
.SS "StationGrid::~StationGrid ()"

.PP
Definition at line \fB3143\fP of file \fBfsglbvar\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long* StationGrid::Grid"

.PP
Definition at line \fB384\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double StationGrid::Height"

.PP
Definition at line \fB383\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double StationGrid::Width"

.PP
Definition at line \fB382\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long StationGrid::XDim"

.PP
Definition at line \fB380\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long StationGrid::YDim"

.PP
Definition at line \fB381\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
