.TH "TAtkTreeWindow" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAtkTreeWindow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tempatk\&.h>\fP
.PP
Inherits TTreeWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTAtkTreeWindow\fP (TWindow *parent, int resID)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB42\fP of file \fBtempatk\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TAtkTreeWindow::TAtkTreeWindow (TWindow * parent, int resID)"


.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
