.TH "TransCombMap" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransCombMap
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransCombMap\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBFileName\fP [256]"
.br
.ti -1c
.RI "char \fBResolution\fP [16]"
.br
.ti -1c
.RI "int \fBenrate\fP"
.br
.ti -1c
.RI "int \fBfuelrate\fP"
.br
.ti -1c
.RI "int \fBflame\fP"
.br
.ti -1c
.RI "int \fBpm25\fP"
.br
.ti -1c
.RI "int \fBpm10\fP"
.br
.ti -1c
.RI "int \fBco\fP"
.br
.ti -1c
.RI "int \fBco2\fP"
.br
.ti -1c
.RI "int \fBch4\fP"
.br
.ti -1c
.RI "int \fBx1\fP"
.br
.ti -1c
.RI "int \fBxc\fP"
.br
.ti -1c
.RI "int \fBvp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB933\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransCombMap::TransCombMap ()"

.SH "Member Data Documentation"
.PP 
.SS "int TransCombMap::ch4"

.PP
Definition at line \fB937\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::co"

.PP
Definition at line \fB937\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::co2"

.PP
Definition at line \fB937\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::enrate"

.PP
Definition at line \fB937\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char TransCombMap::FileName[256]"

.PP
Definition at line \fB935\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::flame"

.PP
Definition at line \fB937\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::fuelrate"

.PP
Definition at line \fB937\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::pm10"

.PP
Definition at line \fB937\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::pm25"

.PP
Definition at line \fB937\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char TransCombMap::Resolution[16]"

.PP
Definition at line \fB936\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::vp"

.PP
Definition at line \fB939\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::x1"

.PP
Definition at line \fB938\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransCombMap::xc"

.PP
Definition at line \fB938\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
