.TH "TransMult" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransMult
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsatkdlg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBMult\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB84\fP of file \fBfsatkdlg\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char TransMult::Mult[64]"

.PP
Definition at line \fB86\fP of file \fBfsatkdlg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
