.TH "TransAttack" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransAttack
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsatkdlg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBBurnOut\fP"
.br
.ti -1c
.RI "int \fBLeft\fP"
.br
.ti -1c
.RI "int \fBRight\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBLineProd\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBBurnDelay\fP"
.br
.ti -1c
.RI "\fBTScrollBarData\fP \fBFireDist\fP"
.br
.ti -1c
.RI "int \fBdir\fP"
.br
.ti -1c
.RI "int \fBindir\fP"
.br
.ti -1c
.RI "int \fBpdir\fP"
.br
.ti -1c
.RI "int \fBgdir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB62\fP of file \fBfsatkdlg\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTScrollBarData\fP TransAttack::BurnDelay"

.PP
Definition at line \fB67\fP of file \fBfsatkdlg\&.h\fP\&.
.SS "int TransAttack::BurnOut"

.PP
Definition at line \fB64\fP of file \fBfsatkdlg\&.h\fP\&.
.SS "int TransAttack::dir"

.PP
Definition at line \fB69\fP of file \fBfsatkdlg\&.h\fP\&.
.SS "\fBTScrollBarData\fP TransAttack::FireDist"

.PP
Definition at line \fB68\fP of file \fBfsatkdlg\&.h\fP\&.
.SS "int TransAttack::gdir"

.PP
Definition at line \fB72\fP of file \fBfsatkdlg\&.h\fP\&.
.SS "int TransAttack::indir"

.PP
Definition at line \fB70\fP of file \fBfsatkdlg\&.h\fP\&.
.SS "int TransAttack::Left"

.PP
Definition at line \fB65\fP of file \fBfsatkdlg\&.h\fP\&.
.SS "\fBTScrollBarData\fP TransAttack::LineProd"

.PP
Definition at line \fB66\fP of file \fBfsatkdlg\&.h\fP\&.
.SS "int TransAttack::pdir"

.PP
Definition at line \fB71\fP of file \fBfsatkdlg\&.h\fP\&.
.SS "int TransAttack::Right"

.PP
Definition at line \fB65\fP of file \fBfsatkdlg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
