.TH "TransWtrEdit" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransWtrEdit
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wwedits\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBFileName\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB127\fP of file \fBwwedits\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char TransWtrEdit::FileName[256]"

.PP
Definition at line \fB129\fP of file \fBwwedits\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
