.TH "TransAirAttack" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransAirAttack
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsairdlg\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBl1\fP"
.br
.ti -1c
.RI "int \fBl2\fP"
.br
.ti -1c
.RI "int \fBl3\fP"
.br
.ti -1c
.RI "int \fBl4\fP"
.br
.ti -1c
.RI "int \fBl5\fP"
.br
.ti -1c
.RI "int \fBl6\fP"
.br
.ti -1c
.RI "char \fBDuration\fP [16]"
.br
.ti -1c
.RI "int \fBgc1\fP"
.br
.ti -1c
.RI "int \fBgc2\fP"
.br
.ti -1c
.RI "int \fBgc3\fP"
.br
.ti -1c
.RI "int \fBgc4\fP"
.br
.ti -1c
.RI "char \fBgname\fP [24]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB73\fP of file \fBfsairdlg\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "char TransAirAttack::Duration[16]"

.PP
Definition at line \fB76\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::gc1"

.PP
Definition at line \fB77\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::gc2"

.PP
Definition at line \fB77\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::gc3"

.PP
Definition at line \fB77\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::gc4"

.PP
Definition at line \fB77\fP of file \fBfsairdlg\&.h\fP\&.
.SS "char TransAirAttack::gname[24]"

.PP
Definition at line \fB78\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::l1"

.PP
Definition at line \fB75\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::l2"

.PP
Definition at line \fB75\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::l3"

.PP
Definition at line \fB75\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::l4"

.PP
Definition at line \fB75\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::l5"

.PP
Definition at line \fB75\fP of file \fBfsairdlg\&.h\fP\&.
.SS "int TransAirAttack::l6"

.PP
Definition at line \fB75\fP of file \fBfsairdlg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
