.TH "TTransAirAttackData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransAirAttackData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsairdlg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransAirAttackData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransAirAttack\fP \fBDat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB83\fP of file \fBfsairdlg\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransAirAttackData::TTransAirAttackData ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBTransAirAttack\fP TTransAirAttackData::Dat"

.PP
Definition at line \fB85\fP of file \fBfsairdlg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
