.TH "TTransOutputData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransOutputData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransOutputData\fP ()"
.br
.ti -1c
.RI "void \fBResetData\fP (bool All)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOutputData\fP \fBDat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB198\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransOutputData::TTransOutputData ()"

.SH "Member Function Documentation"
.PP 
.SS "void TTransOutputData::ResetData (bool All)"

.SH "Member Data Documentation"
.PP 
.SS "\fBOutputData\fP TTransOutputData::Dat"

.PP
Definition at line \fB200\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
