.TH "TTransOptionsData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransOptionsData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransOptionsData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOptionsData\fP \fBDat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB234\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransOptionsData::TTransOptionsData ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBOptionsData\fP TTransOptionsData::Dat"

.PP
Definition at line \fB236\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
