.TH "TTransLandDisplayData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransLandDisplayData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransLandDisplayData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLandDisplayData\fP \fBDat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB170\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransLandDisplayData::TTransLandDisplayData ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBLandDisplayData\fP TTransLandDisplayData::Dat"

.PP
Definition at line \fB172\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
