.TH "TTransDisplayData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransDisplayData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransDisplayData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDisplayData\fP \fBDat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB147\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransDisplayData::TTransDisplayData ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBDisplayData\fP TTransDisplayData::Dat"

.PP
Definition at line \fB149\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
