.TH "TTransAccelData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransAccelData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxwaccl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransAccelData\fP ()"
.br
.ti -1c
.RI "void \fBResetData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAccelData\fP \fBDat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB44\fP of file \fBfsxwaccl\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransAccelData::TTransAccelData ()"

.PP
Definition at line \fB42\fP of file \fBfsxwaccl\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TTransAccelData::ResetData ()"

.PP
Definition at line \fB48\fP of file \fBfsxwaccl\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAccelData\fP TTransAccelData::Dat"

.PP
Definition at line \fB46\fP of file \fBfsxwaccl\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
