.TH "TTransAttackData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransAttackData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsatkdlg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransAttackData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransAttack\fP \fBDat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB76\fP of file \fBfsatkdlg\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransAttackData::TTransAttackData ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBTransAttack\fP TTransAttackData::Dat"

.PP
Definition at line \fB78\fP of file \fBfsatkdlg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
