.TH "TTransModelData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransModelData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransModelData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBModelData\fP \fBDat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB215\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransModelData::TTransModelData ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBModelData\fP TTransModelData::Dat"

.PP
Definition at line \fB217\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
