.TH "vec" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vec
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vec\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvec\fP (double xx, double yy)"
.br
.ti -1c
.RI "\fBvec\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBvec\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vec::vec (double xx, double yy)\fR [inline]\fP"

.PP
Definition at line \fB28\fP of file \fBvec\&.h\fP\&.
.SS "vec::vec ()\fR [inline]\fP"

.PP
Definition at line \fB33\fP of file \fBvec\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double vec::x"

.PP
Definition at line \fB26\fP of file \fBvec\&.h\fP\&.
.SS "double vec::y"

.PP
Definition at line \fB26\fP of file \fBvec\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
