.TH "VectorTheme" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VectorTheme
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <themes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBVectorNum\fP"
.br
.ti -1c
.RI "char \fBFileName\fP [256]"
.br
.ti -1c
.RI "long \fBFileType\fP"
.br
.ti -1c
.RI "long \fBPermanent\fP"
.br
.ti -1c
.RI "int \fBPenStyle\fP"
.br
.ti -1c
.RI "int \fBPenWidth\fP"
.br
.ti -1c
.RI "bool \fBOnOff\fP"
.br
.ti -1c
.RI "bool \fBOnOff3d\fP"
.br
.ti -1c
.RI "bool \fBChanged\fP"
.br
.ti -1c
.RI "long \fBPriority\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB134\fP of file \fBthemes\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool VectorTheme::Changed"

.PP
Definition at line \fB145\fP of file \fBthemes\&.h\fP\&.
.SS "char VectorTheme::FileName[256]"

.PP
Definition at line \fB137\fP of file \fBthemes\&.h\fP\&.
.SS "long VectorTheme::FileType"

.PP
Definition at line \fB138\fP of file \fBthemes\&.h\fP\&.
.SS "bool VectorTheme::OnOff"

.PP
Definition at line \fB143\fP of file \fBthemes\&.h\fP\&.
.SS "bool VectorTheme::OnOff3d"

.PP
Definition at line \fB144\fP of file \fBthemes\&.h\fP\&.
.SS "int VectorTheme::PenStyle"

.PP
Definition at line \fB141\fP of file \fBthemes\&.h\fP\&.
.SS "int VectorTheme::PenWidth"

.PP
Definition at line \fB142\fP of file \fBthemes\&.h\fP\&.
.SS "long VectorTheme::Permanent"

.PP
Definition at line \fB139\fP of file \fBthemes\&.h\fP\&.
.SS "long VectorTheme::Priority"

.PP
Definition at line \fB146\fP of file \fBthemes\&.h\fP\&.
.SS "long VectorTheme::VectorNum"

.PP
Definition at line \fB136\fP of file \fBthemes\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
