.TH "ViewRasterLegend" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewRasterLegend
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsrstlg\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBfsrstlg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
