.TH "WeatherData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WeatherData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBmo\fP"
.br
.ti -1c
.RI "long \fBdy\fP"
.br
.ti -1c
.RI "double \fBrn\fP"
.br
.ti -1c
.RI "long \fBt1\fP"
.br
.ti -1c
.RI "long \fBt2\fP"
.br
.ti -1c
.RI "double \fBT1\fP"
.br
.ti -1c
.RI "double \fBT2\fP"
.br
.ti -1c
.RI "long \fBH1\fP"
.br
.ti -1c
.RI "long \fBH2\fP"
.br
.ti -1c
.RI "double \fBel\fP"
.br
.ti -1c
.RI "long \fBtr1\fP"
.br
.ti -1c
.RI "long \fBtr2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB343\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long WeatherData::dy"

.PP
Definition at line \fB346\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double WeatherData::el"

.PP
Definition at line \fB354\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WeatherData::H1"

.PP
Definition at line \fB352\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WeatherData::H2"

.PP
Definition at line \fB353\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WeatherData::mo"

.PP
Definition at line \fB345\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double WeatherData::rn"

.PP
Definition at line \fB347\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WeatherData::t1"

.PP
Definition at line \fB348\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double WeatherData::T1"

.PP
Definition at line \fB350\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WeatherData::t2"

.PP
Definition at line \fB349\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double WeatherData::T2"

.PP
Definition at line \fB351\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WeatherData::tr1"

.PP
Definition at line \fB355\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WeatherData::tr2"

.PP
Definition at line \fB356\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
