.TH "WindData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBmo\fP"
.br
.ti -1c
.RI "long \fBdy\fP"
.br
.ti -1c
.RI "long \fBhr\fP"
.br
.ti -1c
.RI "double \fBws\fP"
.br
.ti -1c
.RI "long \fBwd\fP"
.br
.ti -1c
.RI "long \fBcl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB314\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long WindData::cl"

.PP
Definition at line \fB321\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WindData::dy"

.PP
Definition at line \fB317\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WindData::hr"

.PP
Definition at line \fB318\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WindData::mo"

.PP
Definition at line \fB316\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long WindData::wd"

.PP
Definition at line \fB320\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double WindData::ws"

.PP
Definition at line \fB319\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
