.TH "BurnStruct" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BurnStruct
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <burnupw\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtime\fP"
.br
.ti -1c
.RI "double \fBwdf\fP"
.br
.ti -1c
.RI "double \fBff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB56\fP of file \fBburnupw\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double BurnStruct::ff"

.PP
Definition at line \fB60\fP of file \fBburnupw\&.h\fP\&.
.SS "double BurnStruct::time"

.PP
Definition at line \fB58\fP of file \fBburnupw\&.h\fP\&.
.SS "double BurnStruct::wdf"

.PP
Definition at line \fB59\fP of file \fBburnupw\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
