.TH "celldata32bits" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
celldata32bits
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBe\fP"
.br
.ti -1c
.RI "int16_t \fBs\fP"
.br
.ti -1c
.RI "int16_t \fBa\fP"
.br
.ti -1c
.RI "int16_t \fBf\fP"
.br
.ti -1c
.RI "int16_t \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB667\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t celldata32bits::a"

.PP
Definition at line \fB671\fP of file \fBfsglbvar\&.h\fP\&.
.SS "int16_t celldata32bits::c"

.PP
Definition at line \fB673\fP of file \fBfsglbvar\&.h\fP\&.
.SS "int16_t celldata32bits::e"

.PP
Definition at line \fB669\fP of file \fBfsglbvar\&.h\fP\&.
.SS "int16_t celldata32bits::f"

.PP
Definition at line \fB672\fP of file \fBfsglbvar\&.h\fP\&.
.SS "int16_t celldata32bits::s"

.PP
Definition at line \fB670\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
