.TH "CrossThread" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CrossThread
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrossThread\fP ()"
.br
.ti -1c
.RI "\fB~CrossThread\fP ()"
.br
.ti -1c
.RI "void \fBSetRange\fP (long SpanAStart, long SpanAEnd)"
.br
.ti -1c
.RI "void \fBStartCrossThread\fP (long threadorder, long currentfire, long nextfire)"
.br
.ti -1c
.RI "long \fBGetNumCross\fP ()"
.br
.ti -1c
.RI "long * \fBGetIsect\fP ()"
.br
.ti -1c
.RI "double * \fBGetIpoint\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB184\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CrossThread::CrossThread ()"

.PP
Definition at line \fB43\fP of file \fBcrossthread\&.cpp\fP\&.
.SS "CrossThread::~CrossThread ()"

.PP
Definition at line \fB55\fP of file \fBcrossthread\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double * CrossThread::GetIpoint ()"

.PP
Definition at line \fB194\fP of file \fBcrossthread\&.cpp\fP\&.
.SS "long * CrossThread::GetIsect ()"

.PP
Definition at line \fB188\fP of file \fBcrossthread\&.cpp\fP\&.
.SS "long CrossThread::GetNumCross ()"

.PP
Definition at line \fB182\fP of file \fBcrossthread\&.cpp\fP\&.
.SS "void CrossThread::SetRange (long SpanAStart, long SpanAEnd)"

.PP
Definition at line \fB174\fP of file \fBcrossthread\&.cpp\fP\&.
.SS "void CrossThread::StartCrossThread (long threadorder, long currentfire, long nextfire)"

.PP
Definition at line \fB140\fP of file \fBcrossthread\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
