.TH "DBFInfo" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBFInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shapefil\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBfp\fP"
.br
.ti -1c
.RI "int \fBnRecords\fP"
.br
.ti -1c
.RI "int \fBnRecordLength\fP"
.br
.ti -1c
.RI "int \fBnHeaderLength\fP"
.br
.ti -1c
.RI "int \fBnFields\fP"
.br
.ti -1c
.RI "int * \fBpanFieldOffset\fP"
.br
.ti -1c
.RI "int * \fBpanFieldSize\fP"
.br
.ti -1c
.RI "int * \fBpanFieldDecimals\fP"
.br
.ti -1c
.RI "char * \fBpachFieldType\fP"
.br
.ti -1c
.RI "char * \fBpszHeader\fP"
.br
.ti -1c
.RI "int \fBnCurrentRecord\fP"
.br
.ti -1c
.RI "int \fBbCurrentRecordModified\fP"
.br
.ti -1c
.RI "char * \fBpszCurrentRecord\fP"
.br
.ti -1c
.RI "int \fBbNoHeader\fP"
.br
.ti -1c
.RI "int \fBbUpdated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB329\fP of file \fBshapefil\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int DBFInfo::bCurrentRecordModified"

.PP
Definition at line \fB346\fP of file \fBshapefil\&.h\fP\&.
.SS "int DBFInfo::bNoHeader"

.PP
Definition at line \fB349\fP of file \fBshapefil\&.h\fP\&.
.SS "int DBFInfo::bUpdated"

.PP
Definition at line \fB350\fP of file \fBshapefil\&.h\fP\&.
.SS "FILE* DBFInfo::fp"

.PP
Definition at line \fB331\fP of file \fBshapefil\&.h\fP\&.
.SS "int DBFInfo::nCurrentRecord"

.PP
Definition at line \fB345\fP of file \fBshapefil\&.h\fP\&.
.SS "int DBFInfo::nFields"

.PP
Definition at line \fB337\fP of file \fBshapefil\&.h\fP\&.
.SS "int DBFInfo::nHeaderLength"

.PP
Definition at line \fB336\fP of file \fBshapefil\&.h\fP\&.
.SS "int DBFInfo::nRecordLength"

.PP
Definition at line \fB335\fP of file \fBshapefil\&.h\fP\&.
.SS "int DBFInfo::nRecords"

.PP
Definition at line \fB333\fP of file \fBshapefil\&.h\fP\&.
.SS "char* DBFInfo::pachFieldType"

.PP
Definition at line \fB341\fP of file \fBshapefil\&.h\fP\&.
.SS "int* DBFInfo::panFieldDecimals"

.PP
Definition at line \fB340\fP of file \fBshapefil\&.h\fP\&.
.SS "int* DBFInfo::panFieldOffset"

.PP
Definition at line \fB338\fP of file \fBshapefil\&.h\fP\&.
.SS "int* DBFInfo::panFieldSize"

.PP
Definition at line \fB339\fP of file \fBshapefil\&.h\fP\&.
.SS "char* DBFInfo::pszCurrentRecord"

.PP
Definition at line \fB347\fP of file \fBshapefil\&.h\fP\&.
.SS "char* DBFInfo::pszHeader"

.PP
Definition at line \fB343\fP of file \fBshapefil\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
