.TH "Embers::spotdata" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Embers::spotdata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBTimeRem\fP"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB983\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "void* Embers::spotdata::next"

.PP
Definition at line \fB988\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Embers::spotdata::TimeRem"

.PP
Definition at line \fB987\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Embers::spotdata::x"

.PP
Definition at line \fB985\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double Embers::spotdata::y"

.PP
Definition at line \fB986\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
