.TH "FELocalSite" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FELocalSite
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsx4\&.hpp>\fP
.PP
Inherits \fBLandscapeData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFELocalSite\fP ()"
.br
.ti -1c
.RI "void \fBGetFireEnvironment\fP (\fBFireEnvironment2\fP *env, double SimTime, bool All)"
.br
.ti -1c
.RI "long \fBGetLandscapeData\fP (double xpt, double ypt, \fBLandscapeStruct\fP &ls)"
.br
.ti -1c
.RI "long \fBGetLandscapeData\fP (double xpt, double ypt)"
.br
.ti -1c
.RI "void \fBGetEnvironmentData\fP (\fBEnvironmentData\fP *ed2)"
.br
.in -1c

Public Member Functions inherited from \fBLandscapeData\fP
.in +1c
.ti -1c
.RI "void \fBElevConvert\fP (short)"
.br
.ti -1c
.RI "void \fBSlopeConvert\fP (short)"
.br
.ti -1c
.RI "void \fBAspectConvert\fP (short)"
.br
.ti -1c
.RI "void \fBFuelConvert\fP (short)"
.br
.ti -1c
.RI "void \fBCoverConvert\fP (short)"
.br
.ti -1c
.RI "void \fBHeightConvert\fP (short)"
.br
.ti -1c
.RI "void \fBBaseConvert\fP (short)"
.br
.ti -1c
.RI "void \fBDensityConvert\fP (short)"
.br
.ti -1c
.RI "void \fBDuffConvert\fP (short)"
.br
.ti -1c
.RI "void \fBWoodyConvert\fP (short)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBStationNumber\fP"
.br
.ti -1c
.RI "double \fBAirTemp\fP"
.br
.ti -1c
.RI "double \fBAirHumid\fP"
.br
.ti -1c
.RI "double \fBPtTemperature\fP"
.br
.ti -1c
.RI "double \fBPtHumidity\fP"
.br
.in -1c

Public Attributes inherited from \fBLandscapeData\fP
.in +1c
.ti -1c
.RI "\fBLandscapeStruct\fP \fBld\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB883\fP of file \fBfsx4\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FELocalSite::FELocalSite ()"

.PP
Definition at line \fB177\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void FELocalSite::GetEnvironmentData (\fBEnvironmentData\fP * ed2)"

.PP
Definition at line \fB246\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "void FELocalSite::GetFireEnvironment (\fBFireEnvironment2\fP * env, double SimTime, bool All)"

.PP
Definition at line \fB267\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "long FELocalSite::GetLandscapeData (double xpt, double ypt)"

.PP
Definition at line \fB186\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SS "long FELocalSite::GetLandscapeData (double xpt, double ypt, \fBLandscapeStruct\fP & ls)"

.PP
Definition at line \fB215\fP of file \fBfsxwfms2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double FELocalSite::AirHumid"

.PP
Definition at line \fB903\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FELocalSite::AirTemp"

.PP
Definition at line \fB903\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FELocalSite::PtHumidity"

.PP
Definition at line \fB903\fP of file \fBfsx4\&.hpp\fP\&.
.SS "double FELocalSite::PtTemperature"

.PP
Definition at line \fB903\fP of file \fBfsx4\&.hpp\fP\&.
.SS "long FELocalSite::StationNumber"

.PP
Definition at line \fB902\fP of file \fBfsx4\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
