.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsairatk.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsairatk.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdlib\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include 'fsxwbar\&.h'\fP
.br
\fR#include 'fsxlandt\&.h'\fP
.br
\fR#include <time\&.h>\fP
.br
\fR#include <sys/timeb\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAirCraft\fP"
.br
.ti -1c
.RI "struct \fBAirAttackData\fP"
.br
.ti -1c
.RI "class \fBAirAttack\fP"
.br
.ti -1c
.RI "struct \fBGroupAttackData\fP"
.br
.ti -1c
.RI "class \fBGroupAirAttack\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGROUPSIZE\fP   20"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBGetNumAirCraft\fP ()"
.br
.ti -1c
.RI "void \fBSetNumAirCraft\fP (long NumCraft)"
.br
.ti -1c
.RI "bool \fBLoadAirCraft\fP (char *FileName, bool AppendList)"
.br
.ti -1c
.RI "long \fBSetNewAirCraft\fP ()"
.br
.ti -1c
.RI "\fBAirCraft\fP * \fBGetAirCraft\fP (long AirCraftNumber)"
.br
.ti -1c
.RI "long \fBSetAirCraft\fP (long AirCraftNumber)"
.br
.ti -1c
.RI "void \fBFreeAirCraft\fP (long AirCraftNumber)"
.br
.ti -1c
.RI "long \fBSetupAirAttack\fP (long AirCraftNumber, long CoverageLevel, long Duration, double *startpoint)"
.br
.ti -1c
.RI "void \fBCancelAirAttack\fP (long AirAttackCounter)"
.br
.ti -1c
.RI "void \fBLoadAirAttack\fP (\fBAirAttackData\fP airattackdata)"
.br
.ti -1c
.RI "void \fBFreeAllAirAttacks\fP ()"
.br
.ti -1c
.RI "\fBAirAttackData\fP * \fBGetAirAttack\fP (long AirAttackCounter)"
.br
.ti -1c
.RI "\fBAirAttackData\fP * \fBGetAirAttackByOrder\fP (long OrdinalAttackNumber)"
.br
.ti -1c
.RI "void \fBSetNewFireNumberForAirAttack\fP (long OldFireNum, long NewFireNum)"
.br
.ti -1c
.RI "long \fBGetNumAirAttacks\fP ()"
.br
.ti -1c
.RI "void \fBSetNumAirAttacks\fP (long NumAtk)"
.br
.ti -1c
.RI "long \fBSetupGroupAirAttack\fP (long AirCraftNumber, long CoverageLevel, long Duration, double *line, long FireNum, char *GroupName)"
.br
.ti -1c
.RI "\fBGroupAttackData\fP * \fBReassignGroupAirAttack\fP (\fBGroupAttackData\fP *atk)"
.br
.ti -1c
.RI "void \fBCancelGroupAirAttack\fP (long GroupCounter)"
.br
.ti -1c
.RI "void \fBLoadGroupAttack\fP (\fBGroupAttackData\fP groupattackdata)"
.br
.ti -1c
.RI "void \fBFreeAllGroupAirAttacks\fP ()"
.br
.ti -1c
.RI "\fBGroupAttackData\fP * \fBGetGroupAirAttack\fP (long GroupAttackCounter)"
.br
.ti -1c
.RI "\fBGroupAttackData\fP * \fBGetGroupAttackByOrder\fP (long OrdinalAttackNumber)"
.br
.ti -1c
.RI "\fBGroupAttackData\fP * \fBGetGroupAttackForFireNumber\fP (long CurrentFire, long StartNum, long *LastNum)"
.br
.ti -1c
.RI "void \fBSetNewFireNumberForGroupAttack\fP (long OldFireNum, long NewFireNum)"
.br
.ti -1c
.RI "long \fBGetNumGroupAttacks\fP ()"
.br
.ti -1c
.RI "void \fBSetNumGroupAttacks\fP (long NumGroups)"
.br
.ti -1c
.RI "void \fBWriteAirAttackLog\fP (\fBAirAttackData\fP *atk)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GROUPSIZE   20"

.PP
Definition at line \fB96\fP of file \fBfsairatk\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void CancelAirAttack (long AirAttackCounter)"

.PP
Definition at line \fB405\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void CancelGroupAirAttack (long GroupCounter)"

.PP
Definition at line \fB648\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void FreeAirCraft (long AirCraftNumber)"

.PP
Definition at line \fB234\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void FreeAllAirAttacks ()"

.PP
Definition at line \fB454\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void FreeAllGroupAirAttacks ()"

.PP
Definition at line \fB766\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "\fBAirAttackData\fP * GetAirAttack (long AirAttackCounter)"

.PP
Definition at line \fB476\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "\fBAirAttackData\fP * GetAirAttackByOrder (long OrdinalAttackNumber)"

.PP
Definition at line \fB497\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "\fBAirCraft\fP * GetAirCraft (long AirCraftNumber)"

.PP
Definition at line \fB217\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "\fBGroupAttackData\fP * GetGroupAirAttack (long GroupAttackCounter)"

.PP
Definition at line \fB794\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "\fBGroupAttackData\fP * GetGroupAttackByOrder (long OrdinalAttackNumber)"

.PP
Definition at line \fB815\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "\fBGroupAttackData\fP * GetGroupAttackForFireNumber (long CurrentFire, long StartNum, long * LastNum)"

.PP
Definition at line \fB832\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "long GetNumAirAttacks ()"

.PP
Definition at line \fB248\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "long GetNumAirCraft ()"

.PP
Definition at line \fB98\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "long GetNumGroupAttacks ()"

.PP
Definition at line \fB867\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void LoadAirAttack (\fBAirAttackData\fP airattackdata)"

.PP
Definition at line \fB436\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "bool LoadAirCraft (char * FileName, bool AppendList)"

.PP
Definition at line \fB109\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void LoadGroupAttack (\fBGroupAttackData\fP groupattackdata)"

.PP
Definition at line \fB687\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "\fBGroupAttackData\fP * ReassignGroupAirAttack (\fBGroupAttackData\fP * atk)"

.PP
Definition at line \fB639\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "long SetAirCraft (long AirCraftNumber)"

.PP
Definition at line \fB225\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "long SetNewAirCraft ()"

.PP
Definition at line \fB208\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void SetNewFireNumberForAirAttack (long OldFireNum, long NewFireNum)"

.PP
Definition at line \fB515\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void SetNewFireNumberForGroupAttack (long OldFireNum, long NewFireNum)"

.PP
Definition at line \fB855\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void SetNumAirAttacks (long NumAtk)"

.PP
Definition at line \fB254\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void SetNumAirCraft (long NumCraft)"

.PP
Definition at line \fB103\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void SetNumGroupAttacks (long NumGroups)"

.PP
Definition at line \fB872\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "long SetupAirAttack (long AirCraftNumber, long CoverageLevel, long Duration, double * startpoint)"

.PP
Definition at line \fB259\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "long SetupGroupAirAttack (long AirCraftNumber, long CoverageLevel, long Duration, double * line, long FireNum, char * GroupName)"

.PP
Definition at line \fB592\fP of file \fBfsairatk\&.cpp\fP\&.
.SS "void WriteAirAttackLog (\fBAirAttackData\fP * atk)"

.PP
Definition at line \fB539\fP of file \fBfsairatk\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
