.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwaccl.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwaccl.h
.SH SYNOPSIS
.br
.PP
\fR#include 'fsx4\&.hpp'\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAccelData\fP"
.br
.ti -1c
.RI "struct \fBTTransAccelData\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
