.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwutil.cpp" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwutil.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'fsglbvar\&.h'\fP
.br
\fR#include 'fsxwattk\&.h'\fP
.br
\fR#include 'fsxpfront\&.h'\fP
.br
\fR#include 'fsairatk\&.h'\fP
.br
\fR#include 'fsxsync\&.h'\fP
.br
\fR#include 'vec\&.h'\fP
.br
\fR#include 'rand2\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <omp\&.h>\fP
.br
\fR#include 'TimeCounter\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBPI\fP = acos(\-1\&.0)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const double PI = acos(\-1\&.0)"

.PP
Definition at line \fB42\fP of file \fBfsxwutil\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
