.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwaccl.cpp" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/fsxwaccl.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'fsxwaccl\&.h'\fP
.br
\fR#include 'ftestrc\&.h'\fP
.br
\fR#include 'fsxw\&.hpp'\fP
.br
\fR#include 'fsglbvar\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG90\fP   2\&.30259"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAcceleration\fP \fBAccelConst\fP"
.br
.ti -1c
.RI "bool \fBACCEL_ON\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOG90   2\&.30259"

.PP
Definition at line \fB30\fP of file \fBfsxwaccl\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "bool ACCEL_ON\fR [extern]\fP"

.SS "\fBAcceleration\fP AccelConst\fR [extern]\fP"

.PP
Definition at line \fB36\fP of file \fBfsxwmech\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
