.TH "GraphData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsdattyp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGraphData\fP ()"
.br
.ti -1c
.RI "\fB~GraphData\fP ()"
.br
.ti -1c
.RI "void \fBReSet\fP ()"
.br
.ti -1c
.RI "void \fBReAllocData\fP ()"
.br
.ti -1c
.RI "double \fBGetHoriz\fP (long Num)"
.br
.ti -1c
.RI "double \fBGetSlope\fP (long Num)"
.br
.ti -1c
.RI "void \fBSetData\fP (double Horiz, double Slope)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBDataMax\fP"
.br
.ti -1c
.RI "double \fBDataMin\fP"
.br
.ti -1c
.RI "long \fBnumber\fP"
.br
.ti -1c
.RI "long \fBnumarrays\fP"
.br
.ti -1c
.RI "\fBGraphStruct\fP * \fBGraph1\fP"
.br
.ti -1c
.RI "\fBGraphStruct\fP * \fBGraph2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB61\fP of file \fBfsdattyp\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GraphData::GraphData ()"

.SS "GraphData::~GraphData ()"

.SH "Member Function Documentation"
.PP 
.SS "double GraphData::GetHoriz (long Num)"

.SS "double GraphData::GetSlope (long Num)"

.SS "void GraphData::ReAllocData ()"

.SS "void GraphData::ReSet ()"

.SS "void GraphData::SetData (double Horiz, double Slope)"

.SH "Member Data Documentation"
.PP 
.SS "double GraphData::DataMax"

.PP
Definition at line \fB65\fP of file \fBfsdattyp\&.h\fP\&.
.SS "double GraphData::DataMin"

.PP
Definition at line \fB65\fP of file \fBfsdattyp\&.h\fP\&.
.SS "\fBGraphStruct\fP* GraphData::Graph1"

.PP
Definition at line \fB68\fP of file \fBfsdattyp\&.h\fP\&.
.SS "\fBGraphStruct\fP* GraphData::Graph2"

.PP
Definition at line \fB69\fP of file \fBfsdattyp\&.h\fP\&.
.SS "long GraphData::numarrays"

.PP
Definition at line \fB67\fP of file \fBfsdattyp\&.h\fP\&.
.SS "long GraphData::number"

.PP
Definition at line \fB66\fP of file \fBfsdattyp\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
