.TH "grounddata32bits" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
grounddata32bits
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBd\fP"
.br
.ti -1c
.RI "int16_t \fBw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB685\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int16_t grounddata32bits::d"

.PP
Definition at line \fB687\fP of file \fBfsglbvar\&.h\fP\&.
.SS "int16_t grounddata32bits::w"

.PP
Definition at line \fB688\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
