.TH "GroupAttackData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GroupAttackData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsairatk\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBSuspended\fP"
.br
.ti -1c
.RI "char \fBGroupName\fP [256]"
.br
.ti -1c
.RI "long \fBGroupAttackNumber\fP"
.br
.ti -1c
.RI "long \fBDirection\fP"
.br
.ti -1c
.RI "double * \fBIndirectLine\fP"
.br
.ti -1c
.RI "long \fBNumPoints\fP"
.br
.ti -1c
.RI "long \fBFireNumber\fP"
.br
.ti -1c
.RI "long * \fBCoverageLevel\fP"
.br
.ti -1c
.RI "long * \fBEffectiveDuration\fP"
.br
.ti -1c
.RI "long * \fBAircraftNumber\fP"
.br
.ti -1c
.RI "double * \fBWaitTime\fP"
.br
.ti -1c
.RI "long \fBNumCurrentAircraft\fP"
.br
.ti -1c
.RI "long \fBNumTotalAircraft\fP"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB98\fP of file \fBfsairatk\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long* GroupAttackData::AircraftNumber"

.PP
Definition at line \fB109\fP of file \fBfsairatk\&.h\fP\&.
.SS "long* GroupAttackData::CoverageLevel"

.PP
Definition at line \fB107\fP of file \fBfsairatk\&.h\fP\&.
.SS "long GroupAttackData::Direction"

.PP
Definition at line \fB103\fP of file \fBfsairatk\&.h\fP\&.
.SS "long* GroupAttackData::EffectiveDuration"

.PP
Definition at line \fB108\fP of file \fBfsairatk\&.h\fP\&.
.SS "long GroupAttackData::FireNumber"

.PP
Definition at line \fB106\fP of file \fBfsairatk\&.h\fP\&.
.SS "long GroupAttackData::GroupAttackNumber"

.PP
Definition at line \fB102\fP of file \fBfsairatk\&.h\fP\&.
.SS "char GroupAttackData::GroupName[256]"

.PP
Definition at line \fB101\fP of file \fBfsairatk\&.h\fP\&.
.SS "double* GroupAttackData::IndirectLine"

.PP
Definition at line \fB104\fP of file \fBfsairatk\&.h\fP\&.
.SS "void* GroupAttackData::next"

.PP
Definition at line \fB113\fP of file \fBfsairatk\&.h\fP\&.
.SS "long GroupAttackData::NumCurrentAircraft"

.PP
Definition at line \fB111\fP of file \fBfsairatk\&.h\fP\&.
.SS "long GroupAttackData::NumPoints"

.PP
Definition at line \fB105\fP of file \fBfsairatk\&.h\fP\&.
.SS "long GroupAttackData::NumTotalAircraft"

.PP
Definition at line \fB112\fP of file \fBfsairatk\&.h\fP\&.
.SS "long GroupAttackData::Suspended"

.PP
Definition at line \fB100\fP of file \fBfsairatk\&.h\fP\&.
.SS "double* GroupAttackData::WaitTime"

.PP
Definition at line \fB110\fP of file \fBfsairatk\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
