.TH "headdata2" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headdata2
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBCrownFuels\fP"
.br
.ti -1c
.RI "long \fBlatitude\fP"
.br
.ti -1c
.RI "double \fBloeast\fP"
.br
.ti -1c
.RI "double \fBhieast\fP"
.br
.ti -1c
.RI "double \fBlonorth\fP"
.br
.ti -1c
.RI "double \fBhinorth\fP"
.br
.ti -1c
.RI "long \fBloelev\fP"
.br
.ti -1c
.RI "long \fBhielev\fP"
.br
.ti -1c
.RI "long \fBnumeast\fP"
.br
.ti -1c
.RI "long \fBnumnorth\fP"
.br
.ti -1c
.RI "double \fBEastUtm\fP"
.br
.ti -1c
.RI "double \fBWestUtm\fP"
.br
.ti -1c
.RI "double \fBNorthUtm\fP"
.br
.ti -1c
.RI "double \fBSouthUtm\fP"
.br
.ti -1c
.RI "long \fBGridUnits\fP"
.br
.ti -1c
.RI "double \fBXResol\fP"
.br
.ti -1c
.RI "double \fBYResol\fP"
.br
.ti -1c
.RI "short \fBEUnits\fP"
.br
.ti -1c
.RI "short \fBSUnits\fP"
.br
.ti -1c
.RI "short \fBAUnits\fP"
.br
.ti -1c
.RI "short \fBFOptions\fP"
.br
.ti -1c
.RI "short \fBCUnits\fP"
.br
.ti -1c
.RI "short \fBHUnits\fP"
.br
.ti -1c
.RI "short \fBBUnits\fP"
.br
.ti -1c
.RI "short \fBPUnits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB556\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "short headdata2::AUnits"

.PP
Definition at line \fB577\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata2::BUnits"

.PP
Definition at line \fB581\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata2::CrownFuels"

.PP
Definition at line \fB558\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata2::CUnits"

.PP
Definition at line \fB579\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::EastUtm"

.PP
Definition at line \fB568\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata2::EUnits"

.PP
Definition at line \fB575\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata2::FOptions"

.PP
Definition at line \fB578\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata2::GridUnits"

.PP
Definition at line \fB572\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::hieast"

.PP
Definition at line \fB561\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata2::hielev"

.PP
Definition at line \fB565\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::hinorth"

.PP
Definition at line \fB563\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata2::HUnits"

.PP
Definition at line \fB580\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata2::latitude"

.PP
Definition at line \fB559\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::loeast"

.PP
Definition at line \fB560\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata2::loelev"

.PP
Definition at line \fB564\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::lonorth"

.PP
Definition at line \fB562\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::NorthUtm"

.PP
Definition at line \fB570\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata2::numeast"

.PP
Definition at line \fB566\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long headdata2::numnorth"

.PP
Definition at line \fB567\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata2::PUnits"

.PP
Definition at line \fB582\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::SouthUtm"

.PP
Definition at line \fB571\fP of file \fBfsglbvar\&.h\fP\&.
.SS "short headdata2::SUnits"

.PP
Definition at line \fB576\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::WestUtm"

.PP
Definition at line \fB569\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::XResol"

.PP
Definition at line \fB573\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double headdata2::YResol"

.PP
Definition at line \fB574\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
