.TH "NewGroundResources" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewGroundResources
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tempatk\&.h>\fP
.PP
Inherits TDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewGroundResources\fP (TWindow *parent, const char *resID, char *name)"
.br
.ti -1c
.RI "\fB~NewGroundResources\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB55\fP of file \fBtempatk\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NewGroundResources::NewGroundResources (TWindow * parent, const char * resID, char * name)"

.SS "NewGroundResources::~NewGroundResources ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
