.TH "RingBurn" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RingBurn
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxpfront\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRingBurn\fP ()"
.br
.ti -1c
.RI "\fB~RingBurn\fP ()"
.br
.ti -1c
.RI "void \fBSetRange\fP (\fBFireRing\fP *ring, long FireNum, long begin, long end)"
.br
.ti -1c
.RI "\fBX_HANDLE\fP \fBStartBurnThread\fP (long ID)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBThreadStarted\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB168\fP of file \fBfsxpfront\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RingBurn::RingBurn ()"

.PP
Definition at line \fB501\fP of file \fBfsxpfront\&.cpp\fP\&.
.SS "RingBurn::~RingBurn ()"

.PP
Definition at line \fB511\fP of file \fBfsxpfront\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void RingBurn::SetRange (\fBFireRing\fP * ring, long FireNum, long begin, long end)"

.PP
Definition at line \fB518\fP of file \fBfsxpfront\&.cpp\fP\&.
.SS "\fBX_HANDLE\fP RingBurn::StartBurnThread (long ID)"

.PP
Definition at line \fB527\fP of file \fBfsxpfront\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool RingBurn::ThreadStarted"

.PP
Definition at line \fB195\fP of file \fBfsxpfront\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
