.TH "RingStruct" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RingStruct
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxpfront\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBStructNum\fP"
.br
.ti -1c
.RI "long \fBNumFireRings\fP"
.br
.ti -1c
.RI "\fBFireRing\fP \fBfirering\fP [\fBRINGS_PER_STRUCT\fP]"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB159\fP of file \fBfsxpfront\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFireRing\fP RingStruct::firering[\fBRINGS_PER_STRUCT\fP]"

.PP
Definition at line \fB163\fP of file \fBfsxpfront\&.h\fP\&.
.SS "void* RingStruct::next"

.PP
Definition at line \fB164\fP of file \fBfsxpfront\&.h\fP\&.
.SS "long RingStruct::NumFireRings"

.PP
Definition at line \fB162\fP of file \fBfsxpfront\&.h\fP\&.
.SS "long RingStruct::StructNum"

.PP
Definition at line \fB161\fP of file \fBfsxpfront\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
