.TH "shape_tree_node" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shape_tree_node
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shapefil\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBadfBoundsMin\fP [4]"
.br
.ti -1c
.RI "double \fBadfBoundsMax\fP [4]"
.br
.ti -1c
.RI "int \fBnShapeCount\fP"
.br
.ti -1c
.RI "int * \fBpanShapeIds\fP"
.br
.ti -1c
.RI "\fBSHPObject\fP ** \fBpapsShapeObj\fP"
.br
.ti -1c
.RI "int \fBnSubNodes\fP"
.br
.ti -1c
.RI "struct \fBshape_tree_node\fP * \fBapsSubNode\fP [\fBMAX_SUBNODE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB280\fP of file \fBshapefil\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double shape_tree_node::adfBoundsMax[4]"

.PP
Definition at line \fB284\fP of file \fBshapefil\&.h\fP\&.
.SS "double shape_tree_node::adfBoundsMin[4]"

.PP
Definition at line \fB283\fP of file \fBshapefil\&.h\fP\&.
.SS "struct \fBshape_tree_node\fP* shape_tree_node::apsSubNode[\fBMAX_SUBNODE\fP]"

.PP
Definition at line \fB293\fP of file \fBshapefil\&.h\fP\&.
.SS "int shape_tree_node::nShapeCount"

.PP
Definition at line \fB288\fP of file \fBshapefil\&.h\fP\&.
.SS "int shape_tree_node::nSubNodes"

.PP
Definition at line \fB292\fP of file \fBshapefil\&.h\fP\&.
.SS "int* shape_tree_node::panShapeIds"

.PP
Definition at line \fB289\fP of file \fBshapefil\&.h\fP\&.
.SS "\fBSHPObject\fP** shape_tree_node::papsShapeObj"

.PP
Definition at line \fB290\fP of file \fBshapefil\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
