.TH "C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/shapefil.h" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tolk1/Dropbox/SDSC/WiFire/farsite-devAPI/src2/shapefil.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSHPInfo\fP"
.br
.ti -1c
.RI "struct \fBSHPObject\fP"
.br
.ti -1c
.RI "struct \fBshape_tree_node\fP"
.br
.ti -1c
.RI "struct \fBSHPTree\fP"
.br
.ti -1c
.RI "struct \fBDBFInfo\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSHPAPI_CALL\fP"
.br
.ti -1c
.RI "#define \fBSHPAPI_CALL1\fP(x)   * \fBSHPAPI_CALL\fP"
.br
.ti -1c
.RI "#define \fBTRIM_DBF_WHITESPACE\fP"
.br
.ti -1c
.RI "#define \fBDISABLE_MULTIPATCH_MEASURE\fP"
.br
.ti -1c
.RI "#define \fBSHPT_NULL\fP   0"
.br
.ti -1c
.RI "#define \fBSHPT_POINT\fP   1"
.br
.ti -1c
.RI "#define \fBSHPT_ARC\fP   3"
.br
.ti -1c
.RI "#define \fBSHPT_POLYGON\fP   5"
.br
.ti -1c
.RI "#define \fBSHPT_MULTIPOINT\fP   8"
.br
.ti -1c
.RI "#define \fBSHPT_POINTZ\fP   11"
.br
.ti -1c
.RI "#define \fBSHPT_ARCZ\fP   13"
.br
.ti -1c
.RI "#define \fBSHPT_POLYGONZ\fP   15"
.br
.ti -1c
.RI "#define \fBSHPT_MULTIPOINTZ\fP   18"
.br
.ti -1c
.RI "#define \fBSHPT_POINTM\fP   21"
.br
.ti -1c
.RI "#define \fBSHPT_ARCM\fP   23"
.br
.ti -1c
.RI "#define \fBSHPT_POLYGONM\fP   25"
.br
.ti -1c
.RI "#define \fBSHPT_MULTIPOINTM\fP   28"
.br
.ti -1c
.RI "#define \fBSHPT_MULTIPATCH\fP   31"
.br
.ti -1c
.RI "#define \fBSHPP_TRISTRIP\fP   0"
.br
.ti -1c
.RI "#define \fBSHPP_TRIFAN\fP   1"
.br
.ti -1c
.RI "#define \fBSHPP_OUTERRING\fP   2"
.br
.ti -1c
.RI "#define \fBSHPP_INNERRING\fP   3"
.br
.ti -1c
.RI "#define \fBSHPP_FIRSTRING\fP   4"
.br
.ti -1c
.RI "#define \fBSHPP_RING\fP   5"
.br
.ti -1c
.RI "#define \fBMAX_SUBNODE\fP   4"
.br
.ti -1c
.RI "#define \fBXBASE_FLDHDR_SZ\fP   32"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSHPInfo\fP * \fBSHPHandle\fP"
.br
.ti -1c
.RI "typedef struct \fBshape_tree_node\fP \fBSHPTreeNode\fP"
.br
.ti -1c
.RI "typedef \fBDBFInfo\fP * \fBDBFHandle\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDBFFieldType\fP { \fBFTString\fP, \fBFTInteger\fP, \fBFTDouble\fP, \fBFTInvalid\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSHPHandle\fP \fBSHPAPI_CALL\fP \fBSHPOpen\fP (const char *pszShapeFile, const char *pszAccess)"
.br
.ti -1c
.RI "\fBSHPHandle\fP \fBSHPAPI_CALL\fP \fBSHPCreate\fP (const char *pszShapeFile, int nShapeType)"
.br
.ti -1c
.RI "void \fBSHPAPI_CALL\fP \fBSHPGetInfo\fP (\fBSHPHandle\fP hSHP, int *pnEntities, int *pnShapeType, double *padfMinBound, double *padfMaxBound)"
.br
.ti -1c
.RI "\fBSHPObject\fP \fBSHPAPI_CALL1\fP * \fBSHPReadObject\fP (\fBSHPHandle\fP hSHP, int iShape);int \fBSHPAPI_CALL\fP \fBSHPWriteObject\fP(\fBSHPHandle\fP hSHP, int iShape, \fBSHPObject\fP *psObject"
.br
.ti -1c
.RI "void \fBSHPAPI_CALL\fP \fBSHPDestroyObject\fP (\fBSHPObject\fP *psObject)"
.br
.ti -1c
.RI "void \fBSHPAPI_CALL\fP \fBSHPComputeExtents\fP (\fBSHPObject\fP *psObject)"
.br
.ti -1c
.RI "\fBSHPObject\fP \fBSHPAPI_CALL1\fP * \fBSHPCreateObject\fP (int \fBnSHPType\fP, int \fBnShapeId\fP, int nParts, int *panPartStart, int *panPartType, int \fBnVertices\fP, double *padfX, double *padfY, double *padfZ, double *padfM);\fBSHPObject\fP \fBSHPAPI_CALL1\fP(*) \fBSHPCreateSimpleObject\fP(int \fBnSHPType\fP, int \fBnVertices\fP, double *padfX, double *padfY, double *padfZ"
.br
.ti -1c
.RI "void \fBSHPAPI_CALL\fP \fBSHPClose\fP (\fBSHPHandle\fP hSHP)"
.br
.ti -1c
.RI "const char \fBSHPAPI_CALL1\fP * \fBSHPTypeName\fP (int \fBnSHPType\fP);const char \fBSHPAPI_CALL1\fP(*) \fBSHPPartTypeName\fP(int nPartType"
.br
.ti -1c
.RI "\fBSHPTree\fP \fBSHPAPI_CALL1\fP * \fBSHPCreateTree\fP (\fBSHPHandle\fP hSHP, int nDimension, int nMaxDepth, double *padfBoundsMin, double *padfBoundsMax);void \fBSHPAPI_CALL\fP SHPDestroyTree(\fBSHPTree\fP *hTree"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBSHPWriteTree\fP (\fBSHPTree\fP *hTree, const char *pszFilename)"
.br
.ti -1c
.RI "\fBSHPTree\fP \fBSHPAPI_CALL\fP \fBSHPReadTree\fP (const char *pszFilename)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBSHPTreeAddObject\fP (\fBSHPTree\fP *hTree, \fBSHPObject\fP *psObject)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBSHPTreeAddShapeId\fP (\fBSHPTree\fP *hTree, \fBSHPObject\fP *psObject)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBSHPTreeRemoveShapeId\fP (\fBSHPTree\fP *hTree, int \fBnShapeId\fP)"
.br
.ti -1c
.RI "void \fBSHPAPI_CALL\fP \fBSHPTreeTrimExtraNodes\fP (\fBSHPTree\fP *hTree)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL1\fP * \fBSHPTreeFindLikelyShapes\fP (\fBSHPTree\fP *hTree, double *padfBoundsMin, double *padfBoundsMax, int *);int \fBSHPAPI_CALL\fP SHPCheckBoundsOverlap(double *, double *, double *, double *, int"
.br
.ti -1c
.RI "\fBDBFHandle\fP \fBSHPAPI_CALL\fP \fBDBFOpen\fP (const char *pszDBFFile, const char *pszAccess)"
.br
.ti -1c
.RI "\fBDBFHandle\fP \fBSHPAPI_CALL\fP \fBDBFCreate\fP (const char *pszDBFFile)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBDBFGetFieldCount\fP (\fBDBFHandle\fP psDBF)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBDBFGetRecordCount\fP (\fBDBFHandle\fP psDBF)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBDBFAddField\fP (\fBDBFHandle\fP hDBF, const char *pszFieldName, \fBDBFFieldType\fP eType, int nWidth, int nDecimals)"
.br
.ti -1c
.RI "\fBDBFFieldType\fP \fBSHPAPI_CALL\fP \fBDBFGetFieldInfo\fP (\fBDBFHandle\fP psDBF, int iField, char *pszFieldName, int *pnWidth, int *pnDecimals)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBDBFGetFieldIndex\fP (\fBDBFHandle\fP psDBF, const char *pszFieldName)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBDBFReadIntegerAttribute\fP (\fBDBFHandle\fP hDBF, int iShape, int iField)"
.br
.ti -1c
.RI "double \fBSHPAPI_CALL\fP \fBDBFReadDoubleAttribute\fP (\fBDBFHandle\fP hDBF, int iShape, int iField)"
.br
.ti -1c
.RI "const char \fBSHPAPI_CALL1\fP * \fBDBFReadStringAttribute\fP (\fBDBFHandle\fP hDBF, int iShape, int iField);int \fBSHPAPI_CALL\fP \fBDBFIsAttributeNULL\fP(\fBDBFHandle\fP hDBF, int iShape, int iField"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBDBFWriteIntegerAttribute\fP (\fBDBFHandle\fP hDBF, int iShape, int iField, int nFieldValue)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBDBFWriteDoubleAttribute\fP (\fBDBFHandle\fP hDBF, int iShape, int iField, double dFieldValue)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBDBFWriteStringAttribute\fP (\fBDBFHandle\fP hDBF, int iShape, int iField, const char *pszFieldValue)"
.br
.ti -1c
.RI "int \fBSHPAPI_CALL\fP \fBDBFWriteNULLAttribute\fP (\fBDBFHandle\fP hDBF, int iShape, int iField)"
.br
.ti -1c
.RI "const char \fBSHPAPI_CALL1\fP * \fBDBFReadTuple\fP (\fBDBFHandle\fP psDBF, int hEntity);int \fBSHPAPI_CALL\fP \fBDBFWriteTuple\fP(\fBDBFHandle\fP psDBF, int hEntity, void *pRawTuple"
.br
.ti -1c
.RI "\fBDBFHandle\fP \fBSHPAPI_CALL\fP \fBDBFCloneEmpty\fP (\fBDBFHandle\fP psDBF, const char *pszFilename)"
.br
.ti -1c
.RI "void \fBSHPAPI_CALL\fP \fBDBFClose\fP (\fBDBFHandle\fP hDBF)"
.br
.ti -1c
.RI "char \fBSHPAPI_CALL\fP \fBDBFGetNativeFieldType\fP (\fBDBFHandle\fP hDBF, int iField)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DISABLE_MULTIPATCH_MEASURE"

.PP
Definition at line \fB153\fP of file \fBshapefil\&.h\fP\&.
.SS "#define MAX_SUBNODE   4"

.PP
Definition at line \fB278\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPAPI_CALL"

.PP
Definition at line \fB133\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPAPI_CALL1(x)   * \fBSHPAPI_CALL\fP"

.PP
Definition at line \fB136\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPP_FIRSTRING   4"

.PP
Definition at line \fB208\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPP_INNERRING   3"

.PP
Definition at line \fB207\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPP_OUTERRING   2"

.PP
Definition at line \fB206\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPP_RING   5"

.PP
Definition at line \fB209\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPP_TRIFAN   1"

.PP
Definition at line \fB205\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPP_TRISTRIP   0"

.PP
Definition at line \fB204\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_ARC   3"

.PP
Definition at line \fB185\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_ARCM   23"

.PP
Definition at line \fB193\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_ARCZ   13"

.PP
Definition at line \fB189\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_MULTIPATCH   31"

.PP
Definition at line \fB196\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_MULTIPOINT   8"

.PP
Definition at line \fB187\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_MULTIPOINTM   28"

.PP
Definition at line \fB195\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_MULTIPOINTZ   18"

.PP
Definition at line \fB191\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_NULL   0"

.PP
Definition at line \fB183\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_POINT   1"

.PP
Definition at line \fB184\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_POINTM   21"

.PP
Definition at line \fB192\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_POINTZ   11"

.PP
Definition at line \fB188\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_POLYGON   5"

.PP
Definition at line \fB186\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_POLYGONM   25"

.PP
Definition at line \fB194\fP of file \fBshapefil\&.h\fP\&.
.SS "#define SHPT_POLYGONZ   15"

.PP
Definition at line \fB190\fP of file \fBshapefil\&.h\fP\&.
.SS "#define TRIM_DBF_WHITESPACE"

.PP
Definition at line \fB146\fP of file \fBshapefil\&.h\fP\&.
.SS "#define XBASE_FLDHDR_SZ   32"

.PP
Definition at line \fB363\fP of file \fBshapefil\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBDBFInfo\fP* \fBDBFHandle\fP"

.PP
Definition at line \fB353\fP of file \fBshapefil\&.h\fP\&.
.SS "typedef \fBSHPInfo\fP* \fBSHPHandle\fP"

.PP
Definition at line \fB178\fP of file \fBshapefil\&.h\fP\&.
.SS "typedef struct \fBshape_tree_node\fP \fBSHPTreeNode\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDBFFieldType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFTString \fP\fP
.TP
\fB\fIFTInteger \fP\fP
.TP
\fB\fIFTDouble \fP\fP
.TP
\fB\fIFTInvalid \fP\fP
.PP
Definition at line \fB355\fP of file \fBshapefil\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int \fBSHPAPI_CALL\fP DBFAddField (\fBDBFHandle\fP hDBF, const char * pszFieldName, \fBDBFFieldType\fP eType, int nWidth, int nDecimals)"

.PP
Definition at line \fB572\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "\fBDBFHandle\fP \fBSHPAPI_CALL\fP DBFCloneEmpty (\fBDBFHandle\fP psDBF, const char * pszFilename)"

.PP
Definition at line \fB1233\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "void \fBSHPAPI_CALL\fP DBFClose (\fBDBFHandle\fP hDBF)"

.PP
Definition at line \fB428\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "\fBDBFHandle\fP \fBSHPAPI_CALL\fP DBFCreate (const char * pszDBFFile)"

.PP
Definition at line \fB494\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "int \fBSHPAPI_CALL\fP DBFGetFieldCount (\fBDBFHandle\fP psDBF)"

.PP
Definition at line \fB860\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "int \fBSHPAPI_CALL\fP DBFGetFieldIndex (\fBDBFHandle\fP psDBF, const char * pszFieldName)"

.PP
Definition at line \fB1346\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "\fBDBFFieldType\fP \fBSHPAPI_CALL\fP DBFGetFieldInfo (\fBDBFHandle\fP psDBF, int iField, char * pszFieldName, int * pnWidth, int * pnDecimals)"

.PP
Definition at line \fB882\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "char \fBSHPAPI_CALL\fP DBFGetNativeFieldType (\fBDBFHandle\fP hDBF, int iField)"

.PP
Definition at line \fB1314\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "int \fBSHPAPI_CALL\fP DBFGetRecordCount (\fBDBFHandle\fP psDBF)"

.PP
Definition at line \fB871\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "\fBDBFHandle\fP \fBSHPAPI_CALL\fP DBFOpen (const char * pszDBFFile, const char * pszAccess)"

.PP
Definition at line \fB289\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "double \fBSHPAPI_CALL\fP DBFReadDoubleAttribute (\fBDBFHandle\fP hDBF, int iShape, int iField)"

.PP
Definition at line \fB792\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "int \fBSHPAPI_CALL\fP DBFReadIntegerAttribute (\fBDBFHandle\fP hDBF, int iShape, int iField)"

.PP
Definition at line \fB773\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "const char \fBSHPAPI_CALL1\fP * DBFReadStringAttribute (\fBDBFHandle\fP hDBF, int iShape, int iField)"

.SS "const char \fBSHPAPI_CALL1\fP * DBFReadTuple (\fBDBFHandle\fP psDBF, int hEntity)"

.SS "int \fBSHPAPI_CALL\fP DBFWriteDoubleAttribute (\fBDBFHandle\fP hDBF, int iShape, int iField, double dFieldValue)"

.PP
Definition at line \fB1077\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "int \fBSHPAPI_CALL\fP DBFWriteIntegerAttribute (\fBDBFHandle\fP hDBF, int iShape, int iField, int nFieldValue)"

.PP
Definition at line \fB1089\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "int \fBSHPAPI_CALL\fP DBFWriteNULLAttribute (\fBDBFHandle\fP hDBF, int iShape, int iField)"

.PP
Definition at line \fB1115\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "int \fBSHPAPI_CALL\fP DBFWriteStringAttribute (\fBDBFHandle\fP hDBF, int iShape, int iField, const char * pszFieldValue)"

.PP
Definition at line \fB1103\fP of file \fBdbfopen\&.cpp\fP\&.
.SS "void \fBSHPAPI_CALL\fP SHPClose (\fBSHPHandle\fP hSHP)"

.PP
Definition at line \fB587\fP of file \fBshpopen\&.cpp\fP\&.
.SS "void \fBSHPAPI_CALL\fP SHPComputeExtents (\fBSHPObject\fP * psObject)"

.PP
Definition at line \fB786\fP of file \fBshpopen\&.cpp\fP\&.
.SS "\fBSHPHandle\fP \fBSHPAPI_CALL\fP SHPCreate (const char * pszShapeFile, int nShapeType)"

.PP
Definition at line \fB649\fP of file \fBshpopen\&.cpp\fP\&.
.SS "\fBSHPObject\fP \fBSHPAPI_CALL1\fP * SHPCreateObject (int nSHPType, int nShapeId, int nParts, int * panPartStart, int * panPartType, int nVertices, double * padfX, double * padfY, double * padfZ, double * padfM)"

.SS "\fBSHPTree\fP \fBSHPAPI_CALL1\fP * SHPCreateTree (\fBSHPHandle\fP hSHP, int nDimension, int nMaxDepth, double * padfBoundsMin, double * padfBoundsMax)"

.SS "void \fBSHPAPI_CALL\fP SHPDestroyObject (\fBSHPObject\fP * psObject)"

.PP
Definition at line \fB1760\fP of file \fBshpopen\&.cpp\fP\&.
.SS "void \fBSHPAPI_CALL\fP SHPGetInfo (\fBSHPHandle\fP hSHP, int * pnEntities, int * pnShapeType, double * padfMinBound, double * padfMaxBound)"

.PP
Definition at line \fB622\fP of file \fBshpopen\&.cpp\fP\&.
.SS "\fBSHPHandle\fP \fBSHPAPI_CALL\fP SHPOpen (const char * pszShapeFile, const char * pszAccess)"

.PP
Definition at line \fB356\fP of file \fBshpopen\&.cpp\fP\&.
.SS "\fBSHPObject\fP \fBSHPAPI_CALL1\fP * SHPReadObject (\fBSHPHandle\fP hSHP, int iShape)"

.SS "\fBSHPTree\fP \fBSHPAPI_CALL\fP SHPReadTree (const char * pszFilename)"

.SS "int \fBSHPAPI_CALL\fP SHPTreeAddObject (\fBSHPTree\fP * hTree, \fBSHPObject\fP * psObject)"

.SS "int \fBSHPAPI_CALL\fP SHPTreeAddShapeId (\fBSHPTree\fP * hTree, \fBSHPObject\fP * psObject)"

.SS "int \fBSHPAPI_CALL1\fP * SHPTreeFindLikelyShapes (\fBSHPTree\fP * hTree, double * padfBoundsMin, double * padfBoundsMax, int *)"

.SS "int \fBSHPAPI_CALL\fP SHPTreeRemoveShapeId (\fBSHPTree\fP * hTree, int nShapeId)"

.SS "void \fBSHPAPI_CALL\fP SHPTreeTrimExtraNodes (\fBSHPTree\fP * hTree)"

.SS "const char \fBSHPAPI_CALL1\fP * SHPTypeName (int nSHPType) const"

.PP
Definition at line \fB1690\fP of file \fBshpopen\&.cpp\fP\&.
.SS "int \fBSHPAPI_CALL\fP SHPWriteTree (\fBSHPTree\fP * hTree, const char * pszFilename)"

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
