.TH "SHPInfo" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SHPInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shapefil\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBfpSHP\fP"
.br
.ti -1c
.RI "FILE * \fBfpSHX\fP"
.br
.ti -1c
.RI "int \fBnShapeType\fP"
.br
.ti -1c
.RI "int \fBnFileSize\fP"
.br
.ti -1c
.RI "int \fBnRecords\fP"
.br
.ti -1c
.RI "int \fBnMaxRecords\fP"
.br
.ti -1c
.RI "int * \fBpanRecOffset\fP"
.br
.ti -1c
.RI "int * \fBpanRecSize\fP"
.br
.ti -1c
.RI "double \fBadBoundsMin\fP [4]"
.br
.ti -1c
.RI "double \fBadBoundsMax\fP [4]"
.br
.ti -1c
.RI "int \fBbUpdated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB158\fP of file \fBshapefil\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double SHPInfo::adBoundsMax[4]"

.PP
Definition at line \fB173\fP of file \fBshapefil\&.h\fP\&.
.SS "double SHPInfo::adBoundsMin[4]"

.PP
Definition at line \fB172\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPInfo::bUpdated"

.PP
Definition at line \fB175\fP of file \fBshapefil\&.h\fP\&.
.SS "FILE* SHPInfo::fpSHP"

.PP
Definition at line \fB160\fP of file \fBshapefil\&.h\fP\&.
.SS "FILE* SHPInfo::fpSHX"

.PP
Definition at line \fB161\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPInfo::nFileSize"

.PP
Definition at line \fB165\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPInfo::nMaxRecords"

.PP
Definition at line \fB168\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPInfo::nRecords"

.PP
Definition at line \fB167\fP of file \fBshapefil\&.h\fP\&.
.SS "int SHPInfo::nShapeType"

.PP
Definition at line \fB163\fP of file \fBshapefil\&.h\fP\&.
.SS "int* SHPInfo::panRecOffset"

.PP
Definition at line \fB169\fP of file \fBshapefil\&.h\fP\&.
.SS "int* SHPInfo::panRecSize"

.PP
Definition at line \fB170\fP of file \fBshapefil\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
