.TH "streamdata" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
streamdata
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwtr\fP"
.br
.ti -1c
.RI "int \fBwnd\fP"
.br
.ti -1c
.RI "int \fBall\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB306\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int streamdata::all"

.PP
Definition at line \fB310\fP of file \fBfsglbvar\&.h\fP\&.
.SS "int streamdata::wnd"

.PP
Definition at line \fB309\fP of file \fBfsglbvar\&.h\fP\&.
.SS "int streamdata::wtr"

.PP
Definition at line \fB308\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
