.TH "Themes" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Themes
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBID\fP"
.br
.ti -1c
.RI "\fBRasterTheme\fP * \fBtheme\fP"
.br
.ti -1c
.RI "void * \fBlast\fP"
.br
.ti -1c
.RI "void * \fBnext\fP"
.br
.ti -1c
.RI "long \fBChanged\fP"
.br
.ti -1c
.RI "bool \fBSelected\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB263\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long Themes::Changed"

.PP
Definition at line \fB269\fP of file \fBfsglbvar\&.h\fP\&.
.SS "long Themes::ID"

.PP
Definition at line \fB265\fP of file \fBfsglbvar\&.h\fP\&.
.SS "void* Themes::last"

.PP
Definition at line \fB267\fP of file \fBfsglbvar\&.h\fP\&.
.SS "void* Themes::next"

.PP
Definition at line \fB268\fP of file \fBfsglbvar\&.h\fP\&.
.SS "bool Themes::Selected"

.PP
Definition at line \fB270\fP of file \fBfsglbvar\&.h\fP\&.
.SS "\fBRasterTheme\fP* Themes::theme"

.PP
Definition at line \fB266\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
