.TH "TimeStruct" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeStruct
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsdattyp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBMonth\fP"
.br
.ti -1c
.RI "long \fBDay\fP"
.br
.ti -1c
.RI "long \fBHour\fP"
.br
.ti -1c
.RI "long \fBMin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBfsdattyp\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "long TimeStruct::Day"

.PP
Definition at line \fB31\fP of file \fBfsdattyp\&.h\fP\&.
.SS "long TimeStruct::Hour"

.PP
Definition at line \fB32\fP of file \fBfsdattyp\&.h\fP\&.
.SS "long TimeStruct::Min"

.PP
Definition at line \fB33\fP of file \fBfsdattyp\&.h\fP\&.
.SS "long TimeStruct::Month"

.PP
Definition at line \fB30\fP of file \fBfsdattyp\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
