.TH "TransEnvtMap" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransEnvtMap
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransEnvtMap\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBFileName\fP [256]"
.br
.ti -1c
.RI "int \fBone\fP"
.br
.ti -1c
.RI "int \fBten\fP"
.br
.ti -1c
.RI "int \fBhund\fP"
.br
.ti -1c
.RI "int \fBthou\fP"
.br
.ti -1c
.RI "int \fBduff\fP"
.br
.ti -1c
.RI "int \fBmfw\fP"
.br
.ti -1c
.RI "int \fBtemp\fP"
.br
.ti -1c
.RI "int \fBhumid\fP"
.br
.ti -1c
.RI "int \fBsolar\fP"
.br
.ti -1c
.RI "int \fBx1\fP"
.br
.ti -1c
.RI "int \fBx2\fP"
.br
.ti -1c
.RI "int \fBx5\fP"
.br
.ti -1c
.RI "int \fBx10\fP"
.br
.ti -1c
.RI "int \fBx20\fP"
.br
.ti -1c
.RI "int \fBvp\fP"
.br
.ti -1c
.RI "int \fBnw\fP"
.br
.ti -1c
.RI "int \fBeng\fP"
.br
.ti -1c
.RI "int \fBmet\fP"
.br
.ti -1c
.RI "char \fBMo\fP [8]"
.br
.ti -1c
.RI "char \fBDy\fP [8]"
.br
.ti -1c
.RI "char \fBHr\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB888\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransEnvtMap::TransEnvtMap ()"

.SH "Member Data Documentation"
.PP 
.SS "int TransEnvtMap::duff"

.PP
Definition at line \fB891\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char TransEnvtMap::Dy[8]"

.PP
Definition at line \fB896\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::eng"

.PP
Definition at line \fB895\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char TransEnvtMap::FileName[256]"

.PP
Definition at line \fB890\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char TransEnvtMap::Hr[8]"

.PP
Definition at line \fB896\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::humid"

.PP
Definition at line \fB892\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::hund"

.PP
Definition at line \fB891\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::met"

.PP
Definition at line \fB895\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::mfw"

.PP
Definition at line \fB892\fP of file \fBfarsite\&.hpp\fP\&.
.SS "char TransEnvtMap::Mo[8]"

.PP
Definition at line \fB896\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::nw"

.PP
Definition at line \fB894\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::one"

.PP
Definition at line \fB891\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::solar"

.PP
Definition at line \fB892\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::temp"

.PP
Definition at line \fB892\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::ten"

.PP
Definition at line \fB891\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::thou"

.PP
Definition at line \fB891\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::vp"

.PP
Definition at line \fB894\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::x1"

.PP
Definition at line \fB893\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::x10"

.PP
Definition at line \fB893\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::x2"

.PP
Definition at line \fB893\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::x20"

.PP
Definition at line \fB893\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TransEnvtMap::x5"

.PP
Definition at line \fB893\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
