.TH "TTransAirData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransAirData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsairdlg\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransAirData\fP ()"
.br
.ti -1c
.RI "void \fBResetData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAirData\fP \fBDat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB57\fP of file \fBfsairdlg\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransAirData::TTransAirData ()"

.SH "Member Function Documentation"
.PP 
.SS "void TTransAirData::ResetData ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBAirData\fP TTransAirData::Dat"

.PP
Definition at line \fB59\fP of file \fBfsairdlg\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
