.TH "TTransWSData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TTransWSData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <farsite\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTTransWSData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBS1\fP"
.br
.ti -1c
.RI "int \fBS2\fP"
.br
.ti -1c
.RI "int \fBS3\fP"
.br
.ti -1c
.RI "int \fBS4\fP"
.br
.ti -1c
.RI "int \fBS5\fP"
.br
.ti -1c
.RI "int \fBM1\fP"
.br
.ti -1c
.RI "int \fBM2\fP"
.br
.ti -1c
.RI "int \fBM3\fP"
.br
.ti -1c
.RI "int \fBM4\fP"
.br
.ti -1c
.RI "int \fBM5\fP"
.br
.ti -1c
.RI "int \fBD1\fP"
.br
.ti -1c
.RI "int \fBD2\fP"
.br
.ti -1c
.RI "int \fBD3\fP"
.br
.ti -1c
.RI "int \fBD4\fP"
.br
.ti -1c
.RI "int \fBD5\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB45\fP of file \fBfarsite\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TTransWSData::TTransWSData ()"

.SH "Member Data Documentation"
.PP 
.SS "int TTransWSData::D1"

.PP
Definition at line \fB50\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::D2"

.PP
Definition at line \fB50\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::D3"

.PP
Definition at line \fB50\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::D4"

.PP
Definition at line \fB50\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::D5"

.PP
Definition at line \fB50\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::M1"

.PP
Definition at line \fB49\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::M2"

.PP
Definition at line \fB49\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::M3"

.PP
Definition at line \fB49\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::M4"

.PP
Definition at line \fB49\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::M5"

.PP
Definition at line \fB49\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::S1"

.PP
Definition at line \fB48\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::S2"

.PP
Definition at line \fB48\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::S3"

.PP
Definition at line \fB48\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::S4"

.PP
Definition at line \fB48\fP of file \fBfarsite\&.hpp\fP\&.
.SS "int TTransWSData::S5"

.PP
Definition at line \fB48\fP of file \fBfarsite\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
