.TH "VectorBarrier" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VectorBarrier
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsxwbar\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVectorBarrier\fP ()"
.br
.ti -1c
.RI "\fB~VectorBarrier\fP ()"
.br
.ti -1c
.RI "bool \fBAllocBarrier\fP (long VertNumber)"
.br
.ti -1c
.RI "void \fBSetBarrierVertex\fP (long NumVecs, double xpt, double ypt)"
.br
.ti -1c
.RI "void \fBBufferBarrier\fP (double DistanceMultiplier)"
.br
.ti -1c
.RI "bool \fBReBufferBarriers\fP ()"
.br
.ti -1c
.RI "bool \fBTransferBarrier\fP (long NumFire)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB34\fP of file \fBfsxwbar\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VectorBarrier::VectorBarrier ()"

.PP
Definition at line \fB38\fP of file \fBfsxwbar\&.cpp\fP\&.
.SS "VectorBarrier::~VectorBarrier ()"

.PP
Definition at line \fB47\fP of file \fBfsxwbar\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool VectorBarrier::AllocBarrier (long VertNumber)"

.PP
Definition at line \fB53\fP of file \fBfsxwbar\&.cpp\fP\&.
.SS "void VectorBarrier::BufferBarrier (double DistanceMultiplier)"

.PP
Definition at line \fB168\fP of file \fBfsxwbar\&.cpp\fP\&.
.SS "bool VectorBarrier::ReBufferBarriers ()"

.PP
Definition at line \fB272\fP of file \fBfsxwbar\&.cpp\fP\&.
.SS "void VectorBarrier::SetBarrierVertex (long NumVecs, double xpt, double ypt)"

.PP
Definition at line \fB85\fP of file \fBfsxwbar\&.cpp\fP\&.
.SS "bool VectorBarrier::TransferBarrier (long NumFire)"

.PP
Definition at line \fB378\fP of file \fBfsxwbar\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
