.TH "WeatherEdit" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WeatherEdit
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wwedits\&.h>\fP
.PP
Inherits TDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWeatherEdit\fP (TWindow *AParent, const char *resID, \fBTransWtrEdit\fP &ts, long StationNumber)"
.br
.ti -1c
.RI "\fB~WeatherEdit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB134\fP of file \fBwwedits\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WeatherEdit::WeatherEdit (TWindow * AParent, const char * resID, \fBTransWtrEdit\fP & ts, long StationNumber)"

.SS "WeatherEdit::~WeatherEdit ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
