.TH "WindEdit" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindEdit
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <wwedits\&.h>\fP
.PP
Inherits TDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindEdit\fP (TWindow *AParent, const char *resID, \fBTransWndEdit\fP &ts, long stationnumber)"
.br
.ti -1c
.RI "\fB~WindEdit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB65\fP of file \fBwwedits\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WindEdit::WindEdit (TWindow * AParent, const char * resID, \fBTransWndEdit\fP & ts, long stationnumber)"

.SS "WindEdit::~WindEdit ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
