.TH "WoodyData" 3 "farsite4P" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WoodyData
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fsglbvar\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBSurfaceAreaToVolume\fP"
.br
.ti -1c
.RI "double \fBLoad\fP"
.br
.ti -1c
.RI "double \fBHeatContent\fP"
.br
.ti -1c
.RI "double \fBDensity\fP"
.br
.ti -1c
.RI "double \fBFuelMoisture\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB961\fP of file \fBfsglbvar\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double WoodyData::Density"

.PP
Definition at line \fB966\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double WoodyData::FuelMoisture"

.PP
Definition at line \fB967\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double WoodyData::HeatContent"

.PP
Definition at line \fB965\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double WoodyData::Load"

.PP
Definition at line \fB964\fP of file \fBfsglbvar\&.h\fP\&.
.SS "double WoodyData::SurfaceAreaToVolume"

.PP
Definition at line \fB963\fP of file \fBfsglbvar\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for farsite4P from the source code\&.
