var hierarchy =
[
    [ "__attribute__", "struct____attribute____.html", null ],
    [ "AbsoluteBurnPeriod", "struct_absolute_burn_period.html", null ],
    [ "AccelConstants", "struct_accel_constants.html", null ],
    [ "AccelData", "struct_accel_data.html", null ],
    [ "Acceleration", "struct_acceleration.html", null ],
    [ "AirAttack", "class_air_attack.html", null ],
    [ "AirAttackData", "struct_air_attack_data.html", null ],
    [ "AirCraft", "struct_air_craft.html", null ],
    [ "AirData", "struct_air_data.html", null ],
    [ "APolygon", "class_a_polygon.html", [
      [ "AreaPerimeter", "class_area_perimeter.html", null ],
      [ "Embers", "class_embers.html", null ],
      [ "IgnitionCorrect", "class_ignition_correct.html", [
        [ "IgnitionFile", "class_ignition_file.html", null ]
      ] ],
      [ "Rasterize", "class_rasterize.html", null ],
      [ "XUtilities", "class_x_utilities.html", [
        [ "Intersections", "class_intersections.html", [
          [ "Burn", "class_burn.html", null ]
        ] ]
      ] ]
    ] ],
    [ "Atmosphere", "struct_atmosphere.html", null ],
    [ "AtmosphereGrid", "class_atmosphere_grid.html", null ],
    [ "Attack", "class_attack.html", null ],
    [ "AttackData", "struct_attack_data.html", null ],
    [ "BurnHistory", "struct_burn_history.html", null ],
    [ "BurnStruct", "struct_burn_struct.html", null ],
    [ "BurnUp", "class_burn_up.html", null ],
    [ "BurnupFireRings", "class_burnup_fire_rings.html", null ],
    [ "CanopyCharacteristics", "struct_canopy_characteristics.html", null ],
    [ "celldata", "structcelldata.html", null ],
    [ "celldata32bits", "structcelldata32bits.html", null ],
    [ "CoarseWoody", "struct_coarse_woody.html", null ],
    [ "CompareRect", "class_compare_rect.html", [
      [ "Intersections", "class_intersections.html", null ]
    ] ],
    [ "CompoundCrew", "struct_compound_crew.html", null ],
    [ "Crew", "struct_crew.html", null ],
    [ "CrossThread", "class_cross_thread.html", null ],
    [ "Crown", "class_crown.html", null ],
    [ "crowndata", "structcrowndata.html", null ],
    [ "crowndata32bits", "structcrowndata32bits.html", null ],
    [ "DBFInfo", "struct_d_b_f_info.html", null ],
    [ "DeadMoistureDescription", "struct_dead_moisture_description.html", null ],
    [ "DeadMoistureHistory", "struct_dead_moisture_history.html", null ],
    [ "DisplayData", "struct_display_data.html", null ],
    [ "DurationData", "struct_duration_data.html", null ],
    [ "emberdata", "structemberdata.html", null ],
    [ "EnvironmentData", "struct_environment_data.html", null ],
    [ "FarInputs", "struct_far_inputs.html", null ],
    [ "FarsiteEvent", "class_farsite_event.html", null ],
    [ "FireData", "struct_fire_data.html", null ],
    [ "FireEnvironment2", "class_fire_environment2.html", null ],
    [ "FireRing", "struct_fire_ring.html", null ],
    [ "FireStruct", "struct_fire_struct.html", null ],
    [ "Fms", "struct_fms.html", null ],
    [ "FMS_Aspects", "struct_f_m_s___aspects.html", null ],
    [ "FMS_Cover", "struct_f_m_s___cover.html", null ],
    [ "FMS_Elevations", "struct_f_m_s___elevations.html", null ],
    [ "FMS_Slopes", "struct_f_m_s___slopes.html", null ],
    [ "FmsThread", "class_fms_thread.html", null ],
    [ "FuelConversions", "struct_fuel_conversions.html", null ],
    [ "FuelMoistureMap", "struct_fuel_moisture_map.html", null ],
    [ "FuelStruct", "struct_fuel_struct.html", null ],
    [ "GraphData", "struct_graph_data.html", null ],
    [ "GraphStruct", "struct_graph_struct.html", null ],
    [ "GridTheme", "class_grid_theme.html", [
      [ "LandscapeTheme", "class_landscape_theme.html", null ],
      [ "RasterTheme", "class_raster_theme.html", null ]
    ] ],
    [ "grounddata", "structgrounddata.html", null ],
    [ "grounddata32bits", "structgrounddata32bits.html", null ],
    [ "GroupAirAttack", "class_group_air_attack.html", null ],
    [ "GroupAttackData", "struct_group_attack_data.html", null ],
    [ "headdata", "structheaddata.html", null ],
    [ "headdata2", "structheaddata2.html", null ],
    [ "ImportVectors", "class_import_vectors.html", null ],
    [ "InitialFuelMoisture", "struct_initial_fuel_moisture.html", null ],
    [ "LandDisplayData", "struct_land_display_data.html", null ],
    [ "LandscapeData", "class_landscape_data.html", [
      [ "FELocalSite", "class_f_e_local_site.html", null ],
      [ "FireEnvironment", "class_fire_environment.html", [
        [ "FECalls", "class_f_e_calls.html", null ]
      ] ]
    ] ],
    [ "LandscapeStruct", "struct_landscape_struct.html", null ],
    [ "Mechanix", "class_mechanix.html", [
      [ "MechCalls", "class_mech_calls.html", [
        [ "BurnThread", "class_burn_thread.html", null ]
      ] ]
    ] ],
    [ "MergePoints", "struct_merge_points.html", null ],
    [ "ModelData", "struct_model_data.html", null ],
    [ "NewFuel", "struct_new_fuel.html", null ],
    [ "oldcelldata", "structoldcelldata.html", null ],
    [ "oldheaddata", "structoldheaddata.html", null ],
    [ "OptionsData", "struct_options_data.html", null ],
    [ "OutputData", "struct_output_data.html", null ],
    [ "OutputFile", "class_output_file.html", [
      [ "Rasterize", "class_rasterize.html", null ],
      [ "Vectorize", "class_vectorize.html", null ]
    ] ],
    [ "PerimPoints", "struct_perim_points.html", null ],
    [ "PFIntegration", "class_p_f_integration.html", null ],
    [ "PFrontData", "class_p_front_data.html", null ],
    [ "PFrontStruct", "struct_p_front_struct.html", null ],
    [ "PostFrontal", "class_post_frontal.html", null ],
    [ "Proc_INFO", "struct_proc___i_n_f_o.html", null ],
    [ "OutputFile::RastData", "struct_output_file_1_1_rast_data.html", null ],
    [ "RelativeBurnPeriod", "struct_relative_burn_period.html", null ],
    [ "RingBurn", "class_ring_burn.html", null ],
    [ "RingStruct", "struct_ring_struct.html", null ],
    [ "shape_tree_node", "structshape__tree__node.html", null ],
    [ "ShapeFileUtils", "class_shape_file_utils.html", null ],
    [ "SHPInfo", "struct_s_h_p_info.html", null ],
    [ "SHPObject", "struct_s_h_p_object.html", null ],
    [ "SHPTree", "struct_s_h_p_tree.html", null ],
    [ "Embers::spotdata", "struct_embers_1_1spotdata.html", null ],
    [ "StandardizePolygon", "class_standardize_polygon.html", [
      [ "IgnitionCorrect", "class_ignition_correct.html", null ],
      [ "Intersections", "class_intersections.html", null ]
    ] ],
    [ "StationGrid", "struct_station_grid.html", null ],
    [ "streamdata", "structstreamdata.html", null ],
    [ "TDialog", null, [
      [ "ChangeValue", "class_change_value.html", null ],
      [ "NewGroundResources", "class_new_ground_resources.html", null ],
      [ "WeatherEdit", "class_weather_edit.html", null ],
      [ "WindEdit", "class_wind_edit.html", null ]
    ] ],
    [ "TFarsiteInterface", "class_t_farsite_interface.html", null ],
    [ "Themes", "struct_themes.html", null ],
    [ "TimeCounter", "class_time_counter.html", null ],
    [ "TimeData", "struct_time_data.html", null ],
    [ "TimeStruct", "struct_time_struct.html", null ],
    [ "TOutputs", "class_t_outputs.html", null ],
    [ "TransAirAttack", "struct_trans_air_attack.html", null ],
    [ "TransAttack", "struct_trans_attack.html", null ],
    [ "TransCombMap", "struct_trans_comb_map.html", null ],
    [ "TransEnvtMap", "struct_trans_envt_map.html", null ],
    [ "TransMult", "struct_trans_mult.html", null ],
    [ "TransWndEdit", "struct_trans_wnd_edit.html", null ],
    [ "TransWtrEdit", "struct_trans_wtr_edit.html", null ],
    [ "TScrollBarData", "struct_t_scroll_bar_data.html", null ],
    [ "TTransAccelData", "struct_t_trans_accel_data.html", null ],
    [ "TTransAirAttackData", "struct_t_trans_air_attack_data.html", null ],
    [ "TTransAirData", "struct_t_trans_air_data.html", null ],
    [ "TTransAttackData", "struct_t_trans_attack_data.html", null ],
    [ "TTransDisplayData", "struct_t_trans_display_data.html", null ],
    [ "TTransDurationData", "struct_t_trans_duration_data.html", null ],
    [ "TTransLandDisplayData", "struct_t_trans_land_display_data.html", null ],
    [ "TTransModelData", "struct_t_trans_model_data.html", null ],
    [ "TTransOptionsData", "struct_t_trans_options_data.html", null ],
    [ "TTransOutputData", "struct_t_trans_output_data.html", null ],
    [ "TTransWSData", "struct_t_trans_w_s_data.html", null ],
    [ "TTreeWindow", null, [
      [ "TAtkTreeWindow", "class_t_atk_tree_window.html", null ]
    ] ],
    [ "vec", "structvec.html", null ],
    [ "VectorBarrier", "class_vector_barrier.html", null ],
    [ "VectorStorage", "struct_vector_storage.html", null ],
    [ "VectorTheme", "struct_vector_theme.html", null ],
    [ "ViewRasterLegend", "class_view_raster_legend.html", null ],
    [ "WeatherData", "struct_weather_data.html", null ],
    [ "WindData", "struct_wind_data.html", null ],
    [ "WoodyData", "struct_woody_data.html", null ]
];